(function(g){var window=this;var kZ=function(a){a.i||(a.i=new g.Ao,g.G(a,a.i));return a.i},lZ=function(a,b,c){var d=g.V(a.app);
b.event="iv";a.isFullscreen()&&(b.fs=1);b.ux=1;d.logEvent(b,c)},mZ=function(a){a.M("cardstatechange",a.ud()&&a.De()?1:0)},nZ=function(a){var b=g.Lh(a);
a=g.Sh(a);return new g.nh(b.x,b.y,a.width,a.height)},oZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},pZ=function(a){return"none"!=a.style.display},qZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Nna=function(a){var b=g.Fh(a,"fontSize");
var c=(c=b.match(Kna))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in Lna)return qZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Mna)return a=a.parentNode,c=g.Fh(a,"fontSize"),qZ(a,b==c?"1em":b)}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},Ona=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ck&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.fd("pollChoiceIndex"))},tZ=function(a){a=g.Ra(a);
delete rZ[a];g.Yb(rZ)&&sZ&&sZ.stop()},uZ=function(){sZ||(sZ=new g.M(function(){Pna()},20));
var a=sZ;a.isActive()||a.start()},Pna=function(){var a=(0,g.H)();
g.Lb(rZ,function(b){vZ(b,a)});
g.Yb(rZ)||uZ()},wZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},xZ=function(a,b,c,d){g.Vn.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},vZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;yZ(a,a.progress);1==a.progress?(a.g=0,tZ(a),a.Xc(),a.l()):1==a.g&&a.Mr()},yZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},zZ=function(a,b,c,d,e){xZ.call(this,b,c,d,e);
this.element=a},AZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
zZ.call(this,a,b,c,d,e)},Qna=function(a){return Math.pow(a,3)},Rna=function(a){return 3*a*a-2*a*a*a},BZ=function(a){g.D.call(this);
this.i=a||window;this.g=[]},Sna=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.Vr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},CZ=function(a,b){(0,g.A)(b,function(c){g.ds("visualElementShown",{csn:a,
ve:g.Ks(c),eventType:4},g.is,void 0,void 0)})},DZ=function(a,b){(0,g.A)(b,function(c){g.ds("visualElementHidden",{csn:a,
ve:g.Ks(c),eventType:8},g.is,void 0,void 0)})},EZ=function(a,b){g.Sf.call(this);
this.Tj=a;this.Zp=b;this[g.uf]=!1},JZ=function(a,b,c,d){EZ.call(this,a,b);
a=this.Zp;b=this.ga();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.Fa(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Tna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Zp;a=this.ga();if(d instanceof FZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof GZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=HZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=HZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=HZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=IZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},KZ=function(){},LZ=function(a,b){EZ.call(this,a,b)},MZ=function(){this.Ta=[];
this.Ca=[];this.Td=[]},NZ=function(a,b,c,d){var e=a.yd[0]-b*Math.cos(g.td(d))+b*Math.cos(g.td(d+90)),f=a.yd[1]-c*Math.sin(g.td(d))+c*Math.sin(g.td(d+90));
a.Ta.push(3);a.Ca.push(1);a.Td.push(b,c,d,90,e,f);a.Xk=!1;a.yd=[e,f]},Vna=function(a,b){for(var c=a.Td,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Una[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},OZ=function(a,b,c,d){JZ.call(this,a,b,c,d)},i_=function(a,b){this.g=a;
this.i=b},w_=function(a,b,c,d,e){g.go.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Tna=function(a){var b=a.Hj();
return b?b.width/(a.l?new g.wd(a.l,a.I):a.Hj()).width:0},GZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},FZ=function(a,b){this.F=a;
this.H=null==b?1:b},x_=function(a,b){EZ.call(this,a,b)},y_=function(a,b,c,d){JZ.call(this,a,b,c,d)},z_=function(a,b,c,d,e){w_.call(this,a,b,c,d,e);
this.g={};this.R=g.Od&&!g.od(526);this.P=new g.$m(this)},HZ=function(a,b,c){a=a.N.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},A_=function(a,b,c,d){b=HZ(a,"path",{d:Wna(b)});
c=new y_(b,a,c,d);a.o.ga().appendChild(c.ga())},Wna=function(a){var b=[];
Vna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},IZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Xna++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},Yna=function(){B_||(B_=new g.Fg(400),B_.start());
return B_},C_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.B)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.B)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Js(a.trackingParams));var k=(0,g.B)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.jv=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.B)(u.loggingUrls||[],c);p.Dl=g.Tb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.B)(n.impressionUrls||[],c);p.OD=(0,g.B)(n.hovercardShowUrls||[],c);p.Xb={itct:n.trackingParams};p.visualElement=g.Js(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Cm=!1,p.ao=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Cm=!1,p.ao=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Tb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.Cm=!1;p.ao="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var z=d(r.subscribedButtonText);if(r.subscribed){var C=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else C=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Tb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(z||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:C,unsubscribeText:z,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Tb(u,"urlEndpoint","url"),p.Cm=!0,p.ao="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},D_=function(a){g.sK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.I=[];a=g.X(a);this.P=g.Ey(a)||g.Gy(a);this.zA=!0;this.D=0;this.F=new g.Ln;this.u=new g.us(this);g.G(this,this.u);this.u.K(this.player,g.TD("creatorendscreen"),this.JE);this.u.K(this.player,"crx_creatorendscreen",this.KE);this.u.K(this.player,"resize",this.ib);this.u.K(window,"focus",this.BL);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},E_=function(a){return a.player.getVideoData().Nb?"current":a.P?"new":"current"},F_=function(a){return"creator-endscreen-editor"===a},G_=function(a,b){g.aK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Zna(a);c=[];var d=new g.QD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({B:"div",G:"ytp-ce-shadow"}),g.eK(a.player,a.l.element,4),a.A=new g.PP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=$na(a,e);a.g[e.id]=f;a.C[e.id]=e;g.eK(a.player,f.element,4);var k=new g.QD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);aoa(a,f,e)}g.YJ(a.player,
c);a.ib()}},Zna=function(a){var b=g.Zs(),c=g.$s();
c&&b&&a.i.visualElement&&g.Ls(c,b,[a.i.visualElement],void 0)},$na=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:H_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:I_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:H_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:I_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",J:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body",J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:I_(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mn(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",J:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:H_(b)}]};c=new g.W(c);var d=g.Fd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.Xb.itct}else e="endscreen",f=null;e=new g.GV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",J:[{B:"div",G:"ytp-ce-expanding-overlay-body",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:I_(a,b.targetUrl),target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:H_(b)},{B:"div",G:"ytp-ce-expanding-icon",L:J_(b.iconUrl)}]},c=new g.W(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},H_=function(a){if(a.jv)var b=
a.jv.thumbnails;
return J_(b?b[b.length-1].url:null)},J_=function(a){return a?{style:"background-image: url("+a+")"}:{}},aoa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.x)(a.ar,a,b,c));b.ca("mouseleave",(0,g.x)(a.Rr,a,b,c));g.X(a.player).g||b.ca("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.x)(a.Fy,a,c));b.ca("keypress",(0,g.x)(a.Fy,a,c));b.ca("focus",(0,g.x)(function(l,m){this.ar(l,m)},a,b,c));
b.ca("blur",(0,g.x)(function(l,m){this.Rr(l,m)},a,b,c));
b.ca("touchstart",(0,g.x)(a.ar,a,b,c));var f=g.Hd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Sn(b.element,"ytp-ce-element-hover");g.Sn(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.x)(function(l,m){this.zA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),K_(this,m.id,!0)):(g.Sn(l.element,"ytp-ce-force-expand"),g.Sn(l.element,"ytp-ce-element-hover"),K_(this,m.id,!1))},a,b,c);
a=(0,g.x)(function(l,m){m&&(l.ca("blur",function(){pZ(m)&&this.zA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Hd("ytp-sb-subscribe",b.element));a(g.Hd("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},I_=function(a,b){var c=g.X(a.player);
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.jz(c)+b}else return"";return b},K_=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},L_=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||F_(g.X(a.player).playerStyle))c&&c();else{b=boa(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Zq(b[a],d)}},M_=function(a,b,c){L_(a,b.clickUrls,c);
(a=g.$s())&&b.Cm&&g.Ns(a,b.visualElement)},boa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(coa(b[e],c));return d},coa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},N_=function(a){return g.Ma(a)&&a.length?a[0]:a},O_=function(a){var b=/.+/;
return g.Fa(a)&&null!=b&&null!=a&&a.match(b)?a:""},P_=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},Q_=function(a){return g.Fa(a)?a:""},R_=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},S_=function(a,b){return"true"==a||"false"==a?"true"==a:b},T_=function(a,b){return g.Fa(a)?parseFloat(a):b},U_=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.qd(a,b,c);if(a>=b&&a<=c)return a}return e},doa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},V_=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.A)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},eoa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.kh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},foa=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},goa=function(a){this.externalId=a},hoa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},W_=function(a){if(!a)return null;
var b=g.Dc(Q_(a.value));b=g.Ac(b);if(!b)return null;var c=R_(a.target,ioa,"current");return null==c?null:new hoa(b,c,S_(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},X_=function(a){return a.value?a.value:null},joa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},moa=function(a){if(!a)return null;
var b=R_(a.type,koa),c=R_(a.trigger,loa),d=N_(a.url);d=W_(d?d:null);a=N_(a.subscribeData);var e=a?a:null;e?(a=Q_(e.external_user_id),e=Q_(e.subscription_token),a=a&&e?new goa(a):null):a=null;return b?new joa(b,c,d,a):null},Y_=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},Z_=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},$_=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Xi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},a0=function(a,b){if(!a)return null;
var c=T_(a.x,0),d=T_(a.y,0),e=T_(a.w,0),f=T_(a.h,0),k=doa(a.t),l=T_(a.d,0),m=T_(a.px,0),n=T_(a.py,0),p=T_(a.scaleSlope,1),r=T_(a.scaleSlopeX,p);p=T_(a.scaleSlopeY,p);var u=R_(a.scaleDimension,noa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},d0=function(a,b){var c=b0(b,c0(a,new g.nh(a.x,a.y,a.Xi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.qd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.qd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},c0=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=Y_(c,a.o,f);
a=Z_(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.nh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},e0=function(a){return a?a0(a,function(b,c,d,e,f,k,l,m,n,p,r){return new $_(b,c,d,e,f,k,l,m,n,p,r)}):null},f0=function(a,b){this.g=a;
this.i=b||null},b0=function(a,b){var c=a.i?d0(a.i,new f0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.ud?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},g0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){$_.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},ooa=function(a){if(!a)return null;
var b=T_(a.sx,0),c=T_(a.sy,0);return a0(a,function(d,e,f,k,l,m,n,p,r,u,z){return new g0(d,e,f,k,l,b,c,m,n,p,r,u,z)})},poa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=z},h0=function(a){if(!a)return null;
var b=P_(a.fgColor,"#1A1A1A"),c=P_(a.bgColor,"#FFF"),d=P_(a.borderColor,"#000"),e=U_(a.borderWidth,0,5,!1,0),f=U_(a.bgAlpha,0,1,!1,.8),k=P_(a.highlightFontColor,"#F2F2F2"),l=U_(a.highlightWidth,0,5,!1,3),m=Q_(a.textAlign),n=U_(a.textSize,3.3,30.1,!0,3.6107),p=Q_(a.fontWeight),r=eoa(a.padding),u=foa(a.effects),z=U_(a.cornerRadius,0,10,!0,0);a=N_(a.gradient);if(a=a?a:null){var C=U_(a.x1,0,100,!0,0),E=U_(a.y1,0,100,!0,0),F=U_(a.x2,0,100,!0,100),L=U_(a.y2,0,100,!0,100),aa=P_(a.color1,"#FFF"),qa=P_(a.color2,
"#000");a=new qoa(C,E,F,L,aa,qa,U_(a.opacity1,0,100,!0,100),U_(a.opacity2,0,100,!0,0))}else a=null;return new poa(b,c,d,e,f,k,l,m,n,p,r,u,z,a)},qoa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},roa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},toa=function(a){if(!a)return null;
var b=R_(a.type,soa,"rect"),c=V_(a.rectRegion,e0),d=V_(a.anchoredRegion,ooa);a=V_(a.shapelessRegion,e0);return new roa(b,c,d,a)},i0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},uoa=function(a,b){this.i=a;
this.g=b},voa=function(a,b){this.state=a;
this.ref=b},j0=function(a){if(!a)return null;
var b=R_(a.state,woa);a=O_(a.ref);return b?new voa(b,a):null},xoa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},yoa=function(a){if(!a)return null;
var b=V_(a.condition,j0),c=V_(a.notCondition,j0),d=S_(a.show_delay,!1);a=S_(a.hide_delay,!1);return b||c?new xoa(b,c,d,a):null},zoa=function(a,b,c){(0,g.A)(a.g,g.Sa(b,!1),c);
(0,g.A)(a.l,g.Sa(b,!0),c)},k0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.id=a;
this.author=b;this.type=c;this.style=d;this.l=e;this.segment=f;this.i=k||[];this.A=l||[];this.g=m;this.u=n;this.o=p;this.data=r;this.Ya=u;this.itct=z},Coa=function(a){if(!a)return null;
var b=O_(a.id),c=O_(a.author),d=R_(a.type,Aoa),e=R_(a.style,l0),f=Q_(N_(a.TEXT)),k=Q_(a.data);k=0!=k.length?JSON.parse(k):{};var l=N_(a.segment);var m=l?l:null;m?(O_(m.timeRelative),l=O_(m.spaceRelative),l=(m=V_(m.movingRegion,toa))?new uoa(l,m):null):l=null;m=V_(a.action,moa);var n=V_(a.trigger,yoa),p=N_(a.appearance);(p=h0(p?p:null))||(p=h0({}));var r=R_(a.coordinate_system,Boa,"video_relative"),u=S_(a.closeable,!0),z=Q_(a.log_data);a=Q_(a.itct);return b&&d?new k0(b,c,d,e,f,l,m,n,p,r,u,k,z,a):null},
n0=function(a){return m0(a,function(b){return"click"==b.trigger})},m0=function(a,b){return(0,g.Mj)(a.i,b,void 0)},Doa=function(a,b,c){(0,g.A)(a.i,b,c)},Eoa=function(a,b){return g.Ya(a.i,b,void 0)},o0=function(a,b,c){(0,g.A)(a.A,b,c)},Foa=function(a,b){(0,g.B)(a.A,b,void 0)},q0=function(a){return(a=p0(a))?i0(a):null},p0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},r0=function(a,b){var c=q0(a);
return c&&b?Z_(b,c.i,c.g?c.g:"xy"):1},t0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;zoa(b,function(d,e){var f=s0(e.state,e.ref);this.i.subscribe(f,(0,g.x)(this.o,this,f,d));this.g[f]=d},this)},s0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},u0=function(){this.g=!1;
this.u=this.i=null},v0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new z_(b,c,void 0,void 0,void 0),a.i=b,a.i.gq(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ga()));
return a.i},w0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Lb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},x0=function(a,b){var c=g.fo(g.eo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Goa=function(a,b){var c=x0(a,w0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=x0(a,w0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},w0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=x0(a,w0("feComposite",{"in":c,in2:b,operator:"in"}));return x0(a,w0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Hoa=function(a,b){var c=x0(a,w0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=x0(a,w0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=x0(a,w0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=x0(a,w0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=x0(a,w0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=x0(a,w0("feComposite",{operator:"out","in":c,in2:d}));return x0(a,w0("feComposite",{operator:"over","in":b,in2:c}))},Ioa=function(a,b){return b},Joa=function(a){var b=
w0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(d){a:{switch(d){case "bevel":d=Goa;break a;case "dropshadow":d=Hoa;break a}d=Ioa}c=d(b,c)});
return b},Koa=function(a){a=(0,g.Yd)(a,function(b){return b in y0});
g.rb(a,function(b,c){return y0[b]-y0[c]});
return a},Loa=function(a){return g.Ya(a,function(b){return"dropshadow"==b})?new g.kh(0,7,7,0):new g.kh(0,0,0,0)},z0=function(a,b,c){var d=new MZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);NZ(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);NZ(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);NZ(d,b,b,90);d.Zb(a.left+c,a.top+b+c);NZ(d,b,b,180);d.close();return d},A0=function(a,b,c,d){var e=a.u;
e?a=new GZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new FZ(a.bgColor,d?Math.max(b,.9):b));return a},B0=function(a,b){var c=g.oh(a),d=Loa(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.nh(c.left,c.top,c.right-c.left,c.bottom-c.top)},C0=function(a,b,c){if(c.length&&(b=g.Fd(document,"g",void 0,b),b.length)){var d=Koa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Joa(d),a=0<d.childNodes.length?IZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},D0=function(){u0.call(this);
this.o=0},Moa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},E0=function(){u0.apply(this,arguments)},F0=function(){u0.apply(this,arguments)},G0=function(){D0.apply(this,arguments)},H0=function(a,b,c,d,e){g.D.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Z=e;this.F=!1;this.aa=new BZ(this);g.G(this,this.aa);this.N=this.u=this.C=this.P=this.i=null;this.W=!1;this.ba=this.H=this.I=null;this.pn=new g.zl(this.qD,100,this);g.G(this,this.pn);this.D=new g.M(this.tw,500,this);g.G(this,this.D);this.O=this.l=this.o=null},Noa=function(a,b){var c=(0,g.x)(function(d,e,f){e=f?I0(this,e,(0,g.x)(f,this)):I0(this,e);
this.aa.ca(b,d,e)},a);
c("mouseover","G",a.qx);c("mouseout","F",a.Bg);c("click","D");c("touchend","D")},Ooa=function(a){if(a.g.o){if(m0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Th(a.o,!1),g.Ep(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.aa.ca(b,"click",I0(a,"E",c));a.aa.ca(b,"touchend",I0(a,"E",c))}},I0=function(a,b,c){return(0,g.x)(function(d){if(this.Z)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Th(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.ge(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Th(e,
!0)}}e=nZ(d.target);d=new g.ud(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.M(b,this.g)},a)},L0=function(a){if(a.i||a.l){var b=q0(a.g);
if(b){var c=J0(a);if(a.i){b=d0(b,c);var d=g.RJ(a.A).getVideoContentRect();g.Rh(a.i,b.width,b.height);g.Hh(a.i,b.left,b.top);a.P=new g.nh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=q0(a.g))&&d?Y_(d,e.o,e.g?e.g:"xy"):1;var f=r0(a.g,d);d=a.g.g;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.kh(d,d,d,d));d=new g.kh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.RJ(a.A).getVideoContentRect();var p=g.WJ(a.A);g.ph(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.u&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=K0(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Rh(a.u,f.width,f.height);g.Hh(a.u,f.left,f.top)}a.o&&(r?b=new g.ud(r.left+
r.width-23-18,a.W?r.top+2:r.top+r.height-18-2):(r=K0(a,18,b,d,e),b=new g.ud(r.left,r.top),g.Rh(a.o,r.width,r.height)),g.Hh(a.o,b));a.N=new g.nh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.aa.ca(g.RJ(a.A),"mousemove",a.BF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.wd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.nh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.nh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Rh(a.u,
r.width,r.height),g.Hh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Hh(a.o,r&&e?new g.ud(b.width-9,-9):r?new g.ud(b.width-9,45<b.height?9:b.height-9):e?new g.ud(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.ud(45<b.width?b.width-9-18:-9,b.height-9):new g.ud(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.g;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.RJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
r0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Hd("annotation-link-icon",a))?pZ(b):!1;e=(d=g.Hd("annotation-close-button",a))?pZ(d):!1;r&&g.Th(b,!1);e&&g.Th(d,!1);m=f="";if(n=g.Hd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Nna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Th(d,!0);r&&g.Th(b,!0)}}}},K0=function(a,b,c,d,e){var f=0<e;
b=new g.nh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.W=!0);return b},M0=function(a){return"label"!=a.g.style||a.l.g},J0=function(a){var b=g.RJ(a.A).getVideoContentRect();
if("player_relative"==a.g.u){var c=g.RJ(a.A).getPlayerSize();b=new g.nh(-b.left,-b.top,c.width,c.height)}else b=new g.nh(0,0,b.width,b.height);return new f0(b,a.O?q0(a.O):null)},N0=function(a,b){return b?new g.nh(a.x+b.left,a.y+b.top,b.width,b.height):null},O0=function(a,b,c){g.D.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Poa(b,a)},Poa=function(a,b){Foa(a,function(c){return new t0(a.id,c,b)})},P0=function(a){a.i.unsubscribe("resize",a.ox,a);
a.i.unsubscribe("onVideoAreaChange",a.ez,a)},Q0=function(a){a.g&&(a.g.stop(),a.g=null)},R0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Qoa=function(a,b){this.merchant=a;
this.price=b},Roa=function(a){this.g=a;
this.i={}},Soa=function(a){var b={};
b=(b["iv-event"]=1,b);lZ(a.g,b,void 0)},V0=function(a,b,c,d){if(b){var e=S0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=T0(a,"cta_annotation_shown",e,c);U0(a,e,Toa(b,d))}},W0=function(a,b,c,d,e,f){if(b){var k=S0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=T0(a,"cta_annotation_clicked",k,e);U0(a,k,b,c,f)}},X0=function(a,b){if(b){var c=S0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=T0(a,"cta_annotation_closed",c);U0(a,c,d)}},Toa=function(a,b){return b?(0,g.B)(a,g.Sa(function(c,d){return g.cn(d,c)},b)):a},T0=function(a,b,c,d){d=d?g.ib(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.vu){if((b=a.vu[b])&&g.av(b)){a=g.Xc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Gn){b=g.nq(a.Gn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},U0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(n){f++;
g.Zq(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));lZ(a.g,b,m)},S0=function(a,b){var c={};
if(b){var d=new g.Sm(b);(0,g.A)(d.Hd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},Y0=function(a,b,c,d,e){e=S0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;U0(a,e,d)},Z0=function(a,b,c,d){c&&(c=S0(a,c),c["iv-event"]=b,U0(a,c,d))},Uoa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.xb=c;this.videoData=d;this.logger=e;this.Y=f;this.i=k},$0=function(a,b){this.g=a;
this.o=b;this.i=new g.Ln},Woa=function(a,b){var c=[];
(0,g.A)(b.choices,function(k){c.push(Voa(this,b,k))},a);
var d={B:"ul",L:{role:"radiogroup"},J:c},e={};b.Qd&&(e["aria-label"]=g.cN("$POLL_TITLE - Inicia sesi\u00f3n para votar.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",J:[a1(a,"h2",e,b.title),{B:"form",J:[{B:"fieldset",J:[d]}]}]}];b.Qd&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],J:[{B:"h2",U:"\u00bfTe gustar\u00eda votar?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:X_(b.Qd)},J:[{B:"span",V:["iv-button-content"],U:"Iniciar sesi\u00f3n"}]}]}));
f=new g.W({B:"div",V:f,J:d});d=f.element;b1(b,d);Sna(a.g.g,d,g.Sa(a.u,b),a);(0,g.A)(g.Gd("iv-card-poll-choice-input",d),function(k){this.g.g.ca(k,"focus",g.Sa(this.l,!0));this.g.g.ca(k,"blur",g.Sa(this.l,!1))},a);
b.Qd&&(d=g.Hd("iv-card-sign-in-button",d),a.o(d,b.Qd,b.id,b.Xb,b.Ya,b.pd.click,5));return f},f1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.OM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.ZD&&b.zu?{B:"span",V:d,L:e,U:b.zu}:"";c={B:"div",V:["iv-card",c],J:[{B:"a",G:"iv-click-target",L:{href:X_(b.url)},J:[c1(b.bl,d?{B:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",J:[{B:"h2",G:"iv-card-primary-link",U:b.title},d1(a,b)]}]}]};c=new g.W(c);e1(a,c,b);return c},g1=function(a,b){return b.customMessage?a1(a,"div",
"iv-card-message",b.customMessage):""},c1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},J:d}},d1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(d){c.push(a1(this,"li","",d))},a);
return{B:"ul",G:"iv-card-meta-info",J:c}},Voa=function(a,b,c){return{B:"li",
G:R0(b,c.index),J:[{B:"label",J:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.id.replace(/[^a-z0-9-]/gi,"-")+c.index.toString(),value:c.index.toString(),"data-poll-choice-index":c.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",J:[{B:"span",G:"iv-card-poll-choice-percent"},a1(a,"span",void 0,c.desc)]}]},{B:"div",G:"iv-card-poll-result",J:[{B:"div",G:"iv-card-poll-result-bar"}]}]}},a1=function(a,b,c,d){c?g.Fa(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):
c={};
c.dir=g.Mn(a.i,d);return{B:b,L:c,U:d}},h1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.cp&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.cp+");");d.dir=g.Mn(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,J:e}},b1=function(a,b){var c=0;
(0,g.A)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Hd(R0(a,e.index),b);e=e.count/c;null==a.he&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.he==d);f.getElementsByTagName("input")[0].checked=a.he==d;var k=Math.floor(100*e).toFixed(0),l=g.Hd("iv-card-poll-choice-percent",f);g.be(l,g.cN("$PERCENT%",{PERCENT:k}));f=g.Hd("iv-card-poll-result-bar",f);g.zh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.he);g.K(b,"iv-card-poll-expanded",
null!=a.he&&1<a.choices.length)},e1=function(a,b,c,d,e){c.Qd&&i1(a,g.Gd("iv-card-sign-in-button",b.element),c,c.Qd,e);
c.url&&i1(a,g.Gd("iv-click-target",b.element),c,c.url,d)},i1=function(a,b,c,d,e){(0,g.A)(b,function(f){if(e){var k=(0,g.x)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.ca(f,"click",k)}else d&&this.o(f,d,c.id,c.Xb,c.Ya,c.pd.click,5)},a)},j1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},l1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=k1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},k1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Xoa=function(a){a=X_(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!l1(a))||(b=g.Qg(g.Sg(5,a))||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.lq(a);if(!b||!b.v)return null;if(b=b.t)return j1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.jq(a[1]))&&a.t?j1(a.t):-1},m1=function(a){a=X_(a);
a=a.replace(/https?:\/\//g,"");return l1(a)?(a=g.lq(a))&&a.v?a.v:null:null},Yoa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},n1=function(a,b){return b?b:l1(a)?"current":"new"},o1=function(a,b){g.D.call(this);
this.Ba=a;this.context=b;this.kt=!1;this.X=0},Zoa=function(a){return(0,g.H)()-a.X},$oa=function(a,b,c,d,e,f){var k=X_(b);
if(k){var l=n1(k,b.target),m=(0,g.x)(function(){b.g&&this.context.Y.pauseVideo();var p=this.context.videoData.Nb||!1,r=g.lq(k||"");p&&r&&(r.v||r.list)?g.MX(this.context.Y.app,r.v,c,r.list,!1,void 0):g.kL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Zoa(a);W0(a.context.logger,d,m,n,e,f);l1(k)||(a=g.$s(),d=c.itct,a&&d&&g.Ns(a,g.Js(d)))}},r1=function(a,b,c){o1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.W=this.wa=this.u=this.va=!1;this.ba=null;this.N=new g.M(g.Ja,c.xb.ed?4E3:3E3);g.G(this,this.N);this.ka=new g.M(g.Ja);g.G(this,this.ka);this.D=new $0(c,(0,g.x)(this.Li,this),(0,g.x)(this.Nm,this));this.F=new g.W({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{B:"div",
G:"iv-drawer-content"}]});g.G(this,this.F);this.A=this.F.element;this.ua=new g.PP(this.F,330);g.G(this,this.ua);this.xa=g.Hd("iv-drawer-header-text",this.A);this.o=g.Hd("iv-drawer-content",this.A);this.l=[];this.ma=this.O=this.C=this.Z=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&p1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&q1(d)});
this.P=this.H=this.fa=null},apa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c){var d=b.data.tracking||{};d={QD:d.impression,click:d.click,close:d.close,yM:d.teaser_impression,Ns:d.teaser_click};var e=b.data.tracking_params||{},f=null;switch(c){case "collaborator":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):
null,de:e.icon?g.Js(e.icon):null,channelId:b.data.channel_id,customMessage:b.data.custom_message,SL:b.data.image_url,title:b.data.title,metaInfo:b.data.meta_info,url:W_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};s1(a,d);break;case "episode":case "movie":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,bl:b.data.image_url,zu:b.data.badge_symbol||"",priceText:b.data.price_text||"",title:b.data.title,metaInfo:b.data.meta_info,ZD:!!b.data.is_paygated,OM:!!b.data.user_has_entitlement,url:W_({target:b.data.target||"new",value:b.data.url})};s1(a,d);break;case "playlist":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,
teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,bl:b.data.image_url,playlistVideoCount:b.data.playlist_video_count,customMessage:b.data.custom_message,title:b.data.title,metaInfo:b.data.meta_info,url:W_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};s1(a,
d);break;case "poll":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,title:b.data.title,choices:b.data.choices,he:b.data.hasOwnProperty("old_vote")?b.data.old_vote:null,Qd:b.data.signin_url?W_({target:"current",
value:b.data.signin_url}):null,XM:b.data.hasOwnProperty("xsrf_token")?b.data.xsrf_token:null};s1(a,d);break;case "productListing":b.data.signin_url&&(f=W_({target:"current",value:b.data.signin_url}));c=[];for(var k=b.data.offers||[],l=0;l<k.length;l++)c.push(new Qoa(g.bd(k[l].merchant),g.bd(k[l].price)));d={zQ:!1,id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain,showLinkIcon:b.data.show_link_icon,cp:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message,url:W_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Qd:f,uA:b.data.signin_title||null,tA:b.data.signin_message||null,offers:c};
s1(a,d);break;case "simple":b.data.signin_url&&(f=W_({target:"current",value:b.data.signin_url}));d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain,
showLinkIcon:b.data.show_link_icon,cp:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message,url:W_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Qd:f,uA:b.data.signin_title||null,tA:b.data.signin_message||null};s1(a,d);break;case "video":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,bl:b.data.image_url,videoDuration:b.data.video_duration||null,customMessage:b.data.custom_message,title:b.data.title,metaInfo:b.data.meta_info,isLiveNow:!!b.data.is_live_now,url:W_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})},s1(a,d)}}},bpa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,
0x8000000000000,"",function(){p1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){q1(a)});
var c=b.data.headerText;g.be(a.xa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.fa=g.Js(b.data.trackingParams);a.P=g.Js(b.data.closeTrackingParams);a.H=g.Js(b.data.iconTrackingParams)},u1=function(a,b){var c=cpa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Fb.id),g.Xd(c.lp),g.eb(a.l,c),a.Ll(),t1(a))},p1=function(a,b,c,d){if(!a.u){a.ua.show();
a.Z=new g.M(function(){g.J(a.context.Y.getRootNode(),"ytp-iv-drawer-open")},0);
a.Z.start();a.ba=g.Mr(a.o,"mousewheel",(0,g.x)(a.ZE,a));a.u=!0;a.X=(0,g.H)();Y0(a.context.logger,a.R,7,void 0,d&&d.Fb?d.Fb.Ya:void 0);var e=g.$s();e&&a.fa&&a.P&&CZ(e,[a.fa,a.P]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(k){k.Qw||(k.Qw=!0,V0(a.context.logger,k.Fb.Ya,k.Fb.pd.QD,f));e&&CZ(e,[k.Fb.rf])});
mZ(a.i);c&&(a.C=new g.M(function(){a.ea=a.O;a.ma.focus()},330),a.C.start())}},q1=function(a){a.u&&(a.ua.hide(),g.Nr(a.ba),a.ba=null,g.Sn(a.context.Y.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,mZ(a.i),a.C&&a.C.stop(),a.C=new g.M(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.C.start())},dpa=function(a){var b=g.Hd("iv-drawer-close-button",a.A);
a.context.g.ca(b,"click",a.qC,a);a.context.g.ca(a.o,"touchend",function(){a.N.start()});
a.context.g.ca(a.o,"scroll",a.AC,a);a.context.i.subscribe("onHideControls",function(){a.W=!0});
a.context.i.subscribe("onShowControls",function(){a.W=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.W=g.Qn(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Op("iv-button-shown",a.jE,a));a.I.push(g.Op("iv-button-hidden",a.iE,a));a.I.push(g.Op("iv-teaser-shown",a.mE,a));a.I.push(g.Op("iv-teaser-hidden",a.lE,a));a.I.push(g.Op("iv-teaser-clicked",a.kE,a))},s1=function(a,b){a.va||(g.Rn(a.ga(),["html5-stop-propagation",
"iv-drawer-manager"]),g.eK(a.i,a.A,5),dpa(a),a.O=g.Hd("ytp-cards-button",a.i.getRootNode()),a.ma=g.Hd("iv-drawer-close-button",a.A),a.va=!0);u1(a,b.id);var c=epa(a,b);if(c){var d={Fb:b,lp:c.element,Qw:!1},e=fpa(a,d);g.lb(a.l,e,0,d);c.g(a.o,e);a.Ll();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.kM,d)):(c=1E3*a.context.Y.getCurrentTime(),5E3>c&&c>b.startMs&&a.fA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.fA,d)),t1(a))}},epa=function(a,b){switch(b.type){case "simple":var c=
a.D,d=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",e=h1(c,b),f=["iv-card"];b.Qd&&f.push("iv-card-unavailable");d=[{B:"a",G:"iv-click-target",L:{href:X_(b.url)},J:[c1(b.imageUrl,d),{B:"div",G:"iv-card-content",J:[a1(c,"h2",void 0,b.title),e]}]}];b.Qd&&d.push({B:"div",V:["iv-card-sign-in"],J:[a1(c,"h2",void 0,b.uA||""),{B:"p",U:b.tA},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:X_(b.Qd)},J:[a1(c,"span","iv-button-content","Iniciar sesi\u00f3n")]}]});f=new g.W({B:"div",V:f,J:d});e1(c,f,b,void 0,
void 0);return f;case "collaborator":return c=a.D,f={B:"div",V:["iv-card","iv-card-channel"],J:[{B:"a",V:["iv-click-target"],L:{href:X_(b.url),"data-ytid":b.channelId},J:[c1(b.SL),{B:"div",G:"iv-card-content",J:[g1(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},d1(c,b)]}]}]},f=new g.W(f),e1(c,f,b),f;case "episode":return f1(a.D,b,"iv-card-episode");case "movie":return f1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,f={B:"div",V:["iv-card","iv-card-playlist"],J:[{B:"a",G:"iv-click-target",
L:{href:X_(b.url)},J:[c1(b.bl,{B:"div",G:"iv-card-image-overlay",J:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",J:[g1(c,b),a1(c,"h2","iv-card-primary-link",b.title),d1(c,b)]}]}]},f=new g.W(f),e1(c,f,b),f;case "poll":return Woa(a.D,b);case "productListing":c=a.D;e=0!=b.offers.length;f=["iv-card"];d="";var k=h1(c,b);e&&(f.push("iv-card-product-listing"),d="iv-card-primary-link",e=b.offers[0],k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",
U:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",J:k});f={B:"div",V:f,L:{tabindex:"0"},J:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:X_(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",J:[b.sponsored?{B:"div",G:"iv-card-sponsored",J:["Patrocinado",{B:"div",G:"iv-ad-info-container",J:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",J:[{B:"div",
G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:X_(b.url)},J:[a1(c,"h2",d,b.title),k]}]}]};f=new g.W(f);d=g.Sd("span");g.be(d,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");f.kb(d,"adInfo");e1(c,f,b);return f;case "video":return c=a.D,f=b.isLiveNow?{B:"span",V:["yt-badge","yt-badge-live"],U:"EN DIRECTO AHORA"}:"",f={B:"div",V:["iv-card",
"iv-card-video"],J:[{B:"a",G:"iv-click-target",L:{href:X_(b.url)},J:[c1(b.bl,b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",J:[g1(c,b),a1(c,"h2","iv-card-primary-link",b.title),d1(c,b),f]}]}]},f=new g.W(f),e1(c,f,b),f}return null},fpa=function(a,b){if(0==a.l.length)return 0;
var c=g.Za(a.l,function(d){return b.Fb.startMs>d.Fb.startMs||b.Fb.startMs==d.Fb.startMs&&b.Fb.timestamp>=d.Fb.timestamp?!0:!1});
return-1==c?0:c+1},gpa=function(a){return a.g?"productListing"==a.g.Fb.type:(0,g.jj)(a.l,function(b){return"productListing"==b.Fb.type})},t1=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",gpa(a))},v1=function(a,b){if(a.F.Da()){var c=new xZ([0,
a.o.scrollTop],[0,b.lp.offsetTop],600,Rna);a.context.l.ca(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.ca(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.KC(a.F,!0),a.o.scrollTop=b.lp.offsetTop,g.KC(a.F,!1)},w1=function(a){return a.g&&a.g.Fb?a.g.Fb:a.l[0]&&a.l[0].Fb?a.l[0].Fb:null},cpa=function(a,b){return g.Ya(a.l,function(c){return c.Fb.id==b})},x1=function(a,b,c){o1.call(this,a,b);
this.annotation=c;this.isActive=!1},hpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},y1=function(a,b,c){x1.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},z1=function(a,b,c){x1.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Th(this.l,!1);g.Th(this.i,!0)},700,this);
g.G(this,this.A)},ipa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ga().setAttribute("aria-hidden",!0);a.ga().setAttribute("aria-label","Promoci\u00f3n");a.ga().tabIndex=0;var e=a.annotation.Jb(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Li(k,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Uc(f,X_(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.Q(a.context.xb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Li(a.ga(),e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c)}g.J(a.g,"iv-click-target");e&&a.Li(a.g,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c);break;case "playlist":case "video":l=
g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"EN DIRECTO AHORA")),g.J(a.g,"iv-click-target"),e&&a.Li(a.g,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expandir";a.context.g.ca(a.i,
"click",g.Sa(a.iq,5E3),a);c.appendChild(a.i);g.Th(a.i,!1);a.context.g.ca(a.ga(),"mouseover",a.sD,a);a.context.g.ca(a.ga(),"mouseout",a.rD,a);a.context.g.ca(a.ga(),"touchend",g.Sa(a.iq,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Cerrar";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.kD:a.jD,a);c.appendChild(a.l);g.Rn(a.ga(),d);k&&(a.ga().appendChild(k),n&&k.appendChild(n));a.ga().appendChild(a.D);a.ga().appendChild(c)},A1=function(a){a.u||a.F||a.o||
(g.J(a.ga(),"iv-promo-collapsed"),a.u=!0,a.A.start())},B1=function(a){a.A.stop();
a.u&&(g.Tn(a.ga(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Th(a.i,!1),g.Th(a.l,!0))},D1=function(a,b){a.o||(a.o=g.Gg(function(){C1(this);
A1(this)},b,a))},C1=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},E1=function(a){g.sK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Roa(a);this.A=new g.us(this);g.G(this,this.A);this.C=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.x)(this.M,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.x)(this.M,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.x)(this.M,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.x)(this.M,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.x)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.VI,this);this.subscribe("onShowControls",this.OK,this);this.subscribe("presentingplayerstatechange",this.YJ,this);this.subscribe("resize",this.vn,this);this.subscribe("G",this.HE,this);this.subscribe("F",this.Bg,this);this.subscribe("D",this.RH,this);this.subscribe("E",this.uI,this);g.X(this.player).I.subscribe("vast_info_card_add",this.dz,this);this.R=new g.us(this);g.G(this,this.R);this.R.K(this.player,g.TD("annotations_module"),this.FE);this.R.K(this.player,
"crx_annotations_module",this.GE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.W=g.Rd("DIV","video-custom-annotations");this.u=new g.W({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.eK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({B:"div",V:["ytp-iv-video-content"]});g.G(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.W));this.F=this.g=null;this.N=[];jpa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},F1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},jpa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Wf||a.Wf)&&!a.cB||null!==b.I.get(a.videoId)},G1=function(a,b,c){a.I=!0;
a.C=g.Eq(b,c)},H1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(H1(a,e))}return c},I1=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},lpa=function(a,b){var c=kpa(a,b);
if(!c&&"marker"!=b.type)return null;o0(b,function(e){e=(0,g.x)(this.mL,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new O0(a.ua,b,c);g.G(d,c);return d},mpa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Th(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).dj)break;a.u.element.appendChild(c);d=new y1(c,J1(a),b);break;case "promotion":g.eK(a.player,c,4),d=new z1(c,J1(a),b)}d&&d.Vn();return d},npa=function(a){var b=a.player.getVideoData();
if(b.Fd){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Xc=(0,g.x)(function(f,k,l){I1(this,f,k)||(f=g.yq(l)&&l.responseXML?l.responseXML:null)&&K1(this,f)},a,a.H,b.videoId);
g.bq()&&(e.Xc=L1(a,e.Xc));e.ub={ic_only:"1"};M1(e,d);a.I=!0;g.Eq(b.Fd,e)}}},M1=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Ql&&(a.ub.ic_coll=b.Ql);b.Rl&&(a.ub.ic_xml=b.Rl);b.Us&&(a.ub.ic_track=b.Us)},N1=function(a){var b=new g.W({B:"div"});
g.Th(b.element,!1);var c=new r1(a.player,b.element,J1(a));g.G(c,b);b.g(a.u.element);c.Vn();return c},J1=function(a){if(!a.F){var b=new BZ(a);
g.G(a,b);var c=new g.$m(a);g.G(a,c);a.F=new Uoa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.ua)}return a.F},K1=function(a,b){var c=!1;
opa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=H1(a,d[e]),k=null;try{k=Coa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=mpa(a,k))g.G(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=N1(a),g.G(a,a.g)),"card"==k.type?apa(a.g,k):bpa(a.g,k),c=!0;else if(f=lpa(a,k))g.G(a,f),a.i[k.id]=f}}c&&(mZ(a.player),a.vn());g.Lb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},ppa=function(a,b){var c=!1;
a.g||(a.g=N1(a),g.G(a,a.g));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())c=!0;c&&(mZ(a.player),a.vn())},opa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.$s();
if(b){var c=g.Zs();c&&g.Ls(b,c,[g.Js(a)])}}},qpa=function(a,b,c,d){d?O1(a,b,c):P1(a,b,c)},P1=function(a,b,c){if(b=a.i[b])Q0(b),c&&c.i?(a=(0,g.x)(a.rw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.rw(b)},O1=function(a,b,c){if(b=a.i[b])Q0(b),c&&c.o?(a=(0,g.x)(a.qA,a,b),b.g=new g.M(a,2E3),b.g.start()):a.qA(b)},Q1=function(a,b){var c=a.player.getVideoData();
if(!c.Fl)return!1;var d=X_(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!l1(d))return!1;d=g.lq(d);return d.list||d.p?!1:(d=m1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},kpa=function(a,b){if(rpa(b)){var c=b.o||m0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new H0(b,(0,g.x)(a.O.appendChild,a.O),a.player,a.ua,c)}return null},rpa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in l0)if(a.style==l0[b])return!0;return!1},R1=function(a,b,c,d){a.M(s0(b,d),c,d)},L1=function(a,b){return(0,g.x)(function(){if(!this.da()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.N.push(g.$p(b))}},a)};
g.LJ.prototype.Hi=g.da(14,function(a,b){var c=g.MJ(this).l;c&&c.Hi(a,b)});
g.go.prototype.gq=g.da(0,function(){this.i=this.N.createElement("DIV")});
var Kna=/[^\d]+$/,Lna={cm:1,"in":1,mm:1,pc:1,pt:1},Mna={em:1,ex:1},rZ={},sZ=null;g.y(wZ,g.sf);g.y(xZ,g.Vn);g.h=xZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;tZ(this);this.startTime=a=(0,g.H)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Wd("play");-1==this.g&&this.Wd("resume");this.g=1;var b=g.Ra(this);b in rZ||(rZ[b]=this);uZ();vZ(this,a);return!0};
g.h.stop=function(a){tZ(this);this.g=0;a&&(this.progress=1);yZ(this,this.progress);this.Wd("stop");this.l()};
g.h.pause=function(){1==this.g&&(tZ(this),this.g=-1,this.Wd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Wd("destroy");xZ.Wa.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Mr=function(){this.Wd("animate")};
g.h.Wd=function(a){this.dispatchEvent(new wZ(a,this))};
g.y(zZ,xZ);zZ.prototype.u=g.Ja;zZ.prototype.Mr=function(){this.u();zZ.Wa.Mr.call(this)};
zZ.prototype.l=function(){this.u();zZ.Wa.l.call(this)};
zZ.prototype.o=function(){this.u();zZ.Wa.o.call(this)};
g.y(AZ,zZ);AZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(BZ,g.D);BZ.prototype.ca=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Mr(a,b,c);this.g.push(a);return a};
BZ.prototype.Om=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Wr(a,b,c);this.g.push(a);return a};
BZ.prototype.La=function(a){g.Nr(a);g.eb(this.g,a)};
BZ.prototype.T=function(){g.Nr(this.g);this.g.length=0;g.D.prototype.T.call(this)};g.y(EZ,g.Sf);g.h=EZ.prototype;g.h.Zp=null;g.h.Tj=null;g.h.ga=function(){return this.Tj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.Tj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Mf(this.Tj,a,b,c,d)};
g.h.T=function(){EZ.Wa.T.call(this);var a=this.Tj;if(a)if(g.vf(a))a.me&&g.zf(a.me);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Nf(d[e])&&++b}};g.y(JZ,EZ);JZ.prototype.fill=null;g.y(LZ,EZ);MZ.prototype.Ee=null;MZ.prototype.yd=null;MZ.prototype.Xk=!0;var Una=[2,2,6,6,0];g.h=MZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Td.length=0;delete this.Ee;delete this.yd;delete this.Xk;return this};
g.h.moveTo=function(a,b){0==g.Wa(this.Ta)?this.Td.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Td.push(a,b);this.yd=this.Ee=[a,b];return this};
g.h.Zb=function(a){var b=g.Wa(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Td.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.yd=[c,d]};
g.h.close=function(){var a=g.Wa(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.yd=this.Ee);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Td=this.Td.concat();a.Ee=this.Ee&&this.Ee.concat();a.yd=this.yd&&this.yd.concat();a.Xk=this.Xk;return a};
g.h.transform=function(a){if(!this.Xk)throw Error("Non-simple path");a.transform(this.Td,0,this.Td,0,this.Td.length/2);this.Ee&&a.transform(this.Ee,0,this.Ee,0,1);this.yd&&this.Ee!=this.yd&&a.transform(this.yd,0,this.yd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.y(OZ,JZ);g.y(w_,g.go);w_.prototype.o=null;w_.prototype.Hj=function(){return this.gh?g.Sh(this.ga()):g.Ha(this.width)&&g.Ha(this.height)?new g.wd(this.width,this.height):null};
w_.prototype.resume=function(){};g.y(GZ,KZ);g.y(FZ,KZ);g.y(x_,LZ);x_.prototype.clear=function(){g.Vd(this.ga())};
x_.prototype.setSize=function(a,b){var c=this.ga(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.y(y_,OZ);var B_;g.y(z_,w_);var Xna=0;g.h=z_.prototype;g.h.gq=function(){var a=HZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=HZ(this,"g");this.C=HZ(this,"defs");this.o=new x_(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ga().setAttribute("preserveAspectRatio","none"),this.R?this.SA():this.ga().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.SA=function(){if(this.gh){var a=this.Hj();0==a.width?this.ga().style.visibility="hidden":(this.ga().style.visibility="",this.o.ga().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Rh(this.ga(),a,b)};
g.h.Hj=function(){if(!g.Bh)return this.gh?g.Sh(this.ga()):z_.Wa.Hj.call(this);var a=this.width,b=this.height,c=g.Fa(a)&&-1!=a.indexOf("%"),d=g.Fa(b)&&-1!=b.indexOf("%");if(!this.gh&&(c||d))return null;if(c){var e=this.ga().parentNode;var f=g.Sh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ga().parentNode,f=f||g.Sh(e),b=parseFloat(b)*f.height/100);return new g.wd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.C);this.g={}};
g.h.wj=function(){z_.Wa.wj.call(this);this.R&&this.P.La(Yna(),"tick",this.SA)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.P.dispose();delete this.P;z_.Wa.T.call(this)};g.t(D_,g.sK);g.h=D_.prototype;
g.h.load=function(){g.sK.prototype.load.call(this);if(!F_(g.X(this.player).playerStyle)){var a=g.GB(this.player.getVideoData());if(a)a=C_(a,E_(this)),G_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.x)(this.LI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().qv;c&&(a.ub={ad_tracking:c});if(b=g.FB(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Eq(b,a)}}};
g.h.unload=function(){G_(this,null);this.o&&(this.o.abort(),this.o=null);g.sK.prototype.unload.call(this)};
g.h.wc=function(a,b){if(!F_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=C_(b,"new");G_(this,c);return!0}return null};
g.h.getOptions=function(){return F_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.LI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=C_(c,E_(this)))}G_(this,c)};
g.h.ib=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<S1.length;f++){var k=Math.abs(b.width-S1[f]);if(-1==e||d>=k)e=f,d=k}d=T1[e];this.l&&g.zh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Rh(e.element,Math.round(k.width*a.width),f);g.Hh(e.element,m,n);g.Tn(e.element,spa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Tn(e.element,T1);g.J(e.element,d);(e=g.Fd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zh(e,"height",f+"px")}}}}};
g.h.JE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.UJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(L_(this,this.i.impressionUrls),(a=g.$s())&&this.i.visualElement&&g.Ms(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");L_(this,c.impressionUrls);
(b=g.$s())&&g.Ms(b,c.visualElement);g.X(this.player).rb&&this.player.la("endscreenelementshown",a)}};
g.h.KE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Sn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Sn(b,"ytp-ce-shown");g.X(this.player).rb&&this.player.la("endscreenelementhidden",a)}};
g.h.BL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.Tn(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Fy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Qn(c,"ytp-ce-element");){g.Qn(c,"subscribe-label")&&M_(this,a);if(g.Qn(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.Qn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Rr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.ao?(M_(this,a),this.Zz(),this.player.pauseVideo(),c=g.Dc(I_(this,a.targetUrl)),c=g.Ac(c),g.kL(c,void 0,a.Xb)):(c=this.player.getVideoData().Nb,
c=(0,g.x)(this.rM,this,c,I_(this,a.targetUrl),a.Xb),c=(0,g.x)(this.Zz,this,c),M_(this,a,c))}}};
g.h.rM=function(a,b,c){var d=g.lq(b);a&&d&&(d.v||d.list)?g.MX(this.player.app,d.v,c,d.list,!1,void 0):g.jL(b,c)};
g.h.ar=function(a,b){g.Qn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),L_(this,b.OD),K_(this,b.id,!0))};
g.h.Rr=function(a,b){g.Sn(a.element,"ytp-ce-element-hover");g.Sn(a.element,"ytp-ce-force-expand");K_(this,b.id,!1)};
g.h.Zz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var S1=[346,426,470,506,570,640,853,1280,1920],T1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),spa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ioa={VN:"current",cP:"new"};var koa={CLOSE:"close",gP:"openUrl",UB:"subscribe"},loa={QN:"click",CLOSE:"close",yO:"hidden",GP:"rollOut",QB:"rollOver",RB:"shown"};var noa={lQ:"xx",mQ:"xy",nQ:"yx",oQ:"yy"};g.t(g0,$_);var soa={pB:"anchored",CP:"rect",JP:"shapeless"};var woa={CLOSED:"closed",pP:"playerControlShow",QB:"rollOver",RB:"shown"};k0.prototype.Jb=function(){var a=Eoa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
k0.prototype.showLinkIcon=function(){return m0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var l0={pB:"anchored",sB:"branding",CHANNEL:"channel",UN:"cta",AO:"highlightText",OO:"label",PLAYLIST:"playlist",sP:"popup",NP:"speech",UB:"subscribe",XP:"title",VIDEO:"video",hQ:"website"},Aoa={sB:"branding",HN:"card",bO:"drawer",zO:"highlight",WO:"marker",xP:"promotion",TEXT:"text",jQ:"widget"},Boa={fQ:"video_relative",qP:"player_relative"};t0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Pb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};u0.prototype.ga=function(){return this.u};
u0.prototype.l=function(){};var y0={bevel:1,dropshadow:2};g.t(D0,u0);
D0.prototype.l=function(a,b){var c=q0(a);if(c){var d=d0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=p0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.qh(b0(b,c0(e,new g.nh(e.D,e.F,e.Xi,e.l),b.g))),k=d.clone();c=new g.nh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.g;k=B0(k,c.effects);l=v0(this,k.width,k.height);m=A0(c,k.width,k.height,this.g);
d=new g.nh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.ud(f.x-k.left,f.y-k.top);this.o=17*Z_(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.g;var p=this.g&&n0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new i_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Moa(d,n);var u=this.A(d,e,n,r),z=n.x;n=n.y;var C=d.width,E=d.height,F=d.left;d=d.top;var L=new MZ;L.moveTo(F+e+p,d+p);"t"==r&&(L.Zb(u.start,d+p),L.Zb(z,n),L.Zb(u.end,d+p));L.Zb(F+C-e-p,d+p);NZ(L,e,e,-90);"r"==r&&(L.Zb(F+C-p,u.start),L.Zb(z,n),L.Zb(F+
C-p,u.end));L.Zb(F+C-p,d+E-e-p);NZ(L,e,e,0);"b"==r&&(L.Zb(u.end,d+E-p),L.Zb(z,n),L.Zb(u.start,d+E-p));L.Zb(F+e+p,d+E-p);NZ(L,e,e,90);"l"==r&&(L.Zb(F+p,u.end),L.Zb(z,n),L.Zb(F+p,u.start));L.Zb(F+p,d+e+p);NZ(L,e,e,180);L.close();A_(l,L,f,m);if(m=this.ga())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Hh(m,k.left,k.top),g.Rh(m,k.width,k.height),C0(l,m,c.effects)}}}};
D0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.qd(k-f/2,l+b,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(E0,u0);E0.prototype.l=function(a,b){var c=q0(a);if(c){var d=d0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.g;c=B0(d,e.effects);var f=v0(this,c.width,c.height),k=new i_(!e.l&&this.g?1:e.l,e.bgColor),l=new FZ("#000",0);d=z0(new g.nh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);A_(f,d,k,l);f=this.ga();g.J(f,"annotation-shape");e=e.g;oZ(f,this.g?Math.max(e,.9):e);g.Hh(f,c.left,c.top);g.Rh(f,c.width,c.height)}}};g.t(F0,u0);
F0.prototype.l=function(a,b){var c=q0(a);if(c){var d=d0(c,b);if(!(0>=d.width||0>=d.height)){c=a.g;var e=B0(d,c.effects),f=v0(this,e.width,e.height),k=new g.nh(0,0,d.width,d.height);d=A0(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.g;var n=this.g&&n0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new i_(p,n?m.i:m.borderColor):null;k=z0(k,l,m?m.g/2+1:0);A_(f,k,m,d);if(k=this.ga())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Hh(k,e.left,e.top),g.Rh(k,e.width,e.height),C0(f,k,c.effects)}}};g.t(G0,D0);G0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(H0,g.D);g.h=H0.prototype;g.h.qx=function(){this.F||(this.o&&g.Th(this.o,!0),this.u&&g.Th(this.u,!0),this.l&&(this.l.g=!0,oZ(this.i,M0(this)?1:0),this.l.l(this.g,J0(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Om(g.RJ(this.A),"mouseleave",function(a){this.pn.stop();this.Bg(a)}))};
g.h.Bg=function(){this.F&&(this.N?this.D.start():this.tw(),this.l&&(this.l.g=!1,oZ(this.i,M0(this)?1:0),this.l.l(this.g,J0(this))),this.F=!1,this.H&&(this.aa.La(this.H),this.H=null))};
g.h.tw=function(){this.o&&g.Th(this.o,!1);this.u&&g.Th(this.u,!1)};
g.h.BF=function(a){this.ba=a;this.pn.Rj()};
g.h.qD=function(){var a=this.ba,b=new g.ud(a.clientX,a.clientY),c=g.Lh(this.A.getRootNode()),d=N0(c,this.P);c=(this.u&&pZ(this.u)||this.o&&pZ(this.o))&&N0(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.qx(a):this.Bg(a)};
g.h.show=function(){var a=this.g.g;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=J0(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new E0:"popup"==this.g.style?d=new F0:"anchored"==this.g.style?d=new D0:"speech"==this.g.style&&(d=new G0);d&&(d.l(this.g,c),this.l=d,c=d.ga())&&(g.Th(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Th(this.i,!1);this.g.l&&(this.C=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.g.bgColor),g.be(this.C,this.g.l),this.i.appendChild(this.C));g.Ep(this.i,"annotation_id",this.g.id);this.R(this.i);Noa(this,this.i);if(n0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Jb())c=this.i,d=new g.Mm(X_(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Th(this.u,
!1);this.i.appendChild(this.u)}Ooa(this);n0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=i0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ga()&&(this.l.ga().style.zIndex=a)}g.Th(this.i,!0);oZ(this.i,M0(this)?1:0);L0(this);this.l&&this.l.ga()&&g.Th(this.l.ga(),!0)};
g.h.hide=function(){this.i&&g.Th(this.i,!1);this.l&&this.l.ga()&&g.Th(this.l.ga(),!1);this.I&&(this.aa.La(this.I),this.I=null)};g.t(O0,g.D);g.h=O0.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(P0(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.ox,this),this.i.subscribe("onVideoAreaChange",this.ez,this))};
g.h.destroy=function(){if(this.view){P0(this);var a=this.view,b=a.aa;g.Nr(b.g);b.g.length=0;a.pn.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ga()&&g.Xd(a.l.ga())}Q0(this)};
g.h.ez=function(){L0(this.view)};
g.h.ox=function(){L0(this.view)};$0.prototype.l=function(a,b){var c=g.ge(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
$0.prototype.u=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.Qd)g.Hd("iv-card-sign-in-button",c).click();else{var d=parseInt(Ona(b.target),10);if(null==a.he)a.choices[d].count++,a.he=d;else if(a.he!=d){var e=a.choices[a.he];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.he=d}else e=a.choices[a.he],e.count=Math.max(e.count-1,0),a.he=null;b1(a,c);g.Iq(this.g.videoData.Fd,{Dc:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.XM}});W0(this.g.logger,a.Ya,void 0,
{"link-id":d},a.pd.click,5);(c=g.$s())&&a.rf&&g.Ns(c,a.rf)}};g.t(o1,g.D);g.h=o1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.QD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&kZ(a).subscribe("onEnter",d,this);e&&kZ(a).subscribe("onExit",e,this);g.YJ(this.context.Y,[a])};
g.h.Vn=function(){this.context.i.subscribe("resize",this.Ll,this)};
g.h.ga=function(){return this.Ba};
g.h.Li=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Sa(this.Nm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Sa(function(){this.kt=!1}),this);
this.context.g.ca(a,"touchmove",g.Sa(function(){this.kt=!0}),this)};
g.h.Nm=function(a,b,c,d,e,f,k){if(this.kt)return!1;k&&(k.stopPropagation(),k.preventDefault());$oa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ga())};
g.h.Ll=function(){};g.t(r1,o1);g.h=r1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Sh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Ll=function(){var a=this.isAvailable();g.Th(this.ga(),a);g.K(this.context.Y.getRootNode(),"ytp-iv-drawer-enabled",a);mZ(this.i)};
g.h.destroy=function(){this.i.Hi(!1);this.i.getRootNode().removeChild(this.A);g.Pp(this.I);g.Nr(this.ba);this.Z&&this.Z.dispose();this.C&&this.C.dispose();o1.prototype.destroy.call(this)};
g.h.ZE=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.fA=function(a){if(!g.Qn(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.$s(),c=this.g?this.g.Fb.de:this.H;b&&c&&DZ(b,[c]);this.g=a;t1(this)}pZ(this.ga())&&(2==this.context.Y.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Y.getAdState():void 0):(b=isNaN(void 0)?this.context.Y.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Y.getCurrentTime()),b&&a.Fb.teaserDurationMs&&this.i.Hi(!0,{teaserText:a.Fb.teaserText,durationMs:a.Fb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.N.isActive()&&this.W)&&v1(this,a),this.ka.start(910+a.Fb.teaserDurationMs))}};
g.h.kM=function(a){this.u||(this.g=a,t1(this),v1(this,a),p1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.qC=function(){if(this.u){Y0(this.context.logger,this.R,4,w1(this).pd.close);var a=g.$s();a&&this.P&&g.Ns(a,this.P);q1(this)}};
g.h.AC=function(){g.K(this.A,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.jE=function(){var a=g.$s(),b=w1(this);b=b?b.de:this.H;a&&b&&CZ(a,[b])};
g.h.iE=function(){var a=g.$s(),b=w1(this);b=b?b.de:this.H;a&&b&&DZ(a,[b])};
g.h.mE=function(){var a=w1(this);Z0(this.context.logger,8,a.Ya,a.pd.yM);var b=g.$s();b&&a&&CZ(b,[a.af,a.de])};
g.h.lE=function(){var a=g.$s(),b=w1(this);a&&b&&DZ(a,[b.af])};
g.h.kE=function(a){var b=w1(this),c=g.$s();this.g?a?(a=this.context.logger,Z0(a,9,b.Ya,b.pd.Ns),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.af&&g.Ns(c,b.af)):(a=this.context.logger,Z0(a,12,b.Ya,b.pd.Ns),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.de&&g.Ns(c,b.de)):(a=this.context.logger,Y0(a,this.R,12,b.pd.Ns),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Ns(c,this.H))};g.t(x1,o1);x1.prototype.Vn=function(){o1.prototype.Vn.call(this);hpa(this)};
x1.prototype.show=function(){o1.prototype.show.call(this);var a=g.$s(),b=this.annotation.data;a&&b&&(b=b.session_data)&&CZ(a,[g.Js(b.itct)])};
x1.prototype.hide=function(){o1.prototype.hide.call(this);var a=g.$s(),b=this.annotation.data;a&&b&&(b=b.session_data)&&DZ(a,[g.Js(b.itct)])};g.t(y1,x1);g.h=y1.prototype;g.h.sM=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Sh(a);this.g||(g.Qh(a,e.width),g.Qh(b,e.width));g.zh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.zh(c,"right","1px");this.o=!0;g.Th(a,!0);this.A=new g.M(function(){g.J(this.ga(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.MD=function(a,b){g.Sn(this.ga(),"iv-branding-active");this.C=new g.M((0,g.x)(function(){g.Th(a,!1);this.g||g.Qh(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){x1.prototype.show.call(this);if(!this.D){g.J(this.ga(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Th(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ga().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.be(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.GV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Y),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Th(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.zh(d,"right",this.u+"px");this.ga().appendChild(d);var e=this.annotation.Jb();e&&this.Li(this.i,e,this.annotation.id,a.session_data,
this.annotation.Ya);this.l=new g.M(g.Sa(this.MD,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ga(),"mouseover",(0,g.x)(this.sM,this,c,d,b,a.image_height));this.context.g.ca(this.ga(),"mouseout",(0,g.x)(this.l.start,this.l,void 0));this.D=!0}V0(this.context.logger,this.annotation.Ya);g.Th(this.ga(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=nZ(a).width;c=g.Ha(void 0)?void 0:b;g.Hh(a,c);f=new AZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Qna);g.G(this,f);this.context.l.ca(f,
"begin",g.Sa(g.Th,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(x1.prototype.hide.call(this),g.Th(this.ga(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);x1.prototype.destroy.call(this)};g.t(z1,x1);g.h=z1.prototype;g.h.show=function(){this.isActive||(x1.prototype.show.call(this),this.H||(ipa(this),this.H=!0),g.Th(this.ga(),!0),this.annotation&&this.annotation.Ya&&V0(this.context.logger,this.annotation.Ya),g.Gg(function(){g.Sn(this.ga(),"iv-promo-inactive")},100,this),this.ga().removeAttribute("aria-hidden"),this.isActive=!0,C1(this),B1(this),D1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ga(),"iv-promo-inactive"),this.isActive=!1,this.ga().setAttribute("aria-hidden",!0))};
g.h.Nm=function(a,b,c,d,e,f,k){return this.u?!1:x1.prototype.Nm.call(this,a,b,c,d,e,f,k)};
g.h.iq=function(a,b){b.stopPropagation();B1(this);D1(this,a);this.g.focus()};
g.h.sD=function(a){this.F=!0;this.iq(500,a)};
g.h.rD=function(){this.F=!1;A1(this)};
g.h.jD=function(a){a.stopPropagation();this.hide();X0(this.context.logger,this.annotation.Ya)};
g.h.kD=function(a){a.stopPropagation();C1(this);this.u=!0;g.J(this.ga(),"iv-promo-collapsed-no-delay");this.A.start();X0(this.context.logger,this.annotation.Ya)};
g.h.destroy=function(){this.A.dispose();x1.prototype.destroy.call(this)};g.t(E1,g.sK);g.h=E1.prototype;g.h.wc=function(a,b){if(!F1(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Un(b);c&&K1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(u1(this.g,b),mZ(this.player)),!0}return null};
g.h.getOptions=function(){return F1(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.vn=function(){if(this.o){var a=g.RJ(this.player).getVideoContentRect(!0);g.Rh(this.o.element,a.width,a.height);g.Hh(this.o.element,a.left,a.top)}if(this.g){var b=g.WJ(this.player);a=this.g;b=b.width;g.K(a.A,"iv-drawer-small",426>=b);g.K(a.A,"iv-drawer-big",1280<=b)}};
g.h.YJ=function(a){this.fc(a.state);g.U(a.state,2)&&(this.ud()&&this.De()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hi(!1))};
g.h.load=function(){g.sK.prototype.load.call(this);this.fc(g.QJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.MI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.bq()&&(c=L1(this,c));c={format:"XML",Xc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&M1(c,b);b=b&&(b.Rl||b.Ql);if(!a.El||b)a.Fd?G1(this,a.Fd,c):(this.l=(0,g.x)(this.IE,this,c),this.player.addEventListener("videodatachange",this.l));g.eK(this.player,this.o.element,4);this.vn();(a=a.Qa&&a.Qa.cards&&a.Qa.cards.cardCollectionRenderer||null)&&ppa(this,a)};
g.h.fc=function(a){a=!a.isCued()&&!g.U(a,1024);g.KC(this.u,a);g.KC(this.o,a)};
g.h.IE=function(a){var b=this.player.getVideoData();b.Fd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),G1(this,b.Fd,a))};
g.h.unload=function(){Soa(this.D);g.aK(this.player,"annotations_module");g.Lb(this.i,function(a){a.destroy()});
g.Lb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,mZ(this.player));this.I=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.P={};this.u.hide();g.sK.prototype.unload.call(this);g.JC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.MI=function(a,b,c){this.C=null;if(!I1(this,b,a)&&(a=g.yq(c)&&c.responseXML?c.responseXML:null)){K1(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.l,f.visible=!0);b=new g.QD(c,e,f);a.push(b)}}g.YJ(this.player,a)}};
g.h.dz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?npa(this):this.load())};
g.h.FE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,O1(this,a),V0(this.D,b.Ya))};
g.h.GE=function(a){P1(this,a.getId())};
g.h.rw=function(a){a&&(a.hide(),R1(this,"shown",!1,a.annotation.id),this.Zl(a.annotation,"hidden"))};
g.h.qA=function(a){a&&(a.show(),R1(this,"shown",!0,a.annotation.id),this.Zl(a.annotation,"shown"))};
g.h.mL=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;o0(d.annotation,function(f){e=e||f.value});
qpa(this,a,b,e)}};
g.h.RH=function(a){if(a&&a.id){var b=a.Jb();if(b){var c=X_(b);if(c){var d=(0,g.x)(this.Zl,this,a,"click");if("new"==n1(c,b.target)||Q1(this,b))d(),d=null;W0(this.D,a.Ya,d)}}}};
g.h.Zl=function(a,b){Doa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!Q1(this,c.url))){e=m1(c.url);var f=Xoa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=J1(this).Y,g.MX(d.app,e,void 0,void 0,void 0,void 0),f&&J1(this).Y.ac()&&J1(this).Y.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=X_(c.url))?(f=k1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Sa(Yoa,e.pageId,e.gc),d=new g.Mm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,d&&
(this.player.pauseVideo(),c=n1(d,c.url.target),e=a.itct,"ei"in g.lq(d)&&(d=g.hh(d,"ei")),g.kL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.VI=function(){R1(this,"playerControlShow",!1)};
g.h.OK=function(){R1(this,"playerControlShow",!0)};
g.h.HE=function(a){R1(this,"rollOver",!0,a.id)};
g.h.Bg=function(a){R1(this,"rollOver",!1,a.id)};
g.h.uI=function(a){a&&a.id&&(this.i[a.id].l=!0,P1(this,a.id),X0(this.D,a.Ya),this.Zl(a,"close"),R1(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.De=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?p1(this.g,c,b):p1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):q1(this.g))};
g.h.Hi=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.dz,this);g.Sn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.N,b=0,c=a.length;b<c;b++)g.cq(a[b]);this.N.length=0;g.sK.prototype.T.call(this)};g.OU.annotations_module=E1;g.OU.creatorendscreen=D_;})(_yt_player);
