(function(g){var window=this;var U1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.sz(a),kind:a.o,name:a.u,id:a.H,is_servable:a.C,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},V1=function(a){return a.g?a.g.languageCode:a.i},tpa=function(a,b){var c=new g.rz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},W1=function(a){if(!upa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(vpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},wpa=function(){this.i=[];
this.g=[]},X1=function(a,b){return b?a.g.concat(a.i):a.g},Y1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Ya(c,(0,g.x)(b.dr,b))||c.push(b);break;default:c=a.g,g.Ya(c,(0,g.x)(b.dr,b))||c.push(b)}},Z1=function(){g.D.call(this);
this.i=new wpa;this.u=[]},$1=function(a,b,c){Z1.call(this,a);
this.g=null;this.u=b.Du;this.l=c},a2=function(){this.Ta=[]},b2=function(a,b,c,d,e,f){g.D.call(this);
this.I=a;this.o=b;this.A=new a2;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.C=e||!1;this.H=new g.M(this.Pw,1E3,this);g.G(this,this.H);this.u=new g.us(this);g.G(this,this.u);g.Q(g.X(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.yx):this.u.K(b,"seekcomplete",this.MF);this.yx(b.getCurrentTime());this.Pw()},c2=function(a,b){b-=a.o.Ib();
var c=a.g;a.g=g.Wa(a.D.yf(b).g);c!=a.g&&a.P&&a.P()},d2=function(a,b){var c=g.Av(b,a.I,{}).Jb(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.i=g.dr(c,d,3,100).then((0,g.x)(a.uK,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.pb(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.db(c.Ta,e),g.db(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.lb(c.Ta,e,0,d),g.lb(c.Ta,e+1,0,d)))},e2=function(a,b){Z1.call(this,g.X(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.cz(g.X(this.C))&&!this.g.i},f2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.HU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.rz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},xpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},g2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.HU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},h2=function(a,b,c,d,e){Z1.call(this,e||null);
c=c||g.lq(a).hl||"";c=c.split("_").join("-");this.o=g.nq(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},i2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.QD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},j2=function(a,b,c,d,e){g.QD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},l2=function(a){a=void 0===a?{}:a;
var b="_"+k2++;return new j2(0,0x8000000000000,0,b,a)},n2=function(a,b,c,d,e,f){var k={};
g.Ta(k,b);g.Ta(k,a.params);g.Ta(k,c);var l={};g.Ta(l,b.wb);a.params.wb&&g.Ta(l,a.params.wb);g.Ta(l,c.wb);k.wb=l;g.W.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.ze?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{B:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.O=!1;this.o=a;this.W=this.R=null;this.Oa=e;this.Ka=f;this.D=null;this.X=.96*e;this.wa=.96*f;this.l=k;this.Ia=c;this.A=this.i["captions-text"];this.Ba=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ka=this.Z*m2(l);a=new g.As(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.LF,this);a.subscribe("dragmove",this.KF,this);a.subscribe("dragend",this.JF,this);this.va=this.ma=0;b="";this.l.windowOpacity&&(a=W1(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":ypa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.ze||3==this.o.params.ze)b=this.element,c="vertical-rl",1==this.l.BA&&(c="vertical-lr"),g.Md&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.zh(b,"-o-writing-mode",c),g.zh(b,"-webkit-writing-mode",c),g.zh(b,"writing-mode",c),g.zh(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.o.params.ze&&(g.zh(b,"text-orientation",""),g.zh(b,"transform","rotate(180deg)"));g.zh(this.element,a);switch(this.l.Vf){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},m2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},o2=function(a,b){var c={},d=b.background?b.background:a.l.wb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.wb.backgroundOpacity;d=W1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*m2(b)+"px";d=1;e=b.color||a.l.wb.color;if(b.color||null!=b.textOpacity)e=W1(e),d=null==b.textOpacity?a.l.wb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Lu&&(k=e=b.Lu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Mq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.wb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Qe&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.LD&&(c.visibility="hidden");1==b.ND&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.ez||g.fz,3==a.o.params.ze?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.ye||2==b.ye||3==b.ye||4==b.ye||5==b.ye)if(g.ez)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.ye){case 4:case 3:c["text-emphasis-position"]="under right";c["webkit-text-emphasis-position"]="under right";break;
case 5:case 2:c["text-emphasis-position"]="over left",c["webkit-text-emphasis-position"]="over left"}return c},p2=function(a){a.D=g.Sd("SPAN");
g.zh(a.D,{display:"block"});g.J(a.D,"caption-visual-line");a.A.appendChild(a.D)},q2=function(a,b){var c=g.Sd("SPAN");
g.zh(c,{display:"inline-block","white-space":"pre-wrap"});g.zh(c,o2(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.zh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.zh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},r2=function(a,b,c){a.O=a.O||!!c;
var d={};g.Ta(d,a.l.wb);g.Ta(d,c||b.g);g.Ta(d,a.Ia.wb);(c=!a.D)&&p2(a);for(var e=a.R&&a.W&&g.bc(d,a.W)?a.R:q2(a,d),f=g.Fa(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(p2(a),e=q2(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Td(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.ez||!g.Dh(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.Dh(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Od?g.zh(e,m,"1em"):
g.zh(e,m,"0.5em")))}a.W=d;a.R=e;a.C.push(b)},s2=function(){},u2=function(){this.o=this.i=this.mode=this.l=0;
this.u=new t2(this);this.A=new t2(this);this.g=[];this.clear()},zpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Il:a,
Jl:b,result:0};a=v2[a];b=v2[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Il:a,Jl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Il:a,Jl:b,result:2};return{Il:a,Jl:b,result:3}},Apa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,w2(a.u,b,c,d))},Bpa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Apa(a,d.Fu,d.Gu,b):1==d.type&&a.l&496&&w2(a.A,d.Fu,d.Gu,b)}a.g.length=0},x2=function(){this.g=0},y2=function(){this.i=this.l=this.g=0},z2=function(){this.timestamp=this.Sd=0},A2=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new z2}this.g=this.i=this.row=0;this.style=new x2;this.u=a;this.o=0},B2=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Sd){0==c&&(c=m,d=p);n=String.fromCharCode(r.Sd);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Sd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Sd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Gpa=function(a,b){switch(a){case 0:return Cpa[(b&127)-32];
case 1:return Dpa[b&15];case 2:return Epa[b&31];case 3:return Fpa[b&31]}return 0},C2=function(a){return a.l[a.row][a.i]},D2=function(a,b,c){2<=b&&1<a.i&&(--a.i,C2(a).Sd=0);
var d=C2(a);d.timestamp=a.u.i+0;d.Sd=Gpa(b,c);32>a.i&&a.i++},E2=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].gg(a.l[c+e][f])},F2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},G2=function(a){a.row=0<a.g?a.g:1;
a.i=1;F2(a,0,15)},H2=function(a){this.o=a;
this.u=0;this.style=new x2;this.A=new A2(a);this.C=new A2(a);this.D=new A2(a);this.i=this.A;this.l=this.C;this.g=this.i},I2=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:B2(d,c),G2(a.i),G2(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(B2(d,c),F2(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},J2=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},K2=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},t2=function(a){this.i=a;
this.g=new y2;this.u=0;this.l=new H2(a);this.A=new H2(a);this.o=this.l},w2=function(a,b,c,d){a.g.update();
b=zpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Il;c=b.Jl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&D2(a,0,b),c&96&&D2(a,0,c),0!=b&&0!=c&&3==a.style.g&&B2(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;E2(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));F2(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:D2(b.g,0,32);break a;case 48:57==c?(d=b.g,C2(d).Sd=0,32>d.i&&d.i++):D2(b.g,1,c&15)}break;case 2:c&32&&D2(b.g,2,c&31);break;case 3:c&32&&D2(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:J2(b);break;case 33:d=
b.g;1<d.i&&(--d.i,C2(d).Sd=0);break;case 36:d=b.g;b=C2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:I2(b,2,d);break;case 38:I2(b,3,d);break;case 39:I2(b,4,d);break;case 40:D2(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);G2(d);K2(b);break;case 43:K2(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:B2(a,d)}F2(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;B2(a,d);E2(a,b,b+1,a.g-1);F2(a,a.row,1)}break;case 46:F2(b.l,0,15);break;case 47:B2(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,J2(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},L2=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Yc){var n=f[1],p=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");r.getAttribute("t");f=g.Sd("RUBY");l=l.textContent;var u=g.Sd("SPAN");u.innerText=l;f.appendChild(u);n.getAttribute("p");u=g.Sd("RP");l=n.textContent;u.innerText=l;f.appendChild(u);k=k[p.getAttribute("p")];l=p.textContent;p=g.Sd("RT");p.innerText=l;f.appendChild(p);l=k.Yc;if(10==l||11==l||12==l||13==l||14==l)if(g.zh(p,"text-emphasis","filled circle"),g.zh(p,"webkit-text-emphasis","filled circle"),
k.Yc==k.Yc==11||13==k.Yc)g.zh(p,"webkit-text-emphasis-position","under left"),g.zh(p,"text-emphasis-position","under left");if(4==k.Yc||7==k.Yc||12==k.Yc||14==k.Yc)g.zh(f,"ruby-position","over"),g.zh(f,"-webkit-ruby-position","before");else if(5==k.Yc||6==k.Yc||11==k.Yc||13==k.Yc)g.zh(f,"ruby-position","under"),g.zh(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Sd("RP");r.innerText=l;f.appendChild(r);return new i2(a,b,e,c,f,d,m)}switch(m.Yc){case 9:case 10:m.ye=1;break;
case 11:m.ye=2;break;case 12:m.ye=3;break;case 13:m.ye=4;break;case 14:m.ye=5}return new i2(a,b,e,c,l.textContent||"",d,m)},M2=function(){g.D.apply(this,arguments)},N2=function(a){M2.call(this);
this.l={};this.F={};this.H={};this.u="_"+k2++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},O2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},P2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Q2=function(a,b){var c=O2(a,b);
return void 0!=c?c:null},S2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return R2.test(c),c},T2=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.H[d]:a.A);d=Q2(b,"mh");null!=d&&(c.Wq=d);d=Q2(b,"ju");null!=d&&(c.textAlign=d);d=Q2(b,"pd");null!=d&&(c.ze=d);d=Q2(b,"sd");null!=d&&(c.BA=d);d=S2(b,"wfc");null!=d&&(c.windowColor=d);d=O2(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},U2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.F[d]);d=Q2(b,"ap");null!=d&&(c.Vf=d);d=O2(b,"cc");null!=d&&(c.Ul=d);d=O2(b,"ah");null!=d&&(c.Re=d);d=O2(b,"rc");null!=d&&(c.Ok=d);d=O2(b,"av");null!=d&&(c.Hg=d);return c},V2=function(a,b,c,d){var e={};
g.Ta(e,U2(a,b));g.Ta(e,T2(a,b));d?g.bc(e,a.A)?(d=a.u,e=a.A):d="_"+k2++:d=b.getAttribute("id")||"_"+k2++;a=O2(b,"t")+c;b=O2(b,"d")||0x8000000000000;if(2==e.ze||3==e.ze)c=e.Ok,e.Ok=e.Ul,e.Ul=c;return new j2(a,b,0,d,e)},W2=function(a,b,c,d,e,f,k){n2.call(this,a,b,c,d,e,f,k);
this.type=1},X2=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},Y2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},Z2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},$2=function(a,b){M2.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new u2;this.g.l=1<<this.track},b3=function(a){if(g.Fa(a))return!1;
a=new X2(a,8,0);return a3(a)},a3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=Z2(a))return!1;
a.version=Y2(a);if(1<a.version)return!1;Y2(a);Y2(a);Y2(a);return!0},c3=function(a,b,c,d,e,f,k){n2.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.fa=0;this.N=NaN;this.xa=0;this.Ea=null;this.ea=new g.M(this.zK,433,this);g.G(this,this.ea)},Hpa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},Ipa=function(a){if(isNaN(a.N)){var b=a.l.Ul;
if(b){var c=g.Sd("SPAN");g.be(c,"\u2013".repeat(b));g.zh(c,o2(a,a.l.wb));a.A.appendChild(c);a.N=c.offsetWidth;a.A.removeChild(c)}else a.N=0}return a.N},Jpa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.BA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},d3=function(a){a.F=[].concat(g.fa(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Ok,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(Ipa(a),a.xa,Hpa(a,a.A))},Kpa=function(a,b){d3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.ao(a.ea));g.zh(a.A,"transform",Jpa(a,c));a.fa=c}d3(a)},e3=function(){M2.call(this)},f3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Qe=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new i2(b,c,d,e.id,p.nodeValue,f||0<n,g.Yb(l)?void 0:l);m.push(p);var r=e;g.G(r,p);r.g.push(p)}else r={},g.Ta(r,l),f3(a,b,c,d,e,!0,p,r,m)}},g3=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},h3=function(a,b,c,d){d=Object.assign({Wq:0},d);
return new j2(a,b,c,"_"+k2++,d)},i3=function(a){g.D.call(this);
this.i=a;this.g=null},l3=function(a){g.sK.call(this,a);
this.u=g.X(a);this.l=a.getVideoData();this.wa=g.RJ(a);this.I=a;var b=null,c=g.Ro("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Bo(c));this.ba=b;this.o={wb:{}};this.A={wb:{}};this.H=[];this.N={};this.W={};this.P=!1;this.ma=g.IU(this.l,this.I);this.xa=!!this.l.captionTracks.length;this.Ba=!!this.l.nj;this.ka="3"==this.u.l;b=a.app.u;c=!(!b||!b.al());this.va=!(!b||!b.Ah());this.C=this.ka&&c&&!this.ma;this.R=!this.C&&this.ka&&this.va&&this.ma;this.i=this.D=this.F=this.O=this.ea=null;this.Z=
new i3(this.u);g.G(this,this.Z);c=b=this.g=null;this.C||(b=new g.Yn(this.QA,void 0,this),g.G(this,b),c=new g.M(this.YL,2E3,this),g.G(this,c));this.X=b;this.fa=c;this.aa=new g.us(this);g.G(this,this.aa);this.C||this.aa.K(a,"resize",this.Zs);this.aa.K(a,"onPlaybackAudioChange",this.bI);this.aa.K(a,g.TD("captions"),this.RE,this);this.aa.K(a,"crx_captions",this.SE,this);j3(this,k3(this,"display-settings")||{})},m3=function(a){if(1==a.u.cg||1==a.l.cg||"alwayson"==g.uB(a.l,"yt:cc"))return!0;
if(2==a.u.cg){var b=k3(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().kp;return"ON"==c||"on"==g.uB(a.l,"yt:cc")},n3=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.gm||"FORCED_ON"==c.kp},p3=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ba?!1:a.xa?!1:!0);c=X1(a.i.i,c);for(var d=[a.l.ag,a.u.ag,g.uB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(V1(c[f])==d[e])return c[f];return a.D&&a.D.Cp?a.D.Cp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||o3(a)}return null},o3=function(a){return a.D&&a.D.gm},q3=function(a){var b=o3(a);
return!!b&&a.g==b},r3=function(a,b){for(var c=a.I.app.u.ga().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},t3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&s3(a,"module-enabled",!!b));a.g=b;n3(a)&&(a.g=o3(a));a.load()},Lpa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Wq?b.params.Wq:1<b.g.length?1:0){case 1:return new W2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new c3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new n2(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},j3=function(a,b,c){var d=u3.wb;
a.o={};g.Ta(a.o,u3);a.o.wb={};g.Ta(a.o.wb,d);a.A={wb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;R2.test(f);e.wb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;R2.test(f);e.wb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||u3.windowColor;R2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.wb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.wb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Qe?3:d.bold?1:d.Qe?2:0);f=f.wb;switch(e){case 1:f.bold=!0;delete f.Qe;break;case 2:delete f.bold;f.Qe=!0;break;case 3:f.bold=!0;f.Qe=!0;break;default:delete f.bold,delete f.Qe}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.wb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=u3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.wb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.wb.fontFamily=f;a.loaded&&a.Zs();c&&s3(a,"display-settings",b)},w3=function(a,b){if(b&&!a.F){var c=l2({ze:0,
lang:"es"});a.F=[c,new i2(c.start,c.end-c.start,0,c.id,"Los subt\u00edtulos tendr\u00e1n este aspecto")];g.YJ(a.player,a.F)}else!b&&a.F&&(v3(a,a.F),a.F=null)},v3=function(a,b){g.$J(a.player,b);
(0,g.A)(b,function(c){g.eb(this.H,c)},a);
a.X.Pj()},k3=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},s3=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.cC.prototype.pj=g.da(13,function(){for(var a=g.Fd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Xd(a[b])});
g.yW.prototype.pj=g.da(12,function(){this.g.pj()});
g.cC.prototype.al=g.da(11,function(){return!!this.g.textTracks});
g.yW.prototype.al=g.da(10,function(){return this.g.al()});
g.cC.prototype.ij=g.da(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.yW.prototype.ij=g.da(8,function(a){this.g.ij(a)});
g.UB.prototype.Ah=g.da(7,function(){});
g.cC.prototype.Ah=g.da(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.yW.prototype.Ah=g.da(5,function(){return this.g.Ah()});
g.rz.prototype.dr=g.da(3,function(a){return a?this.toString()==a.toString():!1});
g.qt.prototype.rm=g.da(2,function(a){return(a=this.kg(a))?a.i:0});
g.kw.prototype.rm=g.da(1,function(){return 0});
var Mpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,vpa=/#(.)(.)(.)/,upa=/^#(?:[0-9a-f]{3}){1,2}$/i,R2=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(Z1,g.D);Z1.prototype.wz=function(){return!1};
Z1.prototype.T=function(){this.Ig();g.D.prototype.T.call(this)};
g.t($1,Z1);$1.prototype.Tq=function(a,b,c){b=this.Lj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Ig();this.g=g.Eq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
$1.prototype.Uq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())Y1(this.i,c.value);a()};
$1.prototype.Lj=function(a,b){var c=a.Jb(),d={fmt:b};a.g&&(d.tlang=V1(a));return g.nq(c,d)};
$1.prototype.Ig=function(){this.g&&this.g.abort()};
a2.prototype.contains=function(a){a=g.pb(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
a2.prototype.length=function(){return this.Ta.length/2};
g.t(b2,g.D);g.h=b2.prototype;g.h.T=function(){g.D.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.yx=function(a){var b=this;if(this.D.gi())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Eb()&&(b.reset(),b.g=null,c2(b,b.o.getCurrentTime()),b.u.La(c))});
else c2(this,a)};
g.h.MF=function(){c2(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new a2;this.i&&(this.i.cancel(),this.i=null)};
g.h.Pw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Jf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.pi(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||d2(this,a),this.g=g.Wa(a.g)));this.H.start()};
g.h.uK=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.rw(a);c?(a=g.Av(this.l,this.I,{}),b=this.l,g.vv(b.i,a,c),b.requestId=a.get("req_id"),d2(this,this.l)):(b||null===this.F||(this.C?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.Ib())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.Ib()))),this.i=this.l=null)};
g.t(e2,Z1);g.h=e2.prototype;g.h.Tq=function(a,b,c){this.Ig();b=xpa(this,a.getId());b||(b=a.i,b=this.g.i?g2(this,b,"386"):g2(this,b));if(b){var d=1E3*(b.index.rm(b.index.oe())-b.index.Hc(b.index.oe()));this.l=new b2(new g.Su,this.C,b,function(e,f){c(e,a,f,d)},this.A||g.Mu(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.wz=function(){var a=this.o;this.o=!1;return a};
g.h.Uq=function(a){var b;this.A?b=[new g.rz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.rz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?f2(this,"386"):f2(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())Y1(this.i,c.value);a()};
g.h.Ig=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Lj=function(){return""};
g.t(h2,Z1);h2.prototype.Tq=function(a,b,c){b=this.Lj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Ig();this.g=g.Eq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
h2.prototype.Uq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.nq(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
Y1(this.i,new g.rz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Ig();this.g=g.Eq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
h2.prototype.Lj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=V1(a));return c=g.nq(c,d)};
h2.prototype.Ig=function(){this.g&&this.g.abort()};var ypa=["left","right","center","justify"];var u3={windowColor:"#080808",windowOpacity:0,textAlign:2,Vf:7,Re:50,Hg:100,wb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(i2,g.QD);i2.prototype.toString=function(){return g.QD.prototype.toString.call(this)};g.t(j2,g.QD);j2.prototype.toString=function(){return g.QD.prototype.toString.call(this)};
var k2=0;g.t(n2,g.W);g.h=n2.prototype;g.h.LF=function(a,b){var c=g.Ph(this.element,this.element.parentElement);this.ma=a-c.x;this.va=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.KF=function(a,b){var c=g.Sh(this.element),d=a-this.ma-.02*this.Oa,e=b-this.va-.02*this.Ka,f=(d+c.width/2)/this.X*3;f=Math.floor(g.qd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.qd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.qd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.qd(c,0,1);this.o.params.Vf=l;this.o.params.Hg=c;this.o.params.Re=d;this.l.Vf=l;this.l.Hg=c;this.l.Re=d;this.Tz()};
g.h.JF=function(){g.Sn(this.element,"ytp-dragging")};
g.h.Tz=function(){this.zh(this.C)};
g.h.zh=function(a){var b=Math.min(this.Nv(),this.X),c=this.Mv(),d="";3==this.o.params.ze&&(d="rotate(180deg)");g.zh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Wo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Re+2;d=this.l.Vf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Hg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.zh(this.element,a)};
g.h.Wo=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.O||this.C.length>b)b=0,this.O=!1,this.C=[],this.D=this.W=this.R=null,g.Vd(this.A);for(;b<a.length;b++)r2(this,a[b])};
g.h.Nv=function(){return 0};
g.h.Mv=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};s2.prototype.u=function(){};u2.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
u2.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var v2=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];x2.prototype.set=function(a){this.g=a};
x2.prototype.get=function(){return this.g};
y2.prototype.clear=function(){this.g=0};
y2.prototype.update=function(){this.g=2==this.g?1:0};
y2.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
z2.prototype.gg=function(a){this.Sd=a.Sd;this.timestamp=a.timestamp};
z2.prototype.reset=function(){this.timestamp=this.Sd=0};
A2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
A2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Sd?a+"_":a+String.fromCharCode(d.Sd)}a+="\n"}return a};
A2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Cpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Dpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Epa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Fpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];H2.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
t2.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(M2,g.D);M2.prototype.reset=function(){};g.t(N2,M2);N2.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
N2.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Ta(l,this.l[m]);m=P2(c,"b");null!=m&&(l.bold=
m);m=P2(c,"i");null!=m&&(l.Qe=m);m=P2(c,"u");null!=m&&(l.underline=m);m=Q2(c,"et");null!=m&&(l.charEdgeStyle=m);m=Q2(c,"of");null!=m&&(l.offset=m);m=S2(c,"bc");null!=m&&(l.background=m);m=S2(c,"ec");null!=m&&(l.Lu=m);m=S2(c,"fc");null!=m&&(l.color=m);m=Q2(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=O2(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=O2(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=O2(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=Q2(c,"rb");null!=m&&10!=m&&(l.Yc=10<m?m-1:m);m=Q2(c,
"hg");null!=m&&(l.ND=m);c=Q2(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.ye=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=T2(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=U2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=V2(this,d,e,!1);g.G(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!P2(d,"a");n=(O2(d,"t")||0)+n;var p=O2(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],z=[].concat(g.fa(d.childNodes));z.length&&(this.C=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var E=z[C];0<C&&(m=!0);var F=void 0;1==E.nodeType&&(F=E);if(F&&"s"==F.tagName)if((E=this.l[F.getAttribute("p")])&&E.Yc)1==E.Yc?(F=L2(n,p,l,m,r,z.slice(C,
C+4),this.l),C+=3):F=L2(n,p,l,m,r,[F],this.l);else{var L=F;F=n;E=p;var aa=l,qa=m,xa=r,cb=L.textContent?L.textContent:"",te=this.l[L.getAttribute("p")];L=O2(L,"t")||0;F=new i2(F+L,E-L,xa,aa,cb,qa,te)}else F=new i2(n,p,r,l,E.textContent||"",m,u);k.push(F);this.i=F}if(0<k.length)for(k[0].windowId==this.u&&(this.g=V2(this,d,e,!0),g.G(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.G(l,k),l.g.push(k),c.push(k)}e=c}else e=[];return e};g.t(W2,n2);W2.prototype.Wo=function(a){var b=this.o.g;n2.prototype.Wo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Ta(d,c.g);g.Ta(d,Npa);var e=c.g;var f=d}r2(this,c,d)}};
var Npa={LD:!0};g.t(X2,s2);X2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+k2++;c=c/1E3-this.C;d=d/1E3-this.C;a=new j2(c,d-c,5,f,{textAlign:0,Vf:0,Re:2.5*b,Hg:5.33*a});e=new i2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t($2,M2);$2.prototype.o=function(a){a=new X2(a,a.byteLength,this.i);if(a3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=Z2(a)*(1E3/45):1==a.version&&(a.o=4294967296*Z2(a)+Z2(a)),a.A=Y2(a);0<a.A;a.A--){var b=Y2(a),c=Y2(a),d=Y2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Fu:c,Gu:d,order:b.g.length}))}Bpa(this.g,a);return a.l}return[]};
$2.prototype.reset=function(){this.g.clear()};g.t(c3,n2);g.h=c3.prototype;g.h.Tz=function(){g.bo(this.ea)};
g.h.zK=function(){g.Sn(this.element,"ytp-rollup-mode");this.zh(this.Ea,!0)};
g.h.Mv=function(){return this.u?this.I:this.H};
g.h.Nv=function(){return this.u?this.H:this.I};
g.h.zh=function(a,b){this.Ea=a;if(this.o.params.Ok){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.xa=this.I;this.H=this.I=0;n2.prototype.zh.call(this,a);Kpa(this,b);n2.prototype.zh.call(this,a)}else n2.prototype.zh.call(this,a)};g.t(e3,M2);
e3.prototype.o=function(a,b){for(var c=[],d=a.split(Opa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Ppa.test(f)){var l=x3.exec(f);if(l&&4<=l.length){var m=g3(l[1]),n=g3(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.q(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(z=E[0],l.Hg=Number.parseInt(z,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
r=E[0];l.Re=Number.parseInt(r,10);2==E.length&&(p=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Hg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Re=0;break;case 1:l.Re=100;break;default:l.Re=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Vf=0>r||8<r?7:r;p=l;f=f.substring(x3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=h3(m,n,5,r),n=new i2(m,n,5,k.id,p,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),g.G(k,n),k.g.push(n);else for(u=p.split(Qpa),1==u.length?(p=5,r=h3(m,n,p,r)):(z=p=6,r=Object.assign({Ul:32},r),r=new j2(m,n,z,"_"+k2++,r)),c.push(r),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(E=g.Un("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(C))):F=E.firstChild,f3(this,z,n-(z-m),p,r,0<l,F,f,c)):z=g3(C)+k}x3.lastIndex=0}}return c};
var Ppa=/^NOTE/,Opa=/(?:\r\n|\r|\n){2,}/,x3=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Qpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(i3,g.D);i3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
i3.prototype.reset=function(){this.g&&this.g.reset()};
i3.prototype.T=function(){this.clear();g.D.prototype.T.call(this)};g.t(l3,g.sK);g.h=l3.prototype;g.h.T=function(){if(this.C||this.R){var a=this.I.app.u;a&&a.pj()}else w3(this,!1);g.sK.prototype.T.call(this)};
g.h.Tk=function(){return this.ka?this.C||this.R:n3(this)?!0:m3(this)};
g.h.load=function(){g.sK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Z.clear(),this.C?r3(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Tq(this.g,"srv3",(0,g.x)(this.gL,this))),this.g&&!q3(this)?this.player.la("captionschanged",U1(this.g)):this.player.la("onCaptionsTrackListChanged");else{var a;this.ma?a=new e2(this.l.ia,this.player):this.xa?a=new $1(this.u,this.l,this.player.getAudioTrack()):a=new h2(this.l.nj,this.l.videoId,this.l.ag||this.u.ag||
g.uB(this.l,"yt:cc_default_lang")||this.u.Wb,this.l.ip,this.u);this.i=a;g.G(this,this.i);a.Uq((0,g.x)(this.fL,this))}};
g.h.unload=function(){this.C&&this.g?r3(this,!1):(this.fa&&g.co(this.fa),g.aK(this.player,"captions"),this.H=[],this.i&&this.i.Ig(),this.Z.clear(),this.F&&g.YJ(this.player,this.F),this.Zs());g.sK.prototype.unload.call(this);var a=g.V(this.player.app);a&&a.o&&g.eD(a.o.l);this.player.la("captionschanged",{})};
g.h.fL=function(){var a;this.P||m3(this)?a=p3(this,this.P):n3(this)&&(a=o3(this));if(this.C||this.R){for(var b=X1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.sz(e),srclang:V1(e),id:e.toString()};this.R||(f.src=this.i.Lj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Rd("TRACK",f))}this.I.app.u.ij(c);a=this.I.app.u.ga();this.va&&this.aa.K(a.textTracks,"change",this.hL)}else!this.g&&a&&t3(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.hL=function(){for(var a=this.I.app.u.ga().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=X1(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&t3(this,b,!0)};
g.h.HM=function(){!this.g&&this.C||this.unload()};
g.h.gL=function(a,b,c,d){if(a){this.i.wz()&&(this.H=[],g.aK(this.I,"captions"),this.X.Pj(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if(!g.Fa(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Lt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!b3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.Fa(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new e3);var z=e.g.o(b,u);.01>Math.random()&&g.Cp(Error("Deprecated subtitles format in web player: WebVTT"));var C=z}else b:{z=a;u=g.Un(z);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=z;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){z={};var F=V1(b);F&&(z.lang=F,Mpa.test(F)&&(z.ze=1));e.g=new N2(z,e.i)}C=e.g.o(u,c);break b}var L=Error("Unsupported subtitles format in web player (Format2)");L.params=z;throw L;}if("transcript"==u.firstChild.tagName){var aa=Error("Unsupported subtitles format in web player (Format1)");aa.params=z;throw aa;}var qa=Error("Invalid caption track data");qa.params=z;throw qa;}var xa=
C}else{C=a;u=c;F=d;if(!b3(C))throw Error("Invalid binary caption track data");e.g||(e.g=new $2(F,b));xa=e.g.o(C,u)}var cb=xa}catch(te){g.N(te),e.clear(),cb=[]}else cb=[];g.YJ(this.player,cb);!this.P||this.R||q3(this)||g.My(this.u)||g.Ny(this.u)||(g.co(this.fa),cb=l2({Vf:0,Re:5,Hg:5,Ok:2,textAlign:0,ze:0,lang:"es"}),this.O=[cb],e=["Haz clic en "," para ir a la configuraci\u00f3n"],this.ea||(xa=new g.GC(g.zP()),g.G(this,xa),this.ea=xa.element),xa=cb.end-cb.start,(b=g.sz(this.g))&&this.O.push(new i2(cb.start,
xa,0,cb.id,b)),this.O.push(new i2(cb.start,xa,0,cb.id,e[0]),new i2(cb.start,xa,0,cb.id,this.ea,!0),new i2(cb.start,xa,0,cb.id,e[1],!0)),g.YJ(this.player,this.O),g.ao(this.fa));!this.P||this.R||q3(this)||(s3(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(cb=g.V(this.player.app))&&cb.o&&g.eD(cb.o.l));this.P=!1}};
g.h.RE=function(a){this.H.push(a);this.X.Pj()};
g.h.SE=function(a){g.eb(this.H,a);this.i instanceof e2&&this.i.A&&g.$J(this.player,[a]);this.X.Pj()};
g.h.RL=function(a){if(a instanceof j2){var b=this.N[a.id];b&&b.o!=a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=Lpa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.W[b]||(this.W[b]=[]),this.W[b].push(a)};
g.h.YL=function(){v3(this,this.O);this.O=null};
g.h.QA=function(){this.X.stop();g.Zb(this.W);this.H.sort(g.SD);var a=this.H;if(this.F){var b=(0,g.Yd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.A)(a,this.RL,this);g.Lb(this.N,function(c,d){this.W[d]?(c.element.parentNode||g.eK(this.player,c.element,4),c.zh(this.W[d])):(c.dispose(),delete this.N[d])},this)};
g.h.cM=function(){j3(this,{},!0)};
g.h.cD=function(){var a=u3.wb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Qe?3:a.bold?1:a.Qe?2:0,textOpacity:a.textOpacity,windowColor:u3.windowColor,windowOpacity:u3.windowOpacity};var b=k3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.VA=function(a,b){var c={};g.Ta(c,k3(this,"display-settings"));g.Ta(c,a);j3(this,c,b);this.player.la("captionssettingschanged")};
g.h.Zs=function(){!this.C&&this.loaded&&(g.Lb(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.QA())};
g.h.wc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.qd(b,-2,4);this.VA({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&t3(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.rb&&s3(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.Yb(b)){t3(this,null,!0);break}for(var d=X1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?tpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||t3(this,c,!0)}else return this.loaded&&this.g&&!q3(this)?U1(this.g):{};return"";case "tracklist":return this.i?(0,g.B)(X1(this.i.i,!(!b||!b.includeAsr)),function(k){return U1(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.C||void 0==b||w3(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.rb&&a.push("stickyLoading");return a};
g.h.Nj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.BM=function(){this.loaded&&this.g&&!q3(this)?(s3(this,"module-enabled",!1),this.unload(),n3(this,!0)&&t3(this,o3(this),!1)):t3(this,q3(this)||!this.g?p3(this,!0):this.g,!0)};
g.h.bI=function(){var a=q3(this);n3(this,a)?t3(this,this.player.getAudioTrack().gm,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Tk()&&(a?t3(this,p3(this),!1):this.load()))};g.OU.captions=l3;})(_yt_player);
