(function(g){var window=this;var y3=function(a,b,c){var d=b.oa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.xc(c?c:"mqdefault.jpg");var f=b instanceof g.UA&&b.lengthSeconds?g.xQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.UD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.UA?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.jj||g.cN("Ver $TITLE",{TITLE:b.title}),duration:f,url:b.Oj(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.WD&&(d.playlist_length=b.getLength());a.update(d)},z3=function(a,b){g.LC.call(this,{B:"div",
V:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},A3=function(a){g.W.call(this,{B:"div",
V:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",U:"Siguiente"},{B:"span",G:"ytp-upnext-title",U:"{{title}}"},{B:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente v\u00eddeo"},J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},J:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",
U:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",V:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},U:"Cancelar"});g.G(this,this.A);this.A.ca("click",this.gI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.M(this.Tl,5E3,this);g.G(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],
"click",this.TJ);this.wy();this.K(a,"autonavvisibility",this.wy);this.K(a,"mdxnowautoplaying",this.lJ);this.K(a,"mdxautoplaycanceled",this.mJ);this.K(a,"mdxautoplayupnext",this.UA);3==this.l.getPresentingPlayerType()&&(a=(a=g.SJ(g.MJ(this.l)))?a.aD():null)&&this.UA(a)},B3=function(a,b){if(!a.o){g.Rp("a11y-announce","Siguiente "+a.u.title);
a.H=g.O();a.o=new g.M((0,g.x)(a.Vo,a,b),25);a.Vo(b);var c=b||g.R(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.Sn(a.element,"ytp-upnext-autoplay-paused")},D3=function(a){C3(a);
a.H=g.O();a.Vo();g.J(a.element,"ytp-upnext-autoplay-paused")},C3=function(a){a.o&&(a.o.dispose(),a.o=null)},E3=function(a,b){b=void 0===b?!1:b;
if(g.Q(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Tl(),a.C=new Notification("Siguiente",{body:c.title,icon:c.xc()}),a.D=a.K(a.C,"click",a.LJ),a.F.start())}C3(a);a.l.nextVideo(!1,b)},F3=function(a){z3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Od}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",U:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.G(this,this.l);this.l.g(this.element);this.o=new g.GV("Suscribirse",null,"Cancelar suscripci\u00f3n",null,!0,!1,b.Sf,b.subscribed,"trailer-endscreen",null,null,a);g.G(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},
G3=function(a){var b=g.X(a),c=g.Nw||g.Ch?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",V:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",U:"En directo"},{B:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{B:"span",V:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",U:"{{playlist_length}}"},")"]}]},{B:"span",V:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.us(this);g.G(this,this.u);this.ca("click",this.D);this.ca("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.RN(a.app.R,this.element,this);this.C()},H3=function(a){g.hK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.MX(a.l.app,b,a.o.Xb,c,void 0,void 0)},I3=function(a){z3.call(this,a,"videowall-endscreen");
this.H=a;this.C=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.aa=new g.us(this);g.G(this,this.aa);this.I=new g.M(g.Sa(g.J,this.element,"ytp-show-tiles"),0);g.G(this,this.I);var b=new g.W({B:"button",V:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Anterior"},J:[g.gP()]});g.G(this,b);b.g(this.element);b.ca("click",this.zF,this);this.N=new g.GC({B:"div",G:"ytp-endscreen-content"});g.G(this,this.N);this.N.g(this.element);b=new g.W({B:"button",V:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Siguiente"},J:[g.hP()]});g.G(this,b);b.g(this.element);b.ca("click",this.yF,this);this.l=new A3(a);g.G(this,this.l);g.eK(this.player,this.l.element,4);this.hide()},J3=function(a){return g.fK(a.player)&&a.xu()&&!a.D},K3=function(a,b){return(0,g.B)(b.suggestions,function(c){c=g.LR(g.X(a.H),c);
g.G(a,c);return c})},L3=function(a){var b=a.Ne();
b!=a.R&&(a.R=b,a.player.M("autonavvisibility"))},N3=function(a){g.sK.call(this,a);
this.g=null;this.i=new g.us(this);g.G(this,this.i);this.l=g.X(a);M3(a)?this.g=new I3(this.player):this.l.Ea?this.g=new F3(this.player):this.g=new z3(this.player);g.G(this,this.g);g.eK(this.player,this.g.element,4);this.Sz();this.i.K(a,"videodatachange",this.Sz,this);this.i.K(a,g.TD("endscreen"),this.LE,this);this.i.K(a,"crx_endscreen",this.ME,this)},M3=function(a){a=g.X(a);
return a.Ba&&!a.Ea};
g.t(z3,g.LC);z3.prototype.create=function(){this.created=!0};
z3.prototype.destroy=function(){this.created=!1};
z3.prototype.xu=function(){return!1};
z3.prototype.Ne=function(){return!1};g.t(A3,g.W);g.h=A3.prototype;g.h.Tl=function(){this.C&&(this.F.stop(),this.La(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.wy=function(){g.KC(this,this.l.Ne())};
g.h.LJ=function(){window.focus();this.Tl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Vo=function(a){a=a||g.R(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.O()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?E3(this,!0):this.o&&this.o.start()};
g.h.TJ=function(a){!g.ae(this.A.element,g.Or(a))&&g.OR(a,this.l)&&E3(this)};
g.h.gI=function(){g.OJ(this.l,!0)};
g.h.lJ=function(a){this.l.getPresentingPlayerType();this.show();B3(this,a)};
g.h.UA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,y3(this,a,"hqdefault.jpg"))};
g.h.mJ=function(){this.l.getPresentingPlayerType();C3(this);this.hide()};
g.h.T=function(){C3(this);this.Tl();g.W.prototype.T.call(this)};g.t(F3,z3);g.t(G3,g.W);G3.prototype.D=function(a){g.OR(a,this.l,this.A,this.o.Xb||void 0)&&H3(this)};
G3.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.Tr(a)||(H3(this),g.Sr(a))}};
G3.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Nb?!1:b.i};g.t(I3,z3);g.h=I3.prototype;g.h.create=function(){z3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=K3(this,a),this.u=a);this.Lf();this.aa.K(this.player,"appresize",this.Lf);this.aa.K(this.player,"onVideoAreaChange",this.Lf);this.aa.K(this.player,"videodatachange",this.AF);this.aa.K(this.player,"autonavchange",this.jr);this.aa.K(this.player,"autonavcancel",this.xF);a=this.u.autonavState;a!=this.O&&this.jr(a);this.aa.K(this.element,"transitionend",this.iL)};
g.h.destroy=function(){g.ws(this.aa);g.rf(this.o);this.o=[];this.A=null;z3.prototype.destroy.call(this);g.Sn(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.xu=function(){return 1!=this.u.autonavState};
g.h.show=function(){z3.prototype.show.call(this);g.Sn(this.element,"ytp-show-tiles");g.X(this.player).g?g.bo(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.OJ(this.player,!1);J3(this)?(L3(this),2==this.u.autonavState?g.Q(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?E3(this.l,!0):B3(this.l):3==this.u.autonavState&&D3(this.l)):(g.OJ(this.player,!0),L3(this))};
g.h.hide=function(){z3.prototype.hide.call(this);D3(this.l);L3(this)};
g.h.iL=function(a){g.Or(a)==this.element&&this.Lf()};
g.h.Lf=function(){if(this.A&&this.A.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.WJ(this.H,!0),b=g.$C(this.H);b&&(b=b.zc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.qd(a.width/m||1,1,1.21);n*=g.qd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Rh(a,m,n);g.zh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;y3(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",J3(this));L3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.rd(p+this.C,l),0!=r){u=this.o[c];u||(u=new G3(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-C-4;g.Hh(u.element,C,z);g.Rh(u.element,F,E);g.zh(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1==r);g.K(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,y3(r,p,g.Qn(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Xb)&&p.itct)&&(u=r.l,g.X(u).F&&g.SN(u.app.R,r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Xd(e.element),g.qf(e);this.o.length=c}};
g.h.AF=function(){var a=this.player.getVideoData();this.u!=a&&(this.C=0,this.A=K3(this,a),this.u=a,this.Lf())};
g.h.yF=function(){this.C+=this.o.length;this.Lf()};
g.h.zF=function(){this.C-=this.o.length;this.Lf()};
g.h.aE=function(){return!!this.l.o};
g.h.jr=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,C3(this.l),this.Da()&&this.Lf()):(this.F=!0,this.Da()&&J3(this)&&(2==a?B3(this.l):3==a&&D3(this.l)))};
g.h.xF=function(a){if(a){for(a=0;a<this.o.length;a++)g.iK(this.H,this.o[a].element,!0);this.jr(1)}else this.D=null,this.F=!1;this.Lf()};
g.h.Ne=function(){return this.Da()&&J3(this)};g.t(N3,g.sK);g.h=N3.prototype;g.h.Tk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!M3(this.player)||b;a=a.Kc||g.Hy(a.Na);var c=g.mX(this.player.app);return b&&!a&&!c};
g.h.Ne=function(){return this.g.Ne()};
g.h.VD=function(){return this.Ne()?this.g.aE():!1};
g.h.T=function(){g.aK(this.player,"endscreen");g.sK.prototype.T.call(this)};
g.h.load=function(){g.sK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.sK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.LE=function(a){this.Tk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.ME=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Sz=function(){g.aK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.QD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.G(this,a);var b=new g.QD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.G(this,b);g.YJ(this.player,[a,b])};g.OU.endscreen=N3;})(_yt_player);
