(function(g){var window=this;var Xpa=function(a,b){return g.Vb(a,b)},V4=function(){},Ypa=function(a){if(a.yc&&"function"==typeof a.yc)return a.yc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Zpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.A)(a,b,void 0);else{if(a.Hd&&"function"==typeof a.Hd)var c=a.Hd();else if(a.yc&&"function"==typeof a.yc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Ypa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},W4=function(a){g.Um(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},X4=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.Zm(a.l,b,c)},Y4=function(a){return(a=g.so(a))?new ActiveXObject(a):new XMLHttpRequest},Z4=function(a,b){return b+" ["+a.ba+" "+a.D+" "+a.getStatus()+"]"},$pa=function(a){return"content-type"==a.toLowerCase()},$4=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},aqa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},a5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},b5=function(a,b){if(a.g){$4(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},c5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;a5(a);b5(a)},d5=function(a){return a.g?a.g.readyState:0},e5=function(a){if(a.i&&"undefined"!=typeof g.bY)if(a.P[1]&&4==d5(a)&&2==a.getStatus())Z4(a,"Local request error detected and ignored");
else if(a.C&&4==d5(a))g.Gg(a.gw,0,a);else if(a.dispatchEvent("readystatechange"),4==d5(a)){Z4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!bqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<d5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";a5(a)}}finally{b5(a)}}},f5=function(a){g.Sf.call(this);
this.headers=new g.Jm;this.N=a||null;this.i=!1;this.P=this.g=null;this.ba=this.D="";this.u=0;this.l="";this.o=this.W=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},g5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},cqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Ho.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Go(e)&&c.push(d):c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.A)(c,function(d){g.Ho.prototype.remove.call(this,d)},a)},h5=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},eqa=function(a,b){g.ab(a,b)||a.push(b)},i5=function(a){var b=0,c;
for(c in a)b++;return b},j5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},fqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a,b,c,d){var e=new g.Mm(null,void 0);
a&&g.Nm(e,a);b&&g.Om(e,b);c&&g.Pm(e,c);d&&(e.i=d);return e},k5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return fqa(a)},l5=function(){this.g=[];
this.i=[]},m5=function(a,b){g.Mp[a]=!0;
var c=g.Kp();c&&c.publish.apply(c,arguments);g.Mp[a]=!1},n5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Jm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",hqa(this,a.capabilities||""),iqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},hqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa(Xpa,jqa)).forEach(function(c){a.capabilities.add(c)})},iqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},o5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},q5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kqa=function(a){return new o5(a)},r5=function(a){return g.Ma(a)?(0,g.B)(a,kqa):[]},s5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},t5=function(a){return g.Ma(a)?"["+(0,g.B)(a,s5).join(",")+"]":"null"},u5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},v5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},w5=function(a,b){return g.Ya(a,function(c){return p5(c,b)})},x5=function(a){try{var b=(0,g.dt)(),c=(0,g.ct)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},mqa=function(){var a=(0,g.ct)();
a&&dqa(a,a.g.mf(!0))},y5=function(){var a=g.ft("yt-remote-connected-devices")||[];
g.rb(a);return a},nqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},z5=function(a){g.et("yt-remote-connected-devices",a,86400)},B5=function(){if(A5)return A5;
var a=g.ft("yt-remote-device-id");a||(a=u5(),g.et("yt-remote-device-id",a,31536E3));for(var b=y5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return A5=d},C5=function(){var a=y5(),b=B5();
g.ab(a,b);g.gt()&&g.tb(a,b);a=nqa(a);if(0==a.length)try{g.gs("remote_sid")}catch(c){}else try{g.fs("remote_sid",a.join(","),-1)}catch(c){}},D5=function(){return g.ft("yt-remote-session-browser-channel")},E5=function(){return g.ft("yt-remote-local-screens")||[]},F5=function(){g.et("yt-remote-lounge-token-expiration",!0,86400)},oqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(E5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&F5();
g.et("yt-remote-local-screens",a,31536E3)},pqa=function(a,b){g.et("yt-remote-session-browser-channel",a);
g.et("yt-remote-session-screen-id",b);var c=y5(),d=B5();g.ab(c,d)||c.push(d);z5(c);C5()},G5=function(a){a||(x5("yt-remote-session-screen-id"),x5("yt-remote-session-video-id"));
C5();a=y5();g.eb(a,B5());z5(a)},I5=function(){if(!H5){var a=g.Ro();
a&&(H5=new g.Bo(a))}return H5?!!H5.get("yt-remote-use-staging-server"):!1},J5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},K5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},M5=function(a){a.length?L5(a.shift(),function(){M5(a)}):N5()},qqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},L5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},N5=function(){var a=K5();
a&&a(!1,"No cast extension found")},O5=function(){if(rqa){var a=2,b=K5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;L5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",N5,c)}},sqa=function(){O5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);M5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},P5=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Uc=b;this.u=(0,g.x)(this.fD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},Q5=function(){},R5=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.$m(this);this.i=new g.Fg;this.i.setInterval(250)},T5=function(a,b,c){a.Xh=1;
a.Xf=W4(b.clone());a.sh=c;a.u=!0;S5(a,null)},U5=function(a,b,c,d,e){a.Xh=1;
a.Xf=W4(b.clone());a.sh=null;a.u=c;e&&(a.Yz=!1);S5(a,d)},S5=function(a,b){a.Fi=(0,g.H)();
V5(a);a.Eg=a.Xf.clone();X4(a.Eg,"t",a.A);a.jl=0;a.sc=a.g.Ap(a.g.Vk()?b:null);0<a.fq&&(a.Hn=new g.zl((0,g.x)(a.fB,a,a.sc),a.fq));a.aa.ca(a.sc,"readystatechange",a.UL);var c=a.ah?g.cc(a.ah):{};a.sh?(a.oo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Eg,a.oo,a.sh,c)):(a.oo="GET",a.Yz&&!g.Od&&(c.Connection="close"),a.sc.send(a.Eg,a.oo,null,c));a.g.te(1)},b6=function(a,b,c){for(var d=!0;!a.Qg&&a.jl<c.length;){var e=tqa(a,c);
if(e==W5){4==b&&(a.pg=4,X5(15),d=!1);break}else if(e==Y5){a.pg=4;X5(16);d=!1;break}else Z5(a,e)}4==b&&0==c.length&&(a.pg=1,X5(17),d=!1);a.xe=a.xe&&d;d||($5(a),a6(a))},tqa=function(a,b){var c=a.jl,d=b.indexOf("\n",c);
if(-1==d)return W5;c=Number(b.substring(c,d));if(isNaN(c))return Y5;d+=1;if(d+c>b.length)return W5;var e=b.substr(d,c);a.jl=d+c;return e},e6=function(a,b){a.Fi=(0,g.H)();
V5(a);var c=b?window.location.hostname:"";a.Eg=a.Xf.clone();g.Um(a.Eg,"DOMAIN",c);g.Um(a.Eg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){$5(a);a.pg=7;X5(22);a6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in c6)k=c6[l];else if(l in d6)k=c6[l]=d6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
c6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Nc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.lL,a);a.Be.parentWindow.d=(0,g.x)(a.cz,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.cz,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Dc(a.Eg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},V5=function(a){a.lt=(0,g.H)()+a.o;
f6(a,a.o)},f6=function(a,b){if(null!=a.Yi)throw Error("WatchDog timer not null");
a.Yi=g6((0,g.x)(a.vL,a),b)},h6=function(a){a.Yi&&(g.v.clearTimeout(a.Yi),a.Yi=null)},a6=function(a){a.g.dw()||a.Qg||a.g.un(a)},$5=function(a){h6(a);
g.qf(a.Hn);a.Hn=null;a.i.stop();g.bn(a.aa);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},Z5=function(a,b){try{a.g.Wy(a,b),a.g.te(4)}catch(c){}},j6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;i6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){j6(a,b,c,d,f)},f)})}},i6=function(a,b,c){var d=new Image;
d.onload=function(){try{k6(d),c(!0)}catch(e){}};
d.onerror=function(){try{k6(d),c(!1)}catch(e){}};
d.onabort=function(){try{k6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{k6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
j5(d,a)},k6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},l6=function(a){this.g=a;
this.i=new Q5},n6=function(a){var b=m6(a.g,a.lj,"/mail/images/cleardot.gif");
W4(b);j6(b.toString(),5E3,(0,g.x)(a.mC,a),3,2E3);a.te(1)},p6=function(a){var b=a.g.F;
if(null!=b)X5(5),b?(X5(11),o6(a.g,a,!1)):(X5(12),o6(a.g,a,!0));else if(a.Dd=new R5(a,void 0,void 0,void 0),a.Dd.ah=a.cq,b=a.g,b=m6(b,b.Vk()?a.Uj:null,a.eq),X5(5),!g.Md||g.pd(10))X4(b,"TYPE","xmlhttp"),U5(a.Dd,b,!1,a.Uj,!1);else{X4(b,"TYPE","html");var c=a.Dd;a=!!a.Uj;c.Xh=3;c.Xf=W4(b.clone());e6(c,a)}},q6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new Q5;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},uqa=function(a,b){this.g=a;
this.map=b;this.context=null},r6=function(a){g.sf.call(this,"statevent",a)},s6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},t6=function(a){g.sf.call(this,"serverreachability",a)},x6=function(a){u6(a);
if(3==a.g){var b=a.Dk++,c=a.hm.clone();g.Um(c,"SID",a.l);g.Um(c,"RID",b);g.Um(c,"TYPE","terminate");v6(a,c);b=new R5(a,a.l,b,void 0);b.Xh=2;b.Xf=W4(c.clone());j5(new Image,b.Xf.toString());b.Fi=(0,g.H)();V5(b)}w6(a)},z6=function(a){a.EC(1,0);
a.hm=m6(a,null,a.bq);y6(a)},u6=function(a){a.fg&&(a.fg.abort(),a.fg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.qf&&(g.v.clearTimeout(a.qf),a.qf=null);A6(a);a.zd&&(a.zd.cancel(),a.zd=null);a.lg&&(g.v.clearTimeout(a.lg),a.lg=null)},B6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new uqa(a.BH++,b));2!=a.g&&3!=a.g||y6(a)},y6=function(a){a.zd||a.lg||(a.lg=g6((0,g.x)(a.bz,a),0),a.Rh=0)},E6=function(a,b){if(1==a.g){if(!b){a.Dk=Math.floor(1E5*Math.random());
var c=a.Dk++,d=new R5(a,"",c,void 0);d.ah=null;var e=C6(a),f=a.hm.clone();g.Um(f,"RID",c);g.Um(f,"CVER","1");v6(a,f);T5(d,f,e);a.zd=d;a.g=2}}else 3==a.g&&(b?D6(a,b):0==a.i.length||a.zd||D6(a))},D6=function(a,b){if(b)if(6<a.Rg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Dk-1;var d=C6(a)}else c=b.C,d=b.sh;else c=a.Dk++,d=C6(a);var e=a.hm.clone();g.Um(e,"SID",a.l);g.Um(e,"RID",c);g.Um(e,"AID",a.ki);v6(a,e);c=new R5(a,a.l,c,a.Rh+1);c.ah=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.zd=c;T5(c,e,d)},v6=function(a,b){if(a.Rc){var c=a.Rc.Gv();
c&&g.Lb(c,function(d,e){g.Um(b,e,d)})}},C6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Rg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Rg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},F6=function(a){a.Sb||a.qf||(a.C=1,a.qf=g6((0,g.x)(a.az,a),0),a.Jh=0)},H6=function(a){if(a.Sb||a.qf||3<=a.Jh)return!1;
a.C++;a.qf=g6((0,g.x)(a.az,a),G6(a,a.Jh));a.Jh++;return!0},o6=function(a,b,c){a.lo=c;
a.Je=b.Af;a.A||z6(a)},A6=function(a){null!=a.Vg&&(g.v.clearTimeout(a.Vg),a.Vg=null)},G6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},J6=function(a,b){if(2==b||9==b){var c=null;
a.Rc&&(c=null);var d=(0,g.x)(a.zM,a);c||(c=new g.Mm("//www.google.com/images/cleardot.gif"),W4(c));i6(c.toString(),1E4,d)}else X5(2);I6(a,b)},I6=function(a,b){a.g=0;
a.Rc&&a.Rc.Iu(b);w6(a);u6(a)},w6=function(a){a.g=0;
a.Je=-1;if(a.Rc)if(0==a.o.length&&0==a.i.length)a.Rc.mp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Rc.mp(b)}},m6=function(a,b,c){var d=g.Vm(c);
if(""!=d.g)b&&g.Om(d,b+"."+d.g),g.Pm(d,d.u);else{var e=window.location;d=gqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.yj&&g.Lb(a.yj,function(f,k){g.Um(d,k,f)});
g.Um(d,"VER",a.Rg);v6(a,d);return d},g6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},X5=function(a){K6.dispatchEvent(new r6(K6,a))},L6=function(){},vqa=function(a,b){this.action=a;
this.params=b||{}},M6=function(a,b){g.D.call(this);
this.g=new g.M(this.dL,0,this);g.G(this,this.g);this.Uc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},N6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Ao;this.i=new M6(this.dM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},wqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.lo,sessionId:a.g.l,arrayId:a.g.ki}},O6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&E6(a.g),x6(a.g));a.D=0},P6=function(a){return!!a.g&&3==a.g.g},xqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},Q6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},R6=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},S6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),ie:g.Sa(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Eq(b,a)},yqa=function(){var a=T6;
U6();V6.push(a);W6(V6)},X6=function(a,b){U6();
var c=V6,d=zqa(a,String(b));0==c.length?Aqa(d):(W6(c),(0,g.A)(c,function(e){e(d)}))},U6=function(){V6||(V6=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",V6,void 0))},Aqa=function(a){var b=(Y6+1)%50;
Y6=b;Z6[b]=a;$6||($6=49==b)},W6=function(a){var b=Z6;
if(b[0]){var c=Y6,d=$6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(f){f(e)})}while(d!=c);
Z6=Array(50);Y6=-1;$6=!1}},zqa=function(a,b){var c=((0,g.H)()-Bqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},a7=function(a){g.P.call(this);
this.C=a;this.g=[]},b7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!v5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=b7(a,b[d])||c;return c},Dqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},c7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},e7=function(a){a7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;d7(this);this.info("Initializing with "+t5(this.g))},f7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=R6(a.l,"/pairing/get_lounge_token_batch");
S6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.pD,a),(0,g.x)(a.oD,a))}},d7=function(a){var b=r5(E5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Cqa(a,b)},g7=function(a,b){oqa((0,g.B)(a.g,q5));
b&&F5()},i7=function(a,b){g.P.call(this);
this.A=b;var c=g.ft("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;h7("Initialized with "+g.Kg(this.g))},j7=function(a,b,c){var d=R6(a.u,"/pairing/get_screen_availability");
S6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},k7=function(a,b){a:if(i5(b)!=i5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(h7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.M("screenChange"));Eqa(a)},l7=function(a){isNaN(a.l)||g.Jp(a.l);
a.l=g.Hp((0,g.x)(a.os,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},h7=function(a){X6("OnlineScreenService",a)},m7=function(a){var b={};
(0,g.A)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Eqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.et("yt-remote-online-screen-ids",a.join(","),60):x5("yt-remote-online-screen-ids")},n7=function(a){a7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Fqa(this)},p7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Jd();if(k=(c?w5(k,c):null)||w5(k,b)){k.uuid=b;var l=o7(a,k);j7(a.i,l,function(m){e(m?l:null)})}else c?Gqa(a,c,(0,g.x)(function(m){var n=o7(this,new o5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));j7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},q7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Gqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Eq(R6(a.A,"/pairing/get_lounge_token_batch"),e)},r7=function(a){a.g=a.l.Jd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+t5(a.g))},Fqa=function(a){s7(a);
a.l=new e7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.xD,a));r7(a);a.o=r5(g.ft("yt-remote-automatic-screen-cache")||[]);s7(a);a.info("Initializing automatic screens: "+t5(a.o));a.i=new i7(a.A,(0,g.x)(a.Jd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.M("onlineScreenChange")},a))},o7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=w5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.et("yt-remote-automatic-screen-cache",(0,g.B)(a.o,q5)));s7(a);a.u[b.uuid]=b.id;g.et("yt-remote-device-id-map",a.u,31536E3);return b},s7=function(a){a.u=g.ft("yt-remote-device-id-map")||{}},t7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},u7=function(a,b){X6(a.P,b)},w7=function(a,b){t7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.eN,this);this.u=(0,g.x)(this.GL,this);this.o=g.Hp((0,g.x)(function(){v7(this,null)},this),12E4)},Hqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){u7(this,"Failed to send message: getMdxSessionStatus.")},a)):u7(a,"Sending yt message without session: "+g.Kg(b))},v7=function(a,b){g.Jp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.wn,a),d=(0,g.x)(a.Md,a);a.Wv(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},x7=function(a,b,c){t7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.hN,this);this.g=g.Ja},y7=function(a){a.g=a.F.kB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.wn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Md(b)},a))},z7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}I5()&&(b.env_useStageMdx=1);return g.ah(b)},A7=function(a,b){t7.call(this,a,b,"ManualSession");
this.g=g.Hp((0,g.x)(this.mi,this,null),150)},B7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.mK,this)},C7=function(a,b){return b?g.Ya(a.l,function(c){return p5(b,c.label)},a):null},D7=function(a){X6("Controller",a)},T6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},E7=function(a){return a.u||!!a.l.length||!!a.g},F7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Zy,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.M("yt-remote-cast2-session-change",null))},G7=function(a){var b=a.i.jB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&p5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=C7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lqa=function(a,b,c,d,e,f,k){Iqa()?Jqa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?J7(a,c):(window.__onGCastApiAvailable=function(l,m){l?J7(a,c):(K7("Failed to load cast API: "+m),L7(!1),I7(!1),x5("yt-remote-cast-available"),x5("yt-remote-cast-receiver"),M7(),c(!1))},d?g.Up("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?sqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?N5():(O5(),M5(Kqa.map(qqa))))):H7("Cannot initialize because not running Chrome")},M7=function(){H7("dispose");
var a=N7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);O7(!1);g.Pp(P7);P7.length=0},Q7=function(){return!!g.ft("yt-remote-cast-installed")},R7=function(){var a=g.ft("yt-remote-cast-receiver");
return a?a.friendlyName:null},S7=function(){H7("clearCurrentReceiver");
x5("yt-remote-cast-receiver")},T7=function(){return Q7()?N7()?N7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},V7=function(){Q7()?N7()?U7()?(H7("Requesting cast selector."),N7().requestSession()):(H7("Wait for cast API to be ready to request the session."),P7.push(g.Op("yt-remote-cast2-api-ready",V7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},W7=function(a,
b){U7()?N7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},Iqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Nw||a},Mqa=function(a,b){N7().init(a,b)},Jqa=function(a,b,c,d){var e=!1;
N7()||(a=new B7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.et("yt-remote-cast-available",f);m5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f);m5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+s5(f));
f||x5("yt-remote-cast-receiver");m5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},J7=function(a,b){L7(!0);
I7(!1);Mqa(a,function(c){c?(O7(!0),g.Rp("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),x5("yt-remote-cast-available"),x5("yt-remote-cast-receiver"),M7());b(c)})},H7=function(a){X6("cloudview",a)},K7=function(a){X6("cloudview",a)},L7=function(a){H7("setCastInstalled_ "+a);
g.et("yt-remote-cast-installed",a)},U7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},O7=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},X7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ke=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},Y7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},Z7=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},$7=function(a,b){a.C=b;
a.A=(0,g.H)()},a8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},b8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&Y7(a)},c8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},f8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new l5;this.l=this.i=null;this.F=(0,g.x)(this.jI,this);this.C=(0,g.x)(this.Gk,this);this.D=(0,g.x)(this.iI,this);this.H=(0,g.x)(this.wI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ot,this),d8(this))):c=3;0!=c&&(b?this.ot(c):g.Hp((0,g.x)(function(){this.ot(c)},this),0));
var d=T7();d&&e8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},g8=function(a){return new X7(a.o.getPlayerContextData())},d8=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.jK,b),this))},a)},h8=function(a){(0,g.A)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},i8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},k8=function(a,b,c){var d=g8(a);
$7(d,c);-1E3!=d.playerState&&(d.playerState=b);j8(a,d)},l8=function(a,b,c){a.o.sendMessage(b,c)},j8=function(a,b){h8(a);
a.o.setPlayerContextData(c8(b));d8(a)},e8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Gk(null));
a.l=b;a.l&&(X6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Gk(a.l.media[0]))},m8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=g8(a);b.contentId!=d.videoId&&X6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;$7(d,a.i.getEstimatedTime());j8(a,d)}else X6("CP","No cast media video. Ignoring state update.")},n8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),l8(this,b,c))},a)},o8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Ma=this.g=null;this.O=a;this.P.push(g.Mr(window,"beforeunload",(0,g.x)(this.iD,this)));this.i=[];this.Ma=new X7;this.N=b.id;this.g=Nqa(this,c);this.g.subscribe("handlerOpened",this.nI,this);this.g.subscribe("handlerClosed",this.kI,this);this.g.subscribe("handlerError",this.lI,this);this.g.subscribe("handlerMessage",this.mI,this);xqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ma.videoId;
g.gt()&&g.et("yt-remote-session-video-id",d)},this)},p8=function(a){X6("conn",a)},Nqa=function(a,b){return new N6(R6(a.O,"/bc"),b)},q8=function(a,b){a.M("proxyStateChange",b)},Oqa=function(a){a.u=g.Hp((0,g.x)(function(){p8("Connecting timeout");
this.Nh(1)},a),2E4)},r8=function(a){g.Jp(a.u);
a.u=NaN},s8=function(a){g.Jp(a.H);
a.H=NaN},Pqa=function(a){t8(a);
a.F=g.Hp((0,g.x)(function(){u8(this,"getNowPlaying")},a),2E4)},t8=function(a){g.Jp(a.F);
a.F=NaN},w8=function(a,b){b&&(r8(a),s8(a));
b==(P6(a.g)&&isNaN(a.u))?b&&(q8(a,1),u8(a,"getSubtitlesTrack")):b?(a.Tv()&&a.Ma.reset(),q8(a,1),u8(a,"getNowPlaying"),v8(a)):a.Nh(1)},Qqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ma.videoId&&(g.Yb(b.params)?a.Ma.g=null:a.Ma.g=b.params,a.M("remotePlayerChange"))},x8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ma.listId=b.params.listId||a.Ma.listId;b8(a.Ma,c,d);a.M("remoteQueueChange")},Rqa=function(a,b){b.params=b.params||{};
x8(a,b);y8(a,b);a.M("autoplayDismissed")},y8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
$7(a.Ma,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ma.playerState&&(c=-1E3);a.Ma.playerState=c;c=Number(b.params.loadedTime);a.Ma.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Ma.D=isNaN(c)?0:c;c=a.Ma;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Ma;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Ma.playerState?Pqa(a):t8(a);a.M("remotePlayerChange")},Sqa=function(a,b){if(-1E3!=
a.Ma.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ma.playerState=c;c=parseInt(b.params.currentTime,10);$7(a.Ma,isNaN(c)?0:c);a.M("remotePlayerChange")}},Tqa=function(a,b){var c="true"==b.params.muted;
a.Ma.volume=parseInt(b.params.volume,10);a.Ma.muted=c;a.M("remotePlayerChange")},Uqa=function(a,b){a.A=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},Vqa=function(a,b){var c="true"==b.params.hasNext;
a.Ma.Ke="true"==b.params.hasPrevious;a.Ma.hasNext=c;a.M("previousNextChange")},v8=function(a){g.Jp(a.D);
a.D=g.Hp((0,g.x)(a.Nh,a,1),864E5)},u8=function(a,b,c){c?p8("Sending: action="+b+", params="+g.Kg(c)):p8("Sending: action="+b);
a.g.sendMessage(b,c)},z8=function(a){a7.call(this,"ScreenServiceProxy");
this.Tc=a;this.i=[];this.i.push(this.Tc.$_s("screenChange",(0,g.x)(this.cN,this)));this.i.push(this.Tc.$_s("onlineScreenChange",(0,g.x)(this.OJ,this)))},$qa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.zp("MDX_CONFIG")||b;mqa();C5();A8||(A8=new Q6(b?b.loungeApiHost:void 0),I5()&&(A8.g="/api/loungedev"));B8||(B8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",B8,void 0));Wqa();var c=C8();if(!c){var d=new n7(A8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=C8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lqa(a,d,function(m){m?D8()&&W7(D8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){m5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),E8("Initializing: "+g.Kg(b)),F8.push(g.Op("yt-remote-cast2-availability-change",function(){m5("yt-remote-receiver-availability-change")})),F8.push(g.Op("yt-remote-cast2-receiver-selected",function(){G8(null);
m5("yt-remote-auto-connect","cast-selector-receiver")})),F8.push(g.Op("yt-remote-cast2-receiver-resumed",function(){m5("yt-remote-receiver-resumed","cast-selector-receiver")})),F8.push(g.Op("yt-remote-cast2-session-change",Xqa)),F8.push(g.Op("yt-remote-connection-change",function(m){m?W7(D8(),"YouTube TV"):H8()||(W7(null,null),S7())})),a=I8(),b.isAuto&&(a.id+="#dial"),g.vq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),E8(" -- with channel params: "+
g.Kg(a)),Yqa(a),c.start(),D8()||Zqa())},ara=function(){var a=J8();
Q7()&&g.ft("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},J8=function(){var a=C8().Tc.$_gos();
var b=K8();b&&L8()&&(v5(a,b)||a.push(b));return lqa(a)},M8=function(){var a=bra();
!a&&Q7()&&R7()&&(a={key:"cast-selector-receiver",name:R7()});return a},bra=function(){var a=J8(),b=K8();
b||(b=H8());return g.Ya(a,function(c){return b&&p5(b,c.key)?!0:!1})},K8=function(){var a=D8();
if(!a)return null;var b=C8().Jd();return w5(b,a)},Xqa=function(a){E8("remote.onCastSessionChange_: "+s5(a));
if(a){var b=K8();b&&b.id==a.id?W7(b.id,"YouTube TV"):(b&&N8(),O8(a,1))}else L8()&&N8()},N8=function(){U7()?N7().stopSession():K7("stopSession called before API ready.");
var a=L8();a&&(a.disconnect(1),P8(null))},Q8=function(){var a=L8();
return!!a&&3!=a.getProxyState()},E8=function(a){X6("remote",a)},C8=function(){if(!R8){var a=g.w("yt.mdx.remote.screenService_");
R8=a?new z8(a):null}return R8},D8=function(){return g.w("yt.mdx.remote.currentScreenId_")},S8=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},T8=function(){return g.w("yt.mdx.remote.connectData_")},G8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},L8=function(){return g.w("yt.mdx.remote.connection_")},P8=function(a){var b=L8();
G8(null);a||S8("");g.Ia("yt.mdx.remote.connection_",a,void 0);B8&&((0,g.A)(B8,function(c){c(a)}),B8.length=0);
b&&!a?m5("yt-remote-connection-change",!1):!b&&a&&m5("yt-remote-connection-change",!0)},H8=function(){var a=g.gt();
if(!a)return null;var b=C8().Jd();return w5(b,a)},O8=function(a,b){K8()&&K8();
if(U8)V8=a;else{S8(a.id);var c=new o8(A8,a,I8());c.connect(b,T8());c.subscribe("beforeDisconnect",function(d){m5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){L8()&&P8(null)});
P8(c)}},Zqa=function(){var a=H8();
a?(E8("Resume connection to: "+s5(a)),O8(a,0)):(G5(),S7(),E8("Skipping connecting because no session screen found."))},Wqa=function(){var a=I8();
if(g.Yb(a)){a=B5();var b=g.ft("yt-remote-session-name")||"",c=g.ft("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},I8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Yqa=function(a){a?(g.et("yt-remote-session-app",a.app),g.et("yt-remote-session-name",a.name)):(x5("yt-remote-session-app"),x5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},W8=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.us(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.jJ);this.l.K(b,"captionschanged",this.hI);this.l.K(b,"captionssettingschanged",this.yA);this.l.K(b,"videoplayerreset",this.xn);this.l.K(b,"mdxautoplaycancel",this.lC);this.O=this.l.K(b,"onVolumeChange",this.Ky);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Vy,this);c.subscribe("remotePlayerChange",this.Ik,this);c.subscribe("remoteQueueChange",this.xn,this);c.subscribe("autoplayUpNext",this.zy,
this);c.subscribe("previousNextChange",this.Sy,this);c.subscribe("nowAutoplaying",this.Oy,this);c.subscribe("autoplayDismissed",this.yy,this);this.suggestion=null;this.F=new g.gC(64);this.o=new g.M(this.wA,500,this);g.G(this,this.o);this.A=new g.M(this.xA,1E3,this);g.G(this,this.A);this.I=new P5(this.IM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.WA,1E3,this);g.G(this,this.P);this.H=new g.zl(this.GF,1E3,this);g.G(this,this.H);this.N=g.Ja;this.yA();this.xn();this.Ik()},X8=function(a,b){a.u.qd(b,
a.i.getVideoData().lengthSeconds)},Z8=function(a){X8(a,0);
a.o.stop();Y8(a,new g.gC(64))},a9=function(a,b){if($8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.lA(a.i.getVideoData(1).videoId,c);a.C=g8(a.g).g}},b9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Df,h5(c));Y8(a,new g.gC(1))},c9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{xQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},$8=function(a){return g8(a.g).videoId==a.i.getVideoData(1).videoId},Y8=function(a,b){a.A.stop();
var c=a.F;if(!g.mC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.UJ(a.i,d);a.F=b;d9(a.u,c,b)}},e9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"No has iniciado sesi\u00f3n"},{B:"div",G:"ytp-mdx-popup-description",U:"Los v\u00eddeos que veas podr\u00edan aparecer en el historial de reproducciones de la TV e influir en las recomendaciones. Puedes evitarlo si cancelas e inicias sesi\u00f3n en YouTube desde tu ordenador."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],
U:"Cancelar"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],U:"Confirmar"}]}]}]});this.l=new g.PP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},g9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.eP()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.PP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);f9(this,g.QJ(a))},f9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.cN("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):g.nC(b)||g.U(b,4)?g.cN("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.cN("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.xT.call(this,"Reproducir en",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.sK.call(this,a);
this.i={key:u5(),name:"Este ordenador"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.pk=new g.gC(64);this.H=0;this.Lm=-1;if(!g.Ny(g.X(this.player))){a=this.player;var b=g.$C(a);b&&(b=b.rk())&&(b=new h9(a,b),g.G(this,b));b=new g9(a);g.G(this,b);g.eK(a,b.element,4);this.F=new e9;g.G(this,this.F);g.eK(a,this.F.element,4);this.D=!!H8()}},d9=function(a,b,c){a.pk=c;
a.player.M("presentingplayerstatechange",new g.nD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)N8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.zp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.zp("SESSION_INDEX")||g.zp("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),L8()||(U8=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Df,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=h5(c))&&(d.locationInfo=c);c=d}else c=null;E8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(G8(c||null),U7()?N7().setLaunchParams(c||null):K7("setLaunchParams called before ready.")):!c&&Q8()&&D8()==b.key?m5("yt-remote-connection-change",!0):(N8(),G8(c||null),c=C8().Jd(),(c=w5(c,b.key))&&O8(c,1))}},bqa=/^https?$/i,cra=["POST",
"PUT"];g.y(f5,g.Sf);g.h=f5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.N?Y4(this.N):Y4(g.xY);this.P=this.N?this.N.getOptions():g.xY.getOptions();this.g.onreadystatechange=(0,g.x)(this.gw,this);try{V4(Z4(this,"Opening Xhr")),this.W=!0,this.g.open(b,String(a),!0),this.W=!1}catch(f){V4(Z4(this,"Error opening Xhr: "+f.message));c5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Zpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Hd(),$pa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(cra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{$4(this),0<this.A&&(this.I=aqa(this.g),V4(Z4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.hw,this)):this.F=g.Gg(this.hw,this.A,this)),V4(Z4(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){V4(Z4(this,"Send error: "+f.message)),c5(this,f)}};
g.h.hw=function(){"undefined"!=typeof g.bY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,Z4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(Z4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),b5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),b5(this,!0));f5.Wa.T.call(this)};
g.h.gw=function(){this.da()||(this.W||this.C||this.o?e5(this):this.lK())};
g.h.lK=function(){e5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<d5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var d6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},c6={"'":"\\'"},dra={};g.h=l5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Lma)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.yc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var jqa={AN:"atp",LP:"ska",AP:"que",aP:"mus",KP:"sus",rO:"dsp",HP:"seq"};n5.prototype.gg=function(){var a=new n5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var H5,A5="",rqa=J5("loadCastFramework")||J5("loadCastApplicationFramework"),Kqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(P5,g.D);g.h=P5.prototype;g.h.eD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Uc:this.za=g.Gg(this.u,this.Uc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();P5.Wa.T.call(this)};
g.h.fD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};Q5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
Q5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=R5.prototype;g.h.ah=null;g.h.xe=!1;g.h.Yi=null;g.h.lt=null;g.h.Fi=null;g.h.Xh=null;g.h.Xf=null;g.h.Eg=null;g.h.sh=null;g.h.sc=null;g.h.jl=0;g.h.Be=null;g.h.oo=null;g.h.pg=null;g.h.Vj=-1;g.h.Yz=!0;g.h.Qg=!1;g.h.fq=0;g.h.Hn=null;var Y5={},W5={};g.h=R5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.UL=function(a){a=a.target;var b=this.Hn;b&&3==d5(a)?b.Rj():this.fB(a)};
g.h.fB=function(a){try{if(a==this.sc)a:{var b=d5(this.sc),c=this.sc.u,d=this.sc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!g5(this.sc))break a;this.Qg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));h6(this);var e=this.sc.getStatus();this.Vj=e;var f=g5(this.sc);(this.xe=200==e)?(4==b&&$5(this),this.u?(b6(this,b,f),g.Ch&&this.xe&&3==b&&(this.aa.ca(this.i,"tick",this.NL),this.i.start())):Z5(this,f),this.xe&&!this.Qg&&(4==b?this.g.un(this):(this.xe=
!1,V5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pg=3,X5(13)):(this.pg=0,X5(14)),$5(this),a6(this))}}catch(k){this.sc&&g5(this.sc)}finally{}};
g.h.NL=function(){var a=d5(this.sc),b=g5(this.sc);this.jl<b.length&&(h6(this),b6(this,a,b),this.xe&&4!=a&&V5(this))};
g.h.lL=function(a){g6((0,g.x)(this.kL,this,a),0)};
g.h.kL=function(a){this.Qg||(h6(this),Z5(this,a),V5(this))};
g.h.cz=function(a){g6((0,g.x)(this.jL,this,a),0)};
g.h.jL=function(a){this.Qg||($5(this),this.xe=a,this.g.un(this),this.g.te(4))};
g.h.cancel=function(){this.Qg=!0;$5(this)};
g.h.vL=function(){this.Yi=null;var a=(0,g.H)();0<=a-this.lt?(2!=this.Xh&&this.g.te(3),$5(this),this.pg=2,X5(18),a6(this)):f6(this,this.lt-a)};
g.h.getLastError=function(){return this.pg};g.h=l6.prototype;g.h.cq=null;g.h.Dd=null;g.h.In=!1;g.h.ew=null;g.h.fm=null;g.h.Pq=null;g.h.eq=null;g.h.be=null;g.h.Af=-1;g.h.Uj=null;g.h.lj=null;g.h.connect=function(a){this.eq=a;a=m6(this.g,null,this.eq);X5(3);this.ew=(0,g.H)();var b=this.g.D;null!=b?(this.Uj=b[0],(this.lj=b[1])?(this.be=1,n6(this)):(this.be=2,p6(this))):(X4(a,"MODE","init"),this.Dd=new R5(this,void 0,void 0,void 0),this.Dd.ah=this.cq,U5(this.Dd,a,!1,null,!0),this.be=0)};
g.h.mC=function(a){if(a)this.be=2,p6(this);else{X5(4);var b=this.g;b.Je=b.fg.Af;J6(b,9)}a&&this.te(2)};
g.h.Ap=function(a){return this.g.Ap(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.Af=-1};
g.h.dw=function(){return!1};
g.h.Wy=function(a,b){this.Af=a.Vj;if(0==this.be)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.Af;J6(c,2);return}this.Uj=c[0];this.lj=c[1]}else c=this.g,c.Je=this.Af,J6(c,2);else if(2==this.be)if(this.In)X5(7),this.Pq=(0,g.H)();else if("11111"==b){if(X5(6),this.In=!0,this.fm=(0,g.H)(),c=this.fm-this.ew,!g.Md||g.pd(10)||500>c)this.Af=200,this.Dd.cancel(),X5(12),o6(this.g,this,!0)}else X5(8),this.fm=this.Pq=(0,g.H)(),this.In=!1};
g.h.un=function(){this.Af=this.Dd.Vj;if(this.Dd.xe)0==this.be?this.lj?(this.be=1,n6(this)):(this.be=2,p6(this)):2==this.be&&((!g.Md||g.pd(10)?!this.In:200>this.Pq-this.fm)?(X5(11),o6(this.g,this,!1)):(X5(12),o6(this.g,this,!0)));else{0==this.be?X5(9):2==this.be&&X5(10);var a=this.g;this.Dd.getLastError();a.Je=this.Af;J6(a,2)}};
g.h.Vk=function(){return this.g.Vk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=q6.prototype;g.h.yj=null;g.h.zd=null;g.h.Sb=null;g.h.bq=null;g.h.hm=null;g.h.yu=null;g.h.sm=null;g.h.Dk=0;g.h.BH=0;g.h.Rc=null;g.h.lg=null;g.h.qf=null;g.h.Vg=null;g.h.fg=null;g.h.lo=null;g.h.ki=-1;g.h.Kw=-1;g.h.Je=-1;g.h.Rh=0;g.h.Jh=0;g.h.Rg=8;var K6=new g.Sf;g.y(r6,g.sf);g.y(s6,g.sf);g.y(t6,g.sf);g.h=q6.prototype;g.h.connect=function(a,b,c,d,e){X5(0);this.bq=b;this.yj=c||{};d&&g.Ea(e)&&(this.yj.OSID=d,this.yj.OAID=e);this.A?(g6((0,g.x)(this.Qu,this,a),100),z6(this)):this.Qu(a)};
g.h.Qu=function(a){this.fg=new l6(this);this.fg.cq=null;this.fg.i=this.u;this.fg.connect(a)};
g.h.dw=function(){return 0==this.g};
g.h.bz=function(a){this.lg=null;E6(this,a)};
g.h.az=function(){this.qf=null;this.Sb=new R5(this,this.l,"rpc",this.C);this.Sb.ah=null;this.Sb.fq=0;var a=this.yu.clone();g.Um(a,"RID","rpc");g.Um(a,"SID",this.l);g.Um(a,"CI",this.lo?"0":"1");g.Um(a,"AID",this.ki);v6(this,a);if(!g.Md||g.pd(10))g.Um(a,"TYPE","xmlhttp"),U5(this.Sb,a,!0,this.sm,!1);else{g.Um(a,"TYPE","html");var b=this.Sb,c=!!this.sm;b.Xh=3;b.Xf=W4(a.clone());e6(b,c)}};
g.h.Wy=function(a,b){if(0!=this.g&&(this.Sb==a||this.zd==a))if(this.Je=a.Vj,this.zd==a&&3==this.g)if(7<this.Rg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Sb)if(this.Sb.Fi+3E3<this.zd.Fi)A6(this),this.Sb.cancel(),this.Sb=null;else break a;H6(this);X5(19)}}else this.Kw=c[1],0<this.Kw-this.ki&&37500>c[2]&&this.lo&&0==this.Jh&&!this.Vg&&(this.Vg=g6((0,g.x)(this.dI,this),6E3));else J6(this,11)}else b!=dra.WN.g&&J6(this,11);else if(this.Sb==a&&
A6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.sm=e[2],e=e[3],null!=e?this.Rg=e:this.Rg=6,this.g=3,this.Rc&&this.Rc.Ku(),this.yu=m6(this,this.Vk()?this.sm:null,this.bq),F6(this)):"stop"==e[0]&&J6(this,7):3==this.g&&("stop"==e[0]?J6(this,7):"noop"!=e[0]&&this.Rc&&this.Rc.Ju(e),this.Jh=0)}}};
g.h.dI=function(){null!=this.Vg&&(this.Vg=null,this.Sb.cancel(),this.Sb=null,H6(this),X5(20))};
g.h.un=function(a){if(this.Sb==a){A6(this);this.Sb=null;var b=2}else if(this.zd==a)this.zd=null,b=1;else return;this.Je=a.Vj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.H)()-a.Fi,K6.dispatchEvent(new s6(K6,a.sh?a.sh.length:0,b,this.Rh)),y6(this),this.o.length=0):F6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.zd||this.lg||1==this.g||2<=this.Rh?d=!1:(this.lg=g6((0,g.x)(this.bz,this,a),G6(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&H6(this))}if(d)switch(c){case 1:J6(this,
5);break;case 4:J6(this,10);break;case 3:J6(this,6);break;case 7:J6(this,12);break;default:J6(this,2)}}};
g.h.EC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.zM=function(a){a?X5(2):(X5(1),I6(this,8))};
g.h.Ap=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new f5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Rc&&this.Rc.isActive(this)};
g.h.te=function(a){K6.dispatchEvent(new t6(K6,a))};
g.h.Vk=function(){return!(!g.Md||g.pd(10))};
g.h=L6.prototype;g.h.Ku=function(){};
g.h.Ju=function(){};
g.h.Iu=function(){};
g.h.mp=function(){};
g.h.Gv=function(){return{}};
g.h.isActive=function(){return!0};g.y(M6,g.D);g.h=M6.prototype;g.h.dL=function(){this.Uc=Math.min(3E5,2*this.Uc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.ao(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Uc=5E3};g.y(N6,L6);g.h=N6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.bh(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.qf(this.l),O6(this),g.qf(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new q6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Rc=null);d.Rc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ki):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):P6(this)&&B6(this.g,c)};
g.h.Ku=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)B6(this.g,a[b])}this.M("handlerOpened")};
g.h.Iu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.mp=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Gv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Ju=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),x6(this.g)):this.M("handlerMessage",new vqa(a[0],a[1]))};
g.h.dM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.zd&&b++;0==b&&this.connect(this.u,this.o)};Q6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Q6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
Q6.prototype.u=function(a){a(Error("request timed out"))};var Bqa=(0,g.H)(),V6=null,Z6=Array(50),Y6=-1,$6=!1;g.y(a7,g.P);a7.prototype.Jd=function(){return this.g};
a7.prototype.contains=function(a){return!!v5(this.g,a)};
a7.prototype.get=function(a){return a?w5(this.g,a):null};
a7.prototype.info=function(a){X6(this.C,a)};g.t(c7,g.P);g.h=c7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.iB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Jp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();g.P.prototype.T.call(this)};
g.h.iB=function(){this.za=NaN;this.g=g.Eq(R6(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.aN,this),onError:(0,g.x)(this.ZM,this),ie:(0,g.x)(this.bN,this)})};
g.h.aN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new o5(c))};
g.h.ZM=function(a){this.g=null;a.status&&404==a.status?this.i>=k9.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=k9[this.i],this.za=g.Hp((0,g.x)(this.iB,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.bN=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};
var k9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(e7,a7);g.h=e7.prototype;g.h.start=function(){d7(this)&&this.M("screenChange");!g.ft("yt-remote-lounge-token-expiration")&&f7(this);g.Jp(this.i);this.i=g.Hp((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){d7(this);b7(this,a);g7(this,!1);this.M("screenChange");b(a);a.token||f7(this)};
g.h.remove=function(a,b){var c=d7(this);Dqa(this,a)&&(g7(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.fo=function(a,b,c,d){var e=d7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,g7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.T=function(){g.Jp(this.i);e7.Wa.T.call(this)};
g.h.pD=function(a){d7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}g7(this,!b);b&&X6(this.C,"Missed "+b+" lounge tokens.")};
g.h.oD=function(a){X6(this.C,"Requesting lounge tokens failed: "+a)};g.t(i7,g.P);g.h=i7.prototype;g.h.start=function(){var a=parseInt(g.ft("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?l7(this):(this.o=(0,g.H)()+3E5,g.et("yt-remote-fast-check-period",this.o),this.os())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){h7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!w5(a,d)},this);
k7(this,b)};
g.h.T=function(){g.Jp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.T.call(this)};
g.h.os=function(){g.Jp(this.l);this.l=NaN;this.i&&this.i.abort();var a=m7(this);if(i5(a)){var b=R6(this.u,"/pairing/get_screen_availability");this.i=S6(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.HK,this,a),(0,g.x)(this.GK,this))}else k7(this,{}),l7(this)};
g.h.HK=function(a,b){this.i=null;var c=g.Sb(m7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;k7(this,d);l7(this)}else this.Hb("Changing Screen set during request."),this.os()};
g.h.GK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;l7(this)};
g.h.Hb=function(a){X6("OnlineScreenService",a)};g.y(n7,a7);g.h=n7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.fo=function(a,b,c,d){this.l.contains(a)?this.l.fo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,X6(this.C,a),d(Error(a)))};
g.h.Jd=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.jB=function(){return(0,g.Yd)(this.Jd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.kB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new c7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(o7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.dN=function(a,b,c,d){g.Eq(R6(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new o5(f.screen||{});if(!k.name||q7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);q7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(o7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ie:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);n7.Wa.T.call(this)};
g.h.xD=function(){r7(this);this.M("screenChange");this.i.update()};
n7.prototype.dispose=n7.prototype.dispose;g.y(t7,g.P);g.h=t7.prototype;g.h.wn=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Md=function(a){this.da()||(a&&u7(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){X6(this.P,a)};
g.h.mB=function(){return null};
g.h.Bs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){u7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.Bs("");t7.Wa.T.call(this)};g.y(w7,t7);g.h=w7.prototype;g.h.As=function(a){if(this.g){if(this.g==a)return;u7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Hqa(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.Bs=g.Ja;g.h.T=function(){this.info("disposeInternal");g.Jp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;w7.Wa.T.call(this)};
g.h.GL=function(a,b){if(!this.da())if(b){var c=k5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":v7(this,c.screenId);break;default:u7(this,"Unknown youtube message: "+d)}}else u7(this,"Unable to parse message.")}else u7(this,"No data in message.")};
g.h.Wv=function(a,b,c,d){p7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(u7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Hp((0,g.x)(this.Wv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.mB=function(){return this.g};
g.h.eN=function(a){this.da()||a||(u7(this,"Cast session died."),this.Md())};g.y(x7,t7);g.h=x7.prototype;g.h.As=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.mi=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Jp(this.A);this.o?this.o.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.T=function(){this.g();this.g=g.Ja;g.Jp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;x7.Wa.T.call(this)};
g.h.hN=function(a){this.da()||a||(u7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Md())};
g.h.tq=function(a){this.H=u5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,z7(this));a(b);y7(this)}else this.C=(0,g.x)(function(){g.Jp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,z7(this));a(c);y7(this)},this),this.A=g.Hp((0,g.x)(function(){this.C()},this),100)};
g.h.TD=function(a,b,c){p7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.wn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.tq(b,c)},this),(0,g.x)(function(d){u7(this,"Failed to get DIAL screen: "+d);
this.tq(b,c)},this))};g.y(A7,t7);A7.prototype.stop=function(){this.Md()};
A7.prototype.As=g.Ja;A7.prototype.mi=function(){g.Jp(this.g);this.g=NaN;var a=w5(this.F.Jd(),this.i.label);a?this.wn(a):this.Md(Error("No such screen"))};
A7.prototype.T=function(){g.Jp(this.g);this.g=NaN;A7.Wa.T.call(this)};g.y(B7,g.P);g.h=B7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.qK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Yy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.FI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),yqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.lB,this)),this.l=G7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.M("yt-remote-cast2-availability-change",E7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.mM=function(a,b){D7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)D7("Unsetting old screen status: "+this.g.i.friendlyName),F7(this,null)}if(a&&b){if(!this.g){c=w5(this.i.Jd(),a);if(!c){D7("setConnectedScreenStatus: Unknown screen.");return}var d=C7(this,c);d||(D7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
D7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);F7(this,new A7(this.i,d),!0)}this.g.Bs(b)}else D7("setConnectedScreenStatus: no screen.")};
g.h.nM=function(a){this.da()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Hb("Setting connection data without a session")};
g.h.gN=function(){this.da()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),F7(this,null)):D7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Yy,this),(0,g.x)(this.MK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.lB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],T6);g.qf(this.g);B7.Wa.T.call(this)};
g.h.Hb=function(a){X6("Controller",a)};
g.h.Zy=function(a,b){this.g==a&&(b||F7(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.mK=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),D7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)D7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{D7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:F7(this,
new A7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:F7(this,new x7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:F7(this,new w7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.FI=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return D7("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);F7(this,new x7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.TD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.tq,b))};
g.h.Yy=function(a){if(!this.da()){D7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)D7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),F7(this,new w7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=w5(this.i.Jd(),c.label);d&&p5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(D7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new w7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Zy,this,this.g)),this.g.mi(null));this.g.As(a)}}};
g.h.fN=function(){return this.g?this.g.mB():null};
g.h.MK=function(a){this.da()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&F7(this,null))};
g.h.qK=function(a){D7("Receiver availability updated: "+a);if(!this.da()){var b=E7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;E7(this)!=b&&this.M("yt-remote-cast2-availability-change",E7(this))}};
g.h.lB=function(){this.da()||(this.l=G7(this),D7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",E7(this)))};
B7.prototype.setLaunchParams=B7.prototype.nM;B7.prototype.setConnectedScreenStatus=B7.prototype.mM;B7.prototype.stopSession=B7.prototype.gN;B7.prototype.getCastSession=B7.prototype.fN;B7.prototype.requestSession=B7.prototype.requestSession;B7.prototype.init=B7.prototype.init;B7.prototype.dispose=B7.prototype.dispose;var P7=[];X7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";Y7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
X7.prototype.isAdPlaying=function(){return 1081==this.playerState};
X7.prototype.getDuration=function(){return this.u?this.D+Z7(this):this.D};
X7.prototype.clone=function(){return new X7(c8(this))};g.t(f8,g.P);g.h=f8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,n8(this,"play")):l8(this,"play"),k8(this,1,a8(g8(this))),this.M("remotePlayerChange")):i8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,n8(this,"pause")):l8(this,"pause"),k8(this,2,a8(g8(this))),this.M("remotePlayerChange")):i8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=g8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,n8(this,"seekTo",{newTime:a}))}else l8(this,"seekTo",{newTime:a});k8(this,3,a);this.M("remotePlayerChange")}else i8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,n8(this,"stopVideo")):l8(this,"stopVideo");var a=g8(this);a.index=-1;a.videoId="";Y7(a);j8(this,a);this.M("remotePlayerChange")}else i8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=g8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){X6("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){X6("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);l8(this,"setVolume",e)}c.muted=b;c.volume=a;j8(this,c)}else i8(this,g.Sa(this.setVolume,a,b))};
g.h.lA=function(a,b){if(1==this.g){var c=g8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));l8(this,"setSubtitlesTrack",d);j8(this,c)}else i8(this,g.Sa(this.lA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();l8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=g8(this);d.audioTrackId=c;j8(this,d)}else i8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=g8(this);c=c||0;var m={videoId:a,currentIndex:c};b8(l,a,c);g.Ea(b)&&($7(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));l8(this,"setPlaylist",m);d||j8(this,l)};
g.h.Dn=function(a,b){if(1==this.g){if(a&&b){var c=g8(this);b8(c,a,b);j8(this,c)}l8(this,"previous")}else i8(this,g.Sa(this.Dn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=g8(this);b8(c,a,b);j8(this,c)}l8(this,"next")}else i8(this,g.Sa(this.nextVideo,a,b))};
g.h.hv=function(){1==this.g?l8(this,"dismissAutoplay"):i8(this,this.hv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.T=function(){h8(this);this.o=null;this.u.clear();e8(this,null);g.P.prototype.T.call(this)};
g.h.ot=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.jK=function(a,b){this.M(a,b)};
g.h.jI=function(a){if(!a)this.Gk(null),e8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=g8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)X6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,j8(this,b)}};
g.h.Gk=function(a){X6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),m8(this),this.M("remotePlayerChange")};
g.h.iI=function(a){a?(m8(this),this.M("remotePlayerChange")):this.Gk(null)};
g.h.Ts=function(){l8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.wI=function(){var a=T7();a&&e8(this,a)};
g.h.Hb=function(a){X6("CP",a)};g.t(o8,g.P);g.h=o8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Ma.listId=c);this.Ma.videoId=d;this.Ma.index=k||0;this.Ma.state=3;$7(this.Ma,m);this.o="UNSUPPORTED";p8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,D5())}else p8("Connecting without params"),this.g.connect({},a,D5());Oqa(this)};
g.h.dispose=function(){this.da()||(this.M("beforeDispose"),q8(this,3));g.P.prototype.dispose.call(this)};
g.h.T=function(){r8(this);t8(this);s8(this);g.Jp(this.C);this.C=NaN;g.Jp(this.D);this.D=NaN;this.l=null;g.Nr(this.P);this.P.length=0;this.g.dispose();g.P.prototype.T.call(this);this.o=this.A=this.i=this.Ma=this.g=null};
g.h.iD=function(){this.Nh(2)};
g.h.nI=function(){p8("Channel opened");this.I&&(this.I=!1,s8(this),this.H=g.Hp((0,g.x)(function(){p8("Timing out waiting for a screen.");this.Nh(1)},this),15E3));
pqa(wqa(this.g),this.N)};
g.h.kI=function(){p8("Channel closed");isNaN(this.u)?G5(!0):G5();this.dispose()};
g.h.lI=function(a){G5();isNaN(this.Ij())?(p8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,p8("Channel error: "+a+" with reconnection in "+this.Ij()+" ms"),q8(this,2))};
g.h.mI=function(a){a.params?p8("Received: action="+a.action+", params="+g.Kg(a.params)):p8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=k5(a.params.devices);this.i=(0,g.B)(a,function(c){return new n5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
w8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
w8(this,!1);break;case "remoteConnected":var b=new n5(k5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||eqa(this.i,b);
break;case "remoteDisconnected":b=new n5(k5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":x8(this,a);break;case "nowPlaying":Rqa(this,a);break;case "onStateChange":y8(this,a);break;case "onAdStateChange":Sqa(this,a);break;case "onVolumeChanged":Tqa(this,a);break;case "onSubtitlesTrackChanged":Qqa(this,a);break;case "nowAutoplaying":Uqa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.M("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":Vqa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:p8("Unrecognized action: "+a.action)}};
g.h.aM=function(){if(this.l){var a=this.l;this.l=null;this.Ma.videoId!=a&&u8(this,"getNowPlaying")}};
g.h.YC=function(){var a=3;this.da()||(a=0,isNaN(this.Ij())?P6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Nh=function(a){p8("Disconnecting with "+a);r8(this);this.M("beforeDisconnect",a);1==a&&G5();O6(this.g,a);this.dispose()};
g.h.XC=function(){var a=this.Ma;this.l&&(a=this.Ma.clone(),b8(a,this.l,a.index));return c8(a)};
g.h.oM=function(a){var b=new X7(a);b.videoId&&b.videoId!=this.Ma.videoId&&(this.l=b.videoId,g.Jp(this.C),this.C=g.Hp((0,g.x)(this.aM,this),5E3));var c=[];this.Ma.listId==b.listId&&this.Ma.videoId==b.videoId&&this.Ma.index==b.index||c.push("remoteQueueChange");this.Ma.playerState==b.playerState&&this.Ma.volume==b.volume&&this.Ma.muted==b.muted&&a8(this.Ma)==a8(b)&&g.Kg(this.Ma.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Ma.reset(a);(0,g.A)(c,function(d){this.M(d)},this)};
g.h.Tv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Ij=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.QC=function(){return this.o||"UNSUPPORTED"};
g.h.RC=function(){return this.A||""};
g.h.YM=function(){if(!isNaN(this.Ij())){var a=this.g.i;g.bo(a.g);a.start()}};
g.h.hM=function(a,b){u8(this,a,b);v8(this)};
o8.prototype.subscribe=o8.prototype.subscribe;o8.prototype.unsubscribeByKey=o8.prototype.Kf;o8.prototype.getProxyState=o8.prototype.YC;o8.prototype.disconnect=o8.prototype.Nh;o8.prototype.getPlayerContextData=o8.prototype.XC;o8.prototype.setPlayerContextData=o8.prototype.oM;o8.prototype.getOtherConnectedRemoteId=o8.prototype.Tv;o8.prototype.getReconnectTimeout=o8.prototype.Ij;o8.prototype.getAutoplayMode=o8.prototype.QC;o8.prototype.getAutoplayVideoId=o8.prototype.RC;o8.prototype.reconnect=o8.prototype.YM;
o8.prototype.sendMessage=o8.prototype.hM;g.t(z8,a7);g.h=z8.prototype;g.h.Jd=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.add=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.fo=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Tc.$_ubk(this.i[a]);this.i.length=0;this.Tc=null;a7.prototype.T.call(this)};
g.h.cN=function(){this.M("screenChange")};
g.h.OJ=function(){this.M("onlineScreenChange")};
n7.prototype.$_st=n7.prototype.start;n7.prototype.$_gspc=n7.prototype.dN;n7.prototype.$_gsppc=n7.prototype.kB;n7.prototype.$_c=n7.prototype.contains;n7.prototype.$_g=n7.prototype.get;n7.prototype.$_a=n7.prototype.add;n7.prototype.$_un=n7.prototype.fo;n7.prototype.$_r=n7.prototype.remove;n7.prototype.$_gs=n7.prototype.Jd;n7.prototype.$_gos=n7.prototype.jB;n7.prototype.$_s=n7.prototype.subscribe;n7.prototype.$_ubk=n7.prototype.Kf;var V8=null,U8=!1,A8=null,B8=null,R8=null,F8=[];g.t(W8,g.D);g.h=W8.prototype;
g.h.T=function(){g.D.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Vy,this);this.g.unsubscribe("remotePlayerChange",this.Ik,this);this.g.unsubscribe("remoteQueueChange",this.xn,this);this.g.unsubscribe("autoplayUpNext",this.zy,this);this.g.unsubscribe("previousNextChange",this.Sy,this);this.g.unsubscribe("nowAutoplaying",this.Oy,this);this.g.unsubscribe("autoplayDismissed",this.yy,this);this.g=this.u=null};
g.h.wx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if($8(this)){if(!g8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==g8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Rj(c[0],c[1]);break;case "control_subtitles_set_track":a9(this,c[0]);break;case "control_set_audio_track":c=c[0],$8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();b9(this,0==c?void 0:c);break;case "control_seek":b9(this,c[0]);break;case "control_subtitles_set_track":a9(this,c[0]);break;case "control_set_audio_track":c=c[0],$8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.hI=function(a){this.I.eD(a)};
g.h.IM=function(a){this.wx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.yA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||a9(this,a)};
g.h.Ky=function(a){if($8(this)){this.g.unsubscribe("remotePlayerChange",this.Ik,this);var b=Math.round(a.volume);a=!!a.muted;var c=g8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Ik,this)}};
g.h.jJ=function(){g.Yb(this.C)||c9(this,this.C);this.D=!1};
g.h.Vy=function(a,b){this.A.stop();2==b&&this.xA()};
g.h.Ik=function(){if($8(this)){this.o.stop();var a=g8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Lm=1;break;case 1082:case 1083:this.u.Lm=0;break;default:this.u.Lm=-1}switch(a.playerState){case 1081:case 1:Y8(this,new g.gC(8));this.wA();break;case 1085:case 3:Y8(this,new g.gC(9));break;case 1083:case 0:Y8(this,new g.gC(2));this.H.stop();X8(this,this.i.getVideoData().lengthSeconds);break;case 1084:Y8(this,new g.gC(4));break;case 2:Y8(this,new g.gC(4));X8(this,a8(a));
break;case -1:Y8(this,new g.gC(64));break;case -1E3:Y8(this,new g.gC(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=g8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,c9(this,a));a=g8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.WA()}else Z8(this)};
g.h.Sy=function(){this.i.M("mdxpreviousnextchange")};
g.h.xn=function(){$8(this)||Z8(this)};
g.h.lC=function(){this.g.hv()};
g.h.zy=function(a){a&&(a=g.Eq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.oL,this)}))&&(this.N=(0,g.x)(a.abort,a))};
g.h.oL=function(a,b){var c=new g.UA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.Oy=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.yy=function(){this.i.M("mdxautoplaycanceled")};
g.h.GF=function(a,b){-1==g8(this.g).playerState?b9(this,a):b&&this.g.seekTo(a)};
g.h.WA=function(){if($8(this)){var a=g8(this.g);this.l.La(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Ky)}};
g.h.wA=function(){this.o.stop();if(!this.g.da()){var a=g8(this.g);1==a.playerState&&Y8(this,new g.gC(8));X8(this,a8(a));this.o.start()}};
g.h.xA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(e9,g.W);e9.prototype.o=function(){m5("mdx-privacy-popup-cancel");this.l.hide()};
e9.prototype.A=function(){m5("mdx-privacy-popup-confirm");this.l.hide()};g.t(g9,g.W);g9.prototype.u=function(a){f9(this,a.state)};g.t(h9,g.xT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.yT(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.re=function(a){return"cast-selector-receiver"==a?"Reparto...":this.F[a].name};
h9.prototype.Ic=function(a){g.xT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.sK);g.h=i9.prototype;
g.h.create=function(){$qa(g.Ey(g.X(this.player)));this.o.push(g.Op("yt-remote-before-disconnect",this.eI,this));this.o.push(g.Op("yt-remote-connection-change",this.rK,this));this.o.push(g.Op("yt-remote-receiver-availability-change",this.Ty,this));this.o.push(g.Op("yt-remote-auto-connect",this.pK,this));this.o.push(g.Op("yt-remote-receiver-resumed",this.oK,this));this.o.push(g.Op("mdx-privacy-popup-confirm",this.QL,this));this.o.push(g.Op("mdx-privacy-popup-cancel",this.PL,this));this.Ty()};
g.h.load=function(){this.player.cancelPlayback();g.sK.prototype.load.call(this);this.u=new W8(this,this.player,this.g);var a=(a=T8())?a.currentTime:0;var b=Q8()?new f8(L8(),void 0):null;0==a&&b&&(a=a8(g8(b)));0!=a&&this.qd(a);d9(this,this.pk,this.pk);g.xX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.sK.prototype.unload.call(this);g.xX(this.player.app,5)};
g.h.T=function(){g.Pp(this.o);g.sK.prototype.T.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.wx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Lm};
g.h.aD=function(){return this.loaded?this.u.suggestion:null};
g.h.Ke=function(){return this.g?g8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?g8(this.g).hasNext:!1};
g.h.qd=function(a,b){this.H=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=g8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ac():!a.isAdPlaying()&&this.player.ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+Z7(a):a.l,isAtLiveHead:1>=(a.u?a.i+Z7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+Z7(a):a.i,seekableStart:0<a.o?a.o+
Z7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Dn=function(){this.g&&this.g.Dn()};
g.h.eI=function(a){1==a&&(this.C=this.g?g8(this.g):null)};
g.h.rK=function(){var a=Q8()?new f8(L8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,a8(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ty=function(){this.A=[this.i].concat(ara());var a=M8()||this.i;j9(this,a);this.player.la("onMdxReceiversChange")};
g.h.pK=function(){var a=M8();j9(this,a)};
g.h.oK=function(){this.l=M8()};
g.h.QL=function(){this.D=!0;U8=!1;V8&&O8(V8,1);V8=null};
g.h.PL=function(){this.D=!1;j9(this,this.i);this.l=this.i;U8=!1;V8=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?V7():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&V7(),!0):!1}};
g.h.Ts=function(){this.g.Ts()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.OU.remote=i9;})(_yt_player);
