(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var k;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){if(!(a instanceof Array)){a=ba(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ea(){}ea.prototype.toJSON=function(){return{}};
function p(a){a.__shady||(a.__shady=new ea);return a.__shady}function q(a){return a&&a.__shady};var r=window.ShadyDOM||{};r.Gb=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var fa=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");r.i=!!(fa&&fa.configurable&&fa.get);r.ha=r.force||!r.Gb;r.w=r.noPatch||!1;r.Ea=r.preferPerformance;var ha=navigator.userAgent.match("Trident");r.Ia=ha;function u(a){return(a=q(a))&&void 0!==a.firstChild}function v(a){return"ShadyRoot"===a.ib}function ia(a){return(a=(a=q(a))&&a.root)&&a.pa()}
var w=Element.prototype,ja=w.matches||w.matchesSelector||w.mozMatchesSelector||w.msMatchesSelector||w.oMatchesSelector||w.webkitMatchesSelector,ka=document.createTextNode(""),la=0,ma=[];(new MutationObserver(function(){for(;ma.length;)try{ma.shift()()}catch(a){throw ka.textContent=la++,a;}})).observe(ka,{characterData:!0});function na(a){ma.push(a);ka.textContent=la++}var oa=!!document.contains;function pa(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function qa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=ba(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}function ra(a){var b=[];for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)b.push(a);return b}
function sa(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b.push(a);return b}function x(a,b,c,d){c=void 0===c?"":c;for(var e in b){var f=b[e];if(!(d&&0<=d.indexOf(e))){f.configurable=!0;var g=c+e;if(f.value)a[g]=f.value;else try{Object.defineProperty(a,g,f)}catch(h){}}}}function y(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};var z=[],ta;function ua(a){ta||(ta=!0,na(va));z.push(a)}function va(){ta=!1;for(var a=!!z.length;z.length;)z.shift()();return a}va.list=z;function wa(){this.R=!1;this.addedNodes=[];this.removedNodes=[];this.V=new Set}function xa(a){a.R||(a.R=!0,na(function(){a.flush()}))}wa.prototype.flush=function(){if(this.R){this.R=!1;var a=this.takeRecords();a.length&&this.V.forEach(function(b){b(a)})}};wa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function ya(a,b){var c=p(a);c.J||(c.J=new wa);c.J.V.add(b);var d=c.J;return{Pa:b,mb:d,lb:a,takeRecords:function(){return d.takeRecords()}}}function za(a){var b=a&&a.mb;b&&(b.V["delete"](a.Pa),b.V.size||(p(a.lb).J=null))}
function Aa(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=Array.from(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ba=/[&\u00A0"]/g,Ca=/[&\u00A0<>]/g;function Da(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Ea(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Fa=Ea("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Ga=Ea("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ha(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var l=a,m=b;switch(h.nodeType){case Node.ELEMENT_NODE:l=h.localName;for(var n="<"+l,t=h.attributes,B=0,Ja;Ja=t[B];B++)n+=" "+Ja.name+'="'+Ja.value.replace(Ba,Da)+'"';n+=">";h=Fa[l]?n:n+Ha(h,m)+"</"+l+">";break a;case Node.TEXT_NODE:h=h.data;h=l&&Ga[l.localName]?h:h.replace(Ca,Da);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var Ia=r.i,Ka={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},La={};function Ma(a){La[a]=function(b){return b["__shady_native_"+a]}}function A(a,b){x(a,b,"__shady_native_");for(var c in b)Ma(c)}function C(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Ka[d]||(Ka[d]=e.value):Ma(d))}}
var D=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),E=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Na=document.implementation.createHTMLDocument("inert");function Oa(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Pa=["firstElementChild","lastElementChild","children","childElementCount"],Qa=["querySelector","querySelectorAll"];
function Ra(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?C(window.EventTarget.prototype,a):(C(Node.prototype,a),C(Window.prototype,a));Ia?C(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):A(Node.prototype,{parentNode:{get:function(){D.currentNode=this;return D.parentNode()}},firstChild:{get:function(){D.currentNode=this;return D.firstChild()}},lastChild:{get:function(){D.currentNode=
this;return D.lastChild()}},previousSibling:{get:function(){D.currentNode=this;return D.previousSibling()}},nextSibling:{get:function(){D.currentNode=this;return D.nextSibling()}},childNodes:{get:function(){var b=[];D.currentNode=this;for(var c=D.firstChild();c;)b.push(c),c=D.nextSibling();return b}},parentElement:{get:function(){E.currentNode=this;return E.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Oa(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});C(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
C(HTMLElement.prototype,["parentElement","contains"]);a={firstElementChild:{get:function(){E.currentNode=this;return E.firstChild()}},lastElementChild:{get:function(){E.currentNode=this;return E.lastChild()}},children:{get:function(){var b=[];E.currentNode=this;for(var c=E.firstChild();c;)b.push(c),c=E.nextSibling();return qa(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Ia?(C(Element.prototype,Pa),C(Element.prototype,["previousElementSibling","nextElementSibling",
"innerHTML","className"]),C(HTMLElement.prototype,["children","innerHTML","className"])):(A(Element.prototype,a),A(Element.prototype,{previousElementSibling:{get:function(){E.currentNode=this;return E.previousSibling()}},nextElementSibling:{get:function(){E.currentNode=this;return E.nextSibling()}},innerHTML:{get:function(){return Ha(this,ra)},set:function(b){var c="template"===this.localName?this.content:this;Oa(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Na.namespaceURI?
Na.createElementNS(this.namespaceURI,d):Na.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}},className:{get:function(){return this.getAttribute("class")||""},set:function(b){this.setAttribute("class",b)}}}));C(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));C(Element.prototype,Qa);C(HTMLElement.prototype,["focus","blur"]);window.HTMLTemplateElement&&
C(window.HTMLTemplateElement.prototype,["innerHTML"]);Ia?C(DocumentFragment.prototype,Pa):A(DocumentFragment.prototype,a);C(DocumentFragment.prototype,Qa);Ia?(C(Document.prototype,Pa),C(Document.prototype,["activeElement"])):A(Document.prototype,a);C(Document.prototype,["importNode","getElementById"]);C(Document.prototype,Qa)};var Sa=y({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get shadowRoot(){return this.__shady_shadowRoot}}),Ta=y({get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=
a},get innerHTML(){return this.__shady_innerHTML},set innerHTML(a){return this.__shady_innerHTML=a}}),Ua=y({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}});function Va(a){for(var b in a){var c=a[b];c&&(c.enumerable=!1)}}Va(Sa);Va(Ta);Va(Ua);var Wa=r.i||r.w,Xa=Wa?function(){}:function(a){var b=p(a);b.La||(b.La=!0,x(a,Ua))},Ya=Wa?function(){}:function(a){var b=p(a);b.Ka||(b.Ka=!0,x(a,Sa),window.customElements&&!r.w||x(a,Ta))};var Za="__eventWrappers"+Date.now(),$a=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),ab=function(){function a(){}var b=!1,c={get capture(){b=!0}};window.addEventListener("test",a,c);window.removeEventListener("test",a,c);return b}();function bb(a){if(a&&"object"===typeof a){var b=!!a.capture;var c=!!a.once;var d=!!a.passive;var e=a.B}else b=!!a,d=c=!1;return{Fa:e,capture:b,once:c,passive:d,Da:ab?a:b}}
var cb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,
drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},db={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};function eb(a){return a instanceof Node?a.__shady_getRootNode():a}
function fb(a,b){var c=[],d=a;for(a=eb(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function gb(a){a.__composedPath||(a.__composedPath=fb(a.target,!0));return a.__composedPath}function hb(a,b){if(!v)return a;a=fb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=eb(d),f!==e&&(g=a.indexOf(f),e=f),!v(f)||-1<g)return d}
function ib(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var jb={focus:!0,blur:!0};function kb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}function lb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!kb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function mb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];lb(a,d,"capture");if(a.Y)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=q(d);f=f&&f.root;if(0===c||f&&f===e)if(lb(a,d,"bubble"),d!==window&&(e=d.__shady_getRootNode()),a.Y)break}}
function nb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],l=h.type,m=h.capture,n=h.once,t=h.passive;if(b===h.node&&c===l&&d===m&&e===n&&f===t)return g}return-1}function ob(a){va();return this.__shady_native_dispatchEvent(a)}
function pb(a,b,c){var d=bb(c),e=d.capture,f=d.once,g=d.passive,h=d.Fa;d=d.Da;if(b){var l=typeof b;if("function"===l||"object"===l)if("object"!==l||b.handleEvent&&"function"===typeof b.handleEvent){if(db[a])return this.__shady_native_addEventListener(a,b,d);var m=h||this;if(h=b[Za]){if(-1<nb(h,m,a,e,f,g))return}else b[Za]=[];h=function(n){f&&this.__shady_removeEventListener(a,b,c);n.__target||qb(n);if(m!==this){var t=Object.getOwnPropertyDescriptor(n,"currentTarget");Object.defineProperty(n,"currentTarget",
{get:function(){return m},configurable:!0})}n.__previousCurrentTarget=n.currentTarget;if(!v(m)&&"slot"!==m.localName||-1!=n.composedPath().indexOf(m))if(n.composed||-1<n.composedPath().indexOf(m))if(kb(n)&&n.target===n.relatedTarget)n.eventPhase===Event.BUBBLING_PHASE&&n.stopImmediatePropagation();else if(n.eventPhase===Event.CAPTURING_PHASE||n.bubbles||n.target===m||m instanceof Window){var B="function"===l?b.call(m,n):b.handleEvent&&b.handleEvent(n);m!==this&&(t?(Object.defineProperty(n,"currentTarget",
t),t=null):delete n.currentTarget);return B}};b[Za].push({node:m,type:a,capture:e,once:f,passive:g,Ub:h});jb[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(h)):this.__shady_native_addEventListener(a,h,d)}}}
function rb(a,b,c){if(b){var d=bb(c);c=d.capture;var e=d.once,f=d.passive,g=d.Fa;d=d.Da;if(db[a])return this.__shady_native_removeEventListener(a,b,d);var h=g||this;g=void 0;var l=null;try{l=b[Za]}catch(m){}l&&(e=nb(l,h,a,c,e,f),-1<e&&(g=l.splice(e,1)[0].Ub,l.length||(b[Za]=void 0)));this.__shady_native_removeEventListener(a,g||b,d);g&&jb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][c?"capture":"bubble"],b=a.indexOf(g),-1<b&&a.splice(b,1))}}
function sb(){for(var a in jb)window.__shady_native_addEventListener(a,function(b){b.__target||(qb(b),mb(b))},!0)}
var tb=y({get composed(){void 0===this.__composed&&($a?this.__composed="focusin"===this.type||"focusout"===this.type||$a(this):!1!==this.isTrusted&&(this.__composed=cb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=fb(this.__target,this.composed));return this.__composedPath},get target(){return hb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=fb(this.__relatedTarget,!0));return hb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.Y=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.Y=this.__immediatePropagationStopped=!0}});
function qb(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(r.i){var b=Object.getPrototypeOf(a);if(!Object.hasOwnProperty(b,"__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;x(c,tb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else x(a,tb)}var ub=ib(Event),vb=ib(CustomEvent),wb=ib(MouseEvent);
function xb(){if(!$a&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}var yb=Object.getOwnPropertyNames(Document.prototype).filter(function(a){return"on"===a.substring(0,2)});function zb(a,b){return{index:a,K:[],U:b}}
function Ab(a,b,c,d){var e=0,f=0,g=0,h=0,l=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<l;g++)if(a[g]!==c[g])break a;g=l}if(b==a.length&&d==c.length){h=a.length;for(var m=c.length,n=0;n<l-g&&Bb(a[--h],c[--m]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=zb(e,0);f<d;)b.K.push(c[f++]);return[b]}if(f==d)return[zb(e,b-e)];l=e;g=f;d=d-g+1;h=b-l+1;b=Array(d);for(m=0;m<d;m++)b[m]=Array(h),b[m][0]=m;for(m=0;m<h;m++)b[0][m]=m;for(m=1;m<d;m++)for(n=1;n<h;n++)if(a[l+n-1]===c[g+m-1])b[m][n]=
b[m-1][n-1];else{var t=b[m-1][n]+1,B=b[m][n-1]+1;b[m][n]=t<B?t:B}l=b.length-1;g=b[0].length-1;d=b[l][g];for(a=[];0<l||0<g;)0==l?(a.push(2),g--):0==g?(a.push(3),l--):(h=b[l-1][g-1],m=b[l-1][g],n=b[l][g-1],t=m<n?m<h?m:h:n<h?n:h,t==h?(h==d?a.push(0):(a.push(1),d=h),l--,g--):t==m?(a.push(3),l--,d=m):(a.push(2),g--,d=n));a.reverse();b=void 0;l=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(l.push(b),b=void 0);e++;f++;break;case 1:b||(b=zb(e,0));b.U++;e++;b.K.push(c[f]);f++;break;case 2:b||(b=zb(e,0));
b.U++;e++;break;case 3:b||(b=zb(e,0)),b.K.push(c[f]),f++}b&&l.push(b);return l}function Bb(a,b){return a===b};function Cb(a,b,c,d){Xa(a);d=d||null;var e=p(a),f=d?p(d):null;e.previousSibling=d?f.previousSibling:b.__shady_lastChild;if(f=q(e.previousSibling))f.nextSibling=a;if(f=q(e.nextSibling=d))f.previousSibling=a;e.parentNode=b;d?d===c.firstChild&&(c.firstChild=a):(c.lastChild=a,c.firstChild||(c.firstChild=a));c.childNodes=null}
function Db(a,b,c){Ya(b);var d=p(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)Cb(a,b,d,c);else Cb(a,b,d,c)}
function Eb(a,b){var c=p(a);b=p(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(p(a).nextSibling=d);d&&(p(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Fb(a,b){var c=p(a);if(b||void 0===c.firstChild){c.childNodes=null;var d=c.firstChild=a.__shady_native_firstChild;c.lastChild=a.__shady_native_lastChild;Ya(a);c=d;for(d=void 0;c;c=c.__shady_native_nextSibling){var e=p(c);e.parentNode=b||a;e.nextSibling=c.__shady_native_nextSibling;e.previousSibling=d||null;d=c;Xa(c)}}};var Gb=null;function F(){Gb||(Gb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Gb||null}function Hb(a,b,c){var d=F();return d&&"class"===b?(d.setElementClass(a,c),!0):!1}function Ib(a,b){var c=F();c&&c.unscopeNode(a,b)}function Jb(a,b){var c=F();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)c=c&&Jb(a,b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}
function Kb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=F();return b?b.currentScopeForNode(a):""}function Lb(a,b){if(a)for(a.nodeType===Node.ELEMENT_NODE&&b(a),a=a.__shady_firstChild;a;a=a.__shady_nextSibling)a.nodeType===Node.ELEMENT_NODE&&Lb(a,b)};var Mb=window.document,Nb=r.Ea,Ob=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Pb=Ob&&Ob.get;function Qb(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function Rb(a){var b=q(a);if(b&&void 0!==b.X)for(b=a.__shady_firstChild;b;b=b.__shady_nextSibling)Rb(b);if(a=q(a))a.X=void 0}function Sb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=q(a))&&b.G)&&b.length?b[0]:Sb(a.__shady_nextSibling));return b}
function Tb(a,b,c){if(a=(a=q(a))&&a.J)b&&(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE?a.addedNodes.push.apply(a.addedNodes,ca(b.childNodes)):a.addedNodes.push(b)),c&&a.removedNodes.push(c),xa(a)}
var Ub=y({get parentNode(){var a=q(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=q(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=q(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=q(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=q(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(u(this)){var a=q(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=q(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(Pb&&Pb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(oa){if(a.__shady_native_contains(this))return!0}else if(a.documentElement&&a.documentElement.__shady_native_contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(v(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(u(this)){for(var a=[],b=this.__shady_firstChild;b;b=b.__shady_nextSibling)b.nodeType!==Node.COMMENT_NODE&&a.push(b.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===
typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!u(this)&&r.i){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Qb(this);this.__shady_native_textContent=a}else Qb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Mb&&a.ownerDocument!==Mb)return this.__shady_native_insertBefore(a,
b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(b){var c=q(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;Tb(this,a);var d=[],e=(c=G(this))?c.host.localName:Kb(this),f=a.__shady_parentNode;if(f){var g=Kb(a);var h=!!c||!G(a)||
Nb&&void 0!==this.__noInsertionPoint;f.__shady_removeChild(a,h)}f=!0;var l=(!Nb||void 0===a.__noInsertionPoint&&void 0===this.__noInsertionPoint)&&!Jb(a,e),m=c&&!a.__noInsertionPoint&&(!Nb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(m||l)l&&(g=g||Kb(a)),Lb(a,function(n){m&&"slot"===n.localName&&d.push(n);if(l){var t=g;F()&&(t&&Ib(n,t),(t=F())&&t.scopeNode(n,e))}});d.length&&(c.la(d),c.l());u(this)&&(Db(a,this,b),c=q(this),ia(this)?(c.root.l(),f=!1):c.root&&(f=!1));f?(c=v(this)?this.host:this,b?
(b=Sb(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&this.ownerDocument.adoptNode(a);return a},appendChild:function(a){if(this!=a||!v(a))return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Mb)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);Tb(this,null,a);var c=G(a),d=c&&c.pb(a),e=q(this);
if(u(this)&&(Eb(a,this),ia(this))){e.root.l();var f=!0}if(F()&&!b&&c&&a.nodeType!==Node.TEXT_NODE){var g=Kb(a);Lb(a,function(h){Ib(h,g)})}Rb(a);c&&((b=this&&"slot"===this.localName)&&(f=!0),(d||b)&&c.l());f||(f=v(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);
var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_firstChild;for(var c;a;a=a.__shady_nextSibling)c=a.__shady_cloneNode(!0),b.__shady_appendChild(c)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=p(this),c=b.X;void 0===c&&(v(this)?(c=this,b.X=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.X=c)));return c}},contains:function(a){return pa(this,a)}});function Vb(a,b,c){var d=[];Wb(a,b,c,d);return d}function Wb(a,b,c,d){for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling){var e;if(e=a.nodeType===Node.ELEMENT_NODE){e=a;var f=b,g=c,h=d,l=f(e);l&&h.push(e);g&&g(l)?e=l:(Wb(e,f,g,h),e=void 0)}if(e)break}}
var H=y({get firstElementChild(){var a=q(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=q(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return u(this)?qa(Array.prototype.filter.call(sa(this),
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),Xb=y({querySelector:function(a){return Vb(this,function(b){return ja.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return b.filter(function(d){return d.__shady_getRootNode()==c})}return Vb(this,function(d){return ja.call(d,
a)})}}),Yb=r.Ea&&!r.w?Object.assign({},H):H;Object.assign(H,Xb);var Zb=y({getElementById:function(a){return""===a?null:Vb(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var $b=y({get activeElement(){var a=r.i?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!v(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=G(a);b&&b!==this;)a=b.host,b=G(a);return this===document?b?null:a:b===this?a:null}});var ac=document.implementation.createHTMLDocument("inert"),bc=y({get innerHTML(){return u(this)?Ha("template"===this.localName?this.content:this,sa):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{Qb(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==ac.namespaceURI?ac.createElementNS(this.namespaceURI,b):ac.createElement(b);for(r.i?b.__shady_native_innerHTML=a:b.innerHTML=a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var cc=y({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.B=c.B||this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.B=c.B||this;this.host.__shady_removeEventListener(a,b,c)}});function dc(a,b){x(a,cc,b);x(a,$b,b);x(a,bc,b);x(a,H,b);r.w&&!b?(x(a,Ub,b),x(a,Zb,b)):r.i||(x(a,Ua),x(a,Sa),x(a,Ta))};var ec={},I=r.deferConnectionCallbacks&&"loading"===document.readyState,fc;function gc(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}function hc(a,b,c){if(a!==ec)throw new TypeError("Illegal constructor");this.a=null;this.ra(b,c)}k=hc.prototype;
k.ra=function(a,b){this.ib="ShadyRoot";this.host=a;this.mode=b&&b.mode;Fb(this.host);a=p(this.host);a.root=this;a.Mb="closed"!==this.mode?this:null;a=p(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;if(r.preferPerformance)for(;a=this.host.__shady_native_firstChild;)this.host.__shady_native_removeChild(a);else this.l()};k.l=function(){var a=this;this.D||(this.D=!0,ua(function(){return a.P()}))};k.cb=function(){for(var a,b=this;b;)b.D&&(a=b),b=b.bb();return a};
k.bb=function(){var a=this.host.__shady_getRootNode();if(v(a)){var b=q(this.host);if(b&&0<b.O)return a}};k.P=function(){var a=this.D&&this.cb();a&&a._renderSelf()};k.Ya=function(){!this.qa&&this.D&&this.P()};
k._renderSelf=function(){var a=I;I=!0;this.D=!1;this.a&&(this.Ta(),this.Ra());if(!r.preferPerformance&&!this.qa)for(var b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling){var c=q(b);b.__shady_native_parentNode!==this.host||"slot"!==b.localName&&c.assignedSlot||this.host.__shady_native_removeChild(b)}this.qa=!0;I=a;fc&&fc()};
k.Ta=function(){this.T();for(var a=0,b;a<this.a.length;a++)b=this.a[a],this.Qa(b);for(a=this.host.__shady_firstChild;a;a=a.__shady_nextSibling)this.na(a);for(a=0;a<this.a.length;a++){b=this.a[a];var c=q(b);if(!c.assignedNodes.length)for(var d=b.__shady_firstChild;d;d=d.__shady_nextSibling)this.na(d,b);(d=(d=q(b.__shady_parentNode))&&d.root)&&(d.pa()||d.D)&&d._renderSelf();this.ka(c.G,c.assignedNodes);if(d=c.va){for(var e=0;e<d.length;e++)q(d[e]).ca=null;c.va=null;d.length>c.assignedNodes.length&&
(c.ga=!0)}c.ga&&(c.ga=!1,this.oa(b))}};k.na=function(a,b){var c=p(a),d=c.ca;c.ca=null;b||(b=(b=this.b[a.__shady_slot||"__catchall"])&&b[0]);b?(p(b).assignedNodes.push(a),c.assignedSlot=b):c.assignedSlot=void 0;d!==c.assignedSlot&&c.assignedSlot&&(p(c.assignedSlot).ga=!0)};k.Qa=function(a){var b=q(a),c=b.assignedNodes;b.assignedNodes=[];b.G=[];if(b.va=c)for(b=0;b<c.length;b++){var d=q(c[b]);d.ca=d.assignedSlot;d.assignedSlot===a&&(d.assignedSlot=null)}};
k.ka=function(a,b){for(var c=0,d=void 0;c<b.length&&(d=b[c]);c++)if("slot"==d.localName){var e=q(d).assignedNodes;e&&e.length&&this.ka(a,e)}else a.push(b[c])};k.oa=function(a){a.__shady_native_dispatchEvent(new Event("slotchange"));a=q(a);a.assignedSlot&&this.oa(a.assignedSlot)};k.Ra=function(){for(var a=this.a,b=[],c=0;c<a.length;c++){var d=a[c].__shady_parentNode,e=q(d);e&&e.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this.Ab(c===this?this.host:c,this.Sa(c))};
k.Sa=function(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)if(this.fb(a))for(var c=q(a).G,d=0;d<c.length;d++)b.push(c[d]);else b.push(a);return b};k.fb=function(a){return"slot"==a.localName};
k.Ab=function(a,b){for(var c=ra(a),d=Ab(b,b.length,c,c.length),e=0,f=0,g=void 0;e<d.length&&(g=d[e]);e++){for(var h=0,l=void 0;h<g.K.length&&(l=g.K[h]);h++)l.__shady_native_parentNode===a&&a.__shady_native_removeChild(l),c.splice(g.index+f,1);f-=g.U}e=0;for(f=void 0;e<d.length&&(f=d[e]);e++)for(g=c[f.index],h=f.index;h<f.index+f.U;h++)l=b[h],a.__shady_native_insertBefore(l,g),c.splice(h,0,l)};k.Xa=function(){this.v=this.v||[];this.a=this.a||[];this.b=this.b||{}};
k.la=function(a){this.Xa();this.v.push.apply(this.v,ca(a))};k.T=function(){this.v&&this.v.length&&(this.jb(this.v),this.v=[])};k.jb=function(a){for(var b,c=0;c<a.length;c++){var d=a[c];Fb(d);var e=d.__shady_parentNode;Fb(e);e=q(e);e.O=(e.O||0)+1;e=this.ta(d);this.b[e]?(b=b||{},b[e]=!0,this.b[e].push(d)):this.b[e]=[d];this.a.push(d)}if(b)for(var f in b)this.b[f]=this.xa(this.b[f])};k.ta=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.Ma=b};
k.xa=function(a){return a.sort(function(b,c){b=gc(b);for(var d=gc(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=sa(c.__shady_parentNode),b.indexOf(c)-b.indexOf(f)}})};k.pb=function(a){if(this.a){this.T();var b=this.b,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e];if(pa(a,f)){d.splice(e,1);var g=this.a.indexOf(f);0<=g&&(this.a.splice(g,1),(g=q(f.__shady_parentNode))&&g.O&&g.O--);e--;this.qb(f);g=!0}}return g}};
k.Bb=function(a){if(this.a){this.T();var b=a.Ma,c=this.ta(a);if(c!==b){b=this.b[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this.b[c]||(this.b[c]=[]);b.push(a);1<b.length&&(this.b[c]=this.xa(b))}}};k.qb=function(a){a=q(a);var b=a.G;if(b)for(var c=0;c<b.length;c++){var d=b[c],e=d.__shady_native_parentNode;e&&e.__shady_native_removeChild(d)}a.G=[];a.assignedNodes=[]};k.pa=function(){this.T();return!(!this.a||!this.a.length)};
(function(a){a.__proto__=DocumentFragment.prototype;dc(a,"__shady_");dc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(hc.prototype);
if(window.customElements&&r.ha&&!r.preferPerformance){var ic=new Map;fc=function(){var a=[];ic.forEach(function(d,e){a.push([e,d])});ic.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.__shadydom_connectedCallback():c.__shadydom_disconnectedCallback()}};I&&document.addEventListener("readystatechange",function(){I=!1;fc()},{once:!0});var jc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.__shadydom_connectedCallback=function(){I?ic.set(this,
!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.__shadydom_disconnectedCallback=function(){I?this.isConnected||ic.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},kc=window.customElements.define,define=function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;kc.call(window.customElements,a,jc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d};window.customElements.define=define;Object.defineProperty(window.CustomElementRegistry.prototype,
"define",{value:define,configurable:!0})}function G(a){a=a.__shady_getRootNode();if(v(a))return a};function J(a){this.node=a}k=J.prototype;k.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};k.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};k.appendChild=function(a){return this.node.__shady_appendChild(a)};k.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};k.removeChild=function(a){return this.node.__shady_removeChild(a)};k.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
k.cloneNode=function(a){return this.node.__shady_cloneNode(a)};k.getRootNode=function(a){return this.node.__shady_getRootNode(a)};k.contains=function(a){return this.node.__shady_contains(a)};k.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};k.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};k.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};k.hasAttribute=function(a){return this.node.__shady_native_hasAttribute(a)};k.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};
k.attachShadow=function(a){return this.node.__shady_attachShadow(a)};k.focus=function(){this.node.__shady_native_focus()};k.blur=function(){this.node.__shady_blur()};k.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};k.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};k.querySelector=function(a){return this.node.__shady_querySelector(a)};
k.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};k.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
da.Object.defineProperties(J.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(v(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(v(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}},className:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_className},set:function(a){return this.node.__shady_className=
a}}});yb.forEach(function(a){Object.defineProperty(J.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})});var lc=new WeakMap;function mc(a){if(v(a)||a instanceof J)return a;var b=lc.get(a);b||(b=new J(a),lc.set(a,b));return b};var nc=y({dispatchEvent:ob,addEventListener:pb,removeEventListener:rb});var oc=y({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&a.P();return(a=q(this))&&a.assignedSlot||null}});var pc=window.document;function qc(a,b){"slot"===b?(a=a.__shady_parentNode,ia(a)&&q(a).root.l()):"slot"===a.localName&&"name"===b&&(b=G(a))&&(b.Bb(a),b.l())}
var rc=y({get previousElementSibling(){var a=q(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=q(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get shadowRoot(){var a=q(this);return a&&a.Mb||null},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){this.ownerDocument!==pc?this.__shady_native_setAttribute(a,b):Hb(this,a,b)||(this.__shady_native_setAttribute(a,b),qc(this,a))},removeAttribute:function(a){this.ownerDocument!==pc?this.__shady_native_removeAttribute(a):Hb(this,a,"")?""===this.getAttribute(a)&&this.__shady_native_removeAttribute(a):
(this.__shady_native_removeAttribute(a),qc(this,a))},attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");if(a.shadyUpgradeFragment&&!r.Ia){var b=a.shadyUpgradeFragment;b.__proto__=ShadowRoot.prototype;b.ra(this,a);Fb(b,b);a=b.__noInsertionPoint?null:b.querySelectorAll("slot");b.__noInsertionPoint=void 0;a&&a.length&&(b.la(a),b.l());b.host.__shady_native_appendChild(b)}else b=new hc(ec,this,a);return b}});var sc=y({blur:function(){var a=q(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});yb.forEach(function(a){sc[a]={set:function(b){var c=p(this),d=a.substring(2);c.A||(c.A={});c.A[a]&&this.removeEventListener(d,c.A[a]);this.__shady_addEventListener(d,b);c.A[a]=b},get:function(){var b=q(this);return b&&b.A&&b.A[a]},configurable:!0}});var tc=y({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&v(b)&&b.P();return(b=q(this))?(a&&a.flatten?b.G:b.assignedNodes)||[]:[]}},addEventListener:function(a,b,c){if("slot"!==this.localName||"slotchange"===a)pb.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.B=this;d.__shady_addEventListener(a,b,c)}},removeEventListener:function(a,
b,c){if("slot"!==this.localName||"slotchange"===a)rb.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.B=this;d.__shady_removeEventListener(a,b,c)}}});var uc=window.document,vc=y({importNode:function(a,b){if(a.ownerDocument!==uc||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b)for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b=this.__shady_importNode(a,!0),c.__shady_appendChild(b);return c}});var wc=y({dispatchEvent:ob,addEventListener:pb.bind(window),removeEventListener:rb.bind(window)});var K={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(K.parentElement=Ub.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(K.contains=Ub.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(K.children=H.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(K.innerHTML=bc.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(K.className=rc.className);
var xc={EventTarget:[nc],Node:[Ub,window.EventTarget?null:nc],Text:[oc],Element:[rc,H,oc,!r.i||"innerHTML"in Element.prototype?bc:null,window.HTMLSlotElement?null:tc],HTMLElement:[sc,K],HTMLSlotElement:[tc],DocumentFragment:[Yb,Zb],Document:[vc,Yb,Zb,$b],Window:[wc]},yc=r.i?null:["innerHTML","textContent"];function zc(a){var b=a?null:yc,c={},d;for(d in xc)c.M=window[d]&&window[d].prototype,xc[d].forEach(function(e){return function(f){return e.M&&f&&x(e.M,f,a,b)}}(c)),c={M:c.M}};if(r.ha){var ShadyDOM={inUse:r.ha,patch:function(a){Ya(a);Xa(a);return a},isShadyRoot:v,enqueue:ua,flush:va,flushInitial:function(a){a.Ya()},settings:r,filterMutations:Aa,observeChildren:ya,unobserveChildren:za,deferConnectionCallbacks:r.deferConnectionCallbacks,preferPerformance:r.preferPerformance,handlesDynamicScoping:!0,wrap:r.w?mc:function(a){return a},Wrapper:J,composedPath:gb,noPatch:r.w,nativeMethods:Ka,nativeTree:La};window.ShadyDOM=ShadyDOM;Ra();zc("__shady_");Object.defineProperty(document,
"_activeElement",$b.activeElement);x(Window.prototype,wc,"__shady_");r.w||(zc(),xb());sb();window.Event=ub;window.CustomEvent=vb;window.MouseEvent=wb;window.ShadowRoot=hc};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Ac(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Bc(a){a=a.replace(Cc,"").replace(Dc,"");var b=Ec,c=a,d=new Ac;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,l=h.rules[h.rules.length-1]||null;e=new Ac;e.start=f+1;e.parent=h;e.previous=l;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function Ec(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=_expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(c),c=c.replace(Fc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=4:c.match(Gc)&&(a.type=7,a.keyframesName=a.selector.split(Fc).pop()):a.type=0===c.indexOf("--")?
1E3:1);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Ec(f,b);return a}function _expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function Hc(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules;if(e&&!_hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(e))for(var f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=Hc(h,b,d);else b?b=a.cssText:(b=a.cssText,b=b.replace(Ic,"").replace(Jc,""),b=b.replace(Kc,"").replace(Lc,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
function _hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){a=a[0];return!!a&&!!a.selector&&0===a.selector.indexOf("--")}var Cc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Dc=/@import[^;]*;/gim,Ic=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Jc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Kc=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Lc=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Gc=/^@[^\s]*keyframes/,Fc=/\s+/g;var L=!(window.ShadyDOM&&window.ShadyDOM.inUse),Mc;function Nc(a){Mc=a&&a.shimcssproperties?!1:L||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var Oc;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(Oc=window.ShadyCSS.cssBuild);var M=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?Mc=window.ShadyCSS.nativeCss:window.ShadyCSS?(Nc(window.ShadyCSS),window.ShadyCSS=void 0):Nc(window.WebComponents&&window.WebComponents.flags);var N=Mc;var Pc=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Qc=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Rc=/(--[\w-]+)\s*([:,;)]|$)/gi,Sc=/(animation\s*:)|(animation-name\s*:)/,Tc=/@media\s(.*)/,Uc=/\{[^}]*\}/g;var Vc=new Set;function O(a,b){if(!a)return"";"string"===typeof a&&(a=Bc(a));b&&P(a,b);return Hc(a,N)}function Wc(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Bc(a.textContent));return a.__cssRules||null}function Xc(a){return!!a.parent&&7===a.parent.type}function P(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&4===f){var g=a.selector.match(Tc);g&&(window.matchMedia(g[1]).matches||(e=!0))}1===f?b(a):c&&7===f?c(a):1E3===f&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)P(g,b,c,d)}}
function Yc(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Zc(e,c,d);return e}var Q=null;function $c(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(Q?Q.nextSibling:null)||b.firstChild);return Q=a}function Zc(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);Q?a.compareDocumentPosition(Q)===Node.DOCUMENT_POSITION_PRECEDING&&(Q=a):Q=a}
function ad(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function bd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=ad(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=bd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function cd(a,b){L?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var dd=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function R(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a["extends"]);return{is:b,L:c}}function ed(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=ad(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function S(a){if(void 0!==Oc)return Oc;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function fd(a){a=void 0===a?"":a;return""!==a&&N?L?"shadow"===a:"shady"===a:!1};function gd(){}function hd(a,b){var c=T;c.S(a,function(d){c.element(d,b||"")})}k=gd.prototype;k.S=function(a,b){a.nodeType===Node.ELEMENT_NODE&&b(a);if(a="template"===a.localName?(a.content||a._content||a).childNodes:a.children||a.childNodes)for(var c=0;c<a.length;c++)this.S(a[c],b)};
k.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),cd(a,b)):cd(a,(d?d+" ":"")+"style-scope "+b)}};function id(a,b,c){var d=T;d.S(a,function(e){d.element(e,b,!0);d.element(e,c)})}function jd(a,b){var c=T;c.S(a,function(d){c.element(d,b||"",!0)})}
function kd(a,b,c,d,e){var f=T;e=void 0===e?"":e;""===e&&(L||"shady"===(void 0===d?"":d)?e=O(b,c):(a=R(a),e=ld(f,b,a.is,a.L,c)+"\n\n"));return e.trim()}function ld(a,b,c,d,e){var f=a.Z(c,d);c=a.ma(c);return O(b,function(g){g.Jb||(a.ya(g,a.ea,c,f),g.Jb=!0);e&&e(g,c,f)})}k.ma=function(a){return a?"."+a:""};k.Z=function(a,b){return b?"[is="+a+"]":a};k.ya=function(a,b,c,d){a.selector=a.h=this.za(a,b,c,d)};
k.za=function(a,b,c,d){var e=ed(a.selector);if(!Xc(a)){a=0;for(var f=e.length,g=void 0;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.filter(function(h){return!!h}).join(",")};k.Ba=function(a){return a.replace(md,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};
k.ob=function(a){for(var b=[],c;c=a.match(nd);){var d=c.index,e=ad(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{ja:a,matches:b}};k.rb=function(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])};
k.ea=function(a,b,c){var d=this,e=!1;a=a.trim();var f=md.test(a);f&&(a=a.replace(md,function(l,m,n){return":"+m+"("+n.replace(/\s/g,"")+")"}),a=this.Ba(a));var g=nd.test(a);if(g){var h=this.ob(a);a=h.ja;h=h.matches}a=a.replace(od,":host $1");a=a.replace(pd,function(l,m,n){e||(l=d.xb(n,m,b,c),e=e||l.stop,m=l.Db,n=l.value);return m+n});g&&(a=this.rb(a,h));f&&(a=this.Ba(a));return a=a.replace(qd,function(l,m,n,t){return'[dir="'+n+'"] '+m+t+", "+m+'[dir="'+n+'"]'+t})};
k.xb=function(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=this.zb(a,d):0!==e&&(a=c?this.Aa(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(rd,function(g,h){return" > "+h}))}return{value:a,Db:b,stop:f}};k.Aa=function(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")};
k.zb=function(a,b){var c=a.match(sd);return(c=c&&c[2].trim()||"")?c[0].match(td)?a.replace(sd,function(d,e,f){return b+f}):c.split(td)[0]===b?c:"should_not_match":a.replace(":host",b)};function ud(a){":root"===a.selector&&(a.selector="html")}k.yb=function(a){return a.match(":host")?"":a.match("::slotted")?this.ea(a,":not(.style-scope)"):this.Aa(a.trim(),":not(.style-scope)")};da.Object.defineProperties(gd.prototype,{N:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var md=/:(nth[-\w]+)\(([^)]+)\)/,pd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,td=/[[.:#*]/,od=/^(::slotted)/,sd=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,rd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,qd=/(.*):dir\((?:(ltr|rtl))\)(.*)/,nd=/:(?:matches|any|-(?:webkit|moz)-any)/,T=new gd;function U(a,b,c,d,e){this.s=a||null;this.placeholder=b||null;this.ia=c||[];this.H=null;this.cssBuild=e||"";this.L=d||"";this.F=this.j=this.o=null}function V(a){return a?a.__styleInfo:null}function vd(a,b){return a.__styleInfo=b}U.prototype.eb=function(){return this.s};U.prototype._getStyleRules=U.prototype.eb;function wd(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var xd=navigator.userAgent.match("Trident");function W(){}function yd(a){var b={},c=[],d=0;P(a,function(f){zd(f);f.index=d++;f=f.c.cssText;for(var g;g=Rc.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.gb=c;a=[];for(var e in b)a.push(e);return a}
function zd(a){if(!a.c){var b={},c={};Ad(a,c)&&(b.m=c,a.rules=null);b.cssText=a.parsedCssText.replace(Uc,"").replace(Pc,"");a.c=b}}function Ad(a,b){var c=a.c;if(c){if(c.m)return Object.assign(b,c.m),!0}else{c=a.parsedCssText;for(var d;a=Pc.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function Bd(a,b,c){b&&(b=0<=b.indexOf(";")?Cd(a,b,c):bd(b,function(d,e,f,g){if(!e)return d+g;(e=Bd(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=Bd(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function Cd(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){Qc.lastIndex=0;if(f=Qc.exec(e))e=Bd(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=Bd(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Dd(a,b){var c={},d=[];P(a,function(e){e.c||zd(e);var f=e.h||e.parsedSelector;b&&e.c.m&&f&&wd.call(b,f)&&(Ad(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{m:c,key:d}}
function Ed(a,b,c,d){b.c||zd(b);if(b.c.m){var e=R(a);a=e.is;e=e.L;e=a?T.Z(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.h||(b.h=T.za(b,T.ea,T.ma(a),e)),c=b.h||e),d({ja:c,Ib:h,Vb:g})}}function Fd(a,b,c){var d={},e={};P(b,function(f){Ed(a,f,c,function(g){wd.call(a._element||a,g.ja)&&(g.Ib?Ad(f,d):Ad(f,e))})},null,!0);return{Nb:e,Hb:d}}
function Gd(a,b,c,d){var e=R(b),f=T.Z(e.is,e.L),g=new RegExp("(?:^|[^.#[:])"+(b["extends"]?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=V(b);e=h.s;h=h.cssBuild;var l=a.Ua(b,e,d);return kd(b,e,function(m){var n="";m.c||zd(m);m.c.cssText&&(n=Cd(a,m.c.cssText,c));m.cssText=n;if(!L&&!Xc(m)&&m.cssText){var t=n=m.cssText;null==m.Ca&&(m.Ca=Sc.test(n));if(m.Ca)if(null==m.W){m.W=[];for(var B in l)t=l[B],t=t(n),n!==t&&(n=t,m.W.push(B))}else{for(B=0;B<m.W.length;++B)t=l[m.W[B]],n=t(n);t=n}m.cssText=t;a.vb(m,
g,f,d)}},h)}W.prototype.Ua=function(a,b,c){a=b.gb;b={};if(!L&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.ub(e,c),b[e.keyframesName]=this.hb(e);return b};W.prototype.hb=function(a){return function(b){return b.replace(a.Kb,a.Ha)}};W.prototype.ub=function(a,b){a.Kb=new RegExp("\\b"+a.keyframesName+"(?!\\B|-)","g");a.Ha=a.keyframesName+"-"+b;a.h=a.h||a.selector;a.selector=a.h.replace(a.keyframesName,a.Ha)};
W.prototype.vb=function(a,b,c,d){a.h=a.h||a.selector;d="."+d;for(var e=ed(a.h),f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};function Hd(a,b){var c=Id,d=Wc(a);a.textContent=O(d,function(e){var f=e.cssText=e.parsedCssText;e.c&&e.c.cssText&&(f=f.replace(Ic,"").replace(Jc,""),e.cssText=Cd(c,f,b))})}da.Object.defineProperties(W.prototype,{Ja:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Id=new W;var X={},Jd=window.customElements;if(Jd&&!L&&!M){var Kd=Jd.define;Jd.define=function(a,b,c){X[a]||(X[a]=$c(a));Kd.call(Jd,a,b,c)}};function Ld(){this.cache={};this.Sb=100}Ld.prototype.Cb=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.m[e]!==b[e])return!1}return!0};Ld.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({m:b,styleElement:c,j:d});e.length>this.Sb&&e.shift();this.cache[a]=e};Ld.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.Cb(e,b,c))return e}};function Md(){}var Nd=new RegExp(T.N+"\\s*([^\\s]*)");function Od(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Nd))?a[1]:""}function Pd(a){var b=dd(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?R(a).is:""}
function Qd(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=Od(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===S(e)))jd(e,g);else if(f instanceof ShadowRoot)for(f=Pd(e),f!==g&&id(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+T.N+")"),g=0;g<e.length;g++){f=e[g];
var h=Pd(f);h&&T.element(f,h)}}}}}
if(!(L||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var Rd=new MutationObserver(Qd),Sd=function(a){Rd.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Sd(document);else{var Td=function(){Sd(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Td):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Td();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Td()})}Md=function(){Qd(Rd.takeRecords())}};var Ud={};var Vd=Promise.resolve();function Wd(a){if(a=Ud[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Xd(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Yd(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Vd.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var Zd={},$d=new Ld;function Y(){this.wa={};this.C=document.documentElement;var a=new Ac;a.rules=[];this.u=vd(this.C,new U(a));this.aa=!1;this.g=this.f=null}k=Y.prototype;k.flush=function(){Md()};k.$a=function(a){var b=this.wa[a]=(this.wa[a]||0)+1;return a+"-"+b};k.Fb=function(a){return Wc(a)};k.Rb=function(a){return O(a)};
k.Za=function(a){var b=[];a=a.content.querySelectorAll("style");for(var c=0;c<a.length;c++){var d=a[c];if(d.hasAttribute("shady-unscoped")){if(!L){var e=d.textContent;Vc.has(e)||(Vc.add(e),e=d.cloneNode(!0),document.head.appendChild(e));d.parentNode.removeChild(d)}}else b.push(d.textContent),d.parentNode.removeChild(d)}return b.join("").trim()};k.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
k.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!M){L||X[b]||(X[b]=$c(b));a._prepared=!0;a.name=b;a["extends"]=c;Ud[b]=a;var d=S(a),e=fd(d);c={is:b,"extends":c};var f=this.Za(a)+(Zd[b]||"");this.I();if(!e){var g;if(g=!d)g=Qc.test(f)||Pc.test(f),Qc.lastIndex=0,Pc.lastIndex=0;var h=Bc(f);g&&N&&this.f&&this.f.transformRules(h,b);a._styleAst=h}g=[];N||(g=yd(a._styleAst));if(!g.length||N)b=this.ab(c,a._styleAst,L?a.content:null,X[b]||null,d,e?f:""),a._style=b;a.nb=g}};
k.Lb=function(a,b){Zd[b]=a.join(" ")};k.prepareTemplateDom=function(a,b){if(!M){var c=S(a);L||"shady"===c||a._domPrepared||(a._domPrepared=!0,hd(a.content,b))}};k.ab=function(a,b,c,d,e,f){f=kd(a,b,null,e,f);return f.length?Yc(f,a.is,c,d):null};k.ua=function(a){var b=R(a),c=b.is;b=b.L;var d=X[c]||null,e=Ud[c];if(e){c=e._styleAst;var f=e.nb;e=S(e);b=new U(c,d,f,b,e);vd(a,b);return b}};
k.Va=function(){!this.f&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this.f=window.ShadyCSS.ApplyShim,this.f.invalidCallback=Wd)};k.Wa=function(){var a=this;!this.g&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.g=window.ShadyCSS.CustomStyleInterface,this.g.transformCallback=function(b){a.Ga(b)},this.g.validateCallback=function(){requestAnimationFrame(function(){(a.g.enqueued||a.aa)&&a.flushCustomStyles()})})};k.I=function(){this.Va();this.Wa()};
k.flushCustomStyles=function(){if(!M&&(this.I(),this.g)){var a=this.g.processStyles();this.g.enqueued&&!fd(this.u.cssBuild)&&(N?this.u.cssBuild||this.tb(a):(this.fa(this.C,this.u),this.Na(a),this.aa&&this.styleDocument()),this.g.enqueued=!1)}};k.styleElement=function(a,b){if(M){if(b){V(a)||vd(a,new U(null));var c=V(a);this.sa(c,b);ae(this,a,c)}}else if(c=V(a)||this.ua(a))this.ba(a)||(this.aa=!0),b&&this.sa(c,b),N?ae(this,a,c):(this.flush(),this.fa(a,c),c.ia&&c.ia.length&&this.Oa(a,c))};
k.sa=function(a,b){a.H=a.H||{};Object.assign(a.H,b)};function ae(a,b,c){var d=R(b).is;if(c.H){var e=c.H,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}if(((e=Ud[d])||a.ba(b))&&(!e||""===S(e))&&e&&e._style&&!Xd(e)){if(Xd(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)a.I(),a.f&&a.f.transformRules(e._styleAst,d),e._style.textContent=kd(b,c.s),Yd(e);L&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=kd(b,c.s));c.s=e._styleAst}}
k.da=function(a){return(a=dd(a).getRootNode().host)?V(a)||this.ua(a)?a:this.da(a):this.C};k.ba=function(a){return a===this.C};
k.Oa=function(a,b){var c=R(a).is,d=$d.fetch(c,b.o,b.ia),e=d?d.styleElement:null,f=b.j;b.j=d&&d.j||this.$a(c);var g=b.j;var h=Id;h=e?e.textContent||"":Gd(h,a,b.o,g);var l=V(a),m=l.F;m&&!L&&m!==e&&(m._useCount--,0>=m._useCount&&m.parentNode&&m.parentNode.removeChild(m));L?l.F?(l.F.textContent=h,e=l.F):h&&(e=Yc(h,g,a.shadowRoot,l.placeholder)):e?e.parentNode||(xd&&-1<h.indexOf("@media")&&(e.textContent=h),Zc(e,null,l.placeholder)):h&&(e=Yc(h,g,null,l.placeholder));e&&(e._useCount=e._useCount||0,l.F!=
e&&e._useCount++,l.F=e);g=e;L||(e=b.j,l=h=a.getAttribute("class")||"",f&&(l=h.replace(new RegExp("\\s*x-scope\\s*"+f+"\\s*","g")," ")),l+=(l?" ":"")+"x-scope "+e,h!==l&&cd(a,l));d||$d.store(c,b.o,g,b.j);return g};k.fa=function(a,b){var c=this.da(a),d=V(c),e=d.o;c===this.C||e||(this.fa(c,d),e=d.o);c=Object.create(e||null);e=Fd(a,b.s,b.cssBuild);a=Dd(d.s,a).m;Object.assign(c,e.Hb,a,e.Nb);this.kb(c,b.H);a=Id;d=Object.getOwnPropertyNames(c);e=0;for(var f;e<d.length;e++)f=d[e],c[f]=Bd(a,c[f],c);b.o=c};
k.kb=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};k.styleDocument=function(a){this.styleSubtree(this.C,a)};k.styleSubtree=function(a,b){var c=dd(a),d=c.shadowRoot;(d||this.ba(a))&&this.styleElement(a,b);if(a=d&&(d.children||d.childNodes))for(c=0;c<a.length;c++)this.styleSubtree(a[c]);else if(c=c.children||c.childNodes)for(a=0;a<c.length;a++)this.styleSubtree(c[a])};k.tb=function(a){for(var b=0;b<a.length;b++){var c=this.g.getStyleForCustomStyle(a[b]);c&&this.sb(c)}};
k.Na=function(a){for(var b=0;b<a.length;b++){var c=this.g.getStyleForCustomStyle(a[b]);c&&Hd(c,this.u.o)}};k.Ga=function(a){var b=this,c=S(a);c!==this.u.cssBuild&&(this.u.cssBuild=c);if(!fd(c)){var d=Wc(a);P(d,function(e){if(L)ud(e);else{var f=T;e.selector=e.parsedSelector;ud(e);f.ya(e,f.yb)}N&&""===c&&(b.I(),b.f&&b.f.transformRule(e))});N?a.textContent=O(d):this.u.s.rules.push(d)}};k.sb=function(a){if(N&&this.f){var b=Wc(a);this.I();this.f.transformRules(b);a.textContent=O(b)}};
k.getComputedStyleValue=function(a,b){var c;N||(c=(V(a)||V(this.da(a))).o[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};k.Qb=function(a,b){var c=dd(a).getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===T.N){c=d[e+1];break}}}c&&b.push(T.N,c);N||(c=V(a))&&c.j&&b.push(Id.Ja,c.j);cd(a,b.join(" "))};k.wb=function(a){return V(a)};k.Pb=function(a,b){T.element(a,b)};
k.Tb=function(a,b){T.element(a,b,!0)};k.Ob=function(a){return Pd(a)};k.Eb=function(a){return Od(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Qb;Y.prototype._styleInfoForNode=Y.prototype.wb;
Y.prototype.transformCustomStyleForDocument=Y.prototype.Ga;Y.prototype.getStyleAst=Y.prototype.Fb;Y.prototype.styleAstToString=Y.prototype.Rb;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Y.prototype.scopeNode=Y.prototype.Pb;Y.prototype.unscopeNode=Y.prototype.Tb;Y.prototype.scopeForNode=Y.prototype.Ob;Y.prototype.currentScopeForNode=Y.prototype.Eb;Y.prototype.prepareAdoptedCssText=Y.prototype.Lb;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return L}},nativeCss:{get:function(){return N}}});var Z=new Y,be,ce;window.ShadyCSS&&(be=window.ShadyCSS.ApplyShim,ce=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:N,nativeShadow:L,cssBuild:Oc,disableRuntime:M};be&&(window.ShadyCSS.ApplyShim=be);ce&&(window.ShadyCSS.CustomStyleInterface=ce);})();
//# sourceMappingURL=webcomponents-sd.js.sourcemap
